/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:54 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _UIActivityHelperDelegate <NSObject>
@optional
-(id)activityHelper:(id)arg1 activitiesForActivityType:(id)arg2 matchingContext:(id)arg3 sessionID:(id)arg4;
-(id)activityHelper:(id)arg1 predictionContextForSessionID:(id)arg2;

@required
-(BOOL)activityHelper:(id)arg1 matchingWithContext:(id)arg2 shouldIncludeSystemActivityType:(id)arg3 sessionID:(id)arg4;

@end

