/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:55 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <sharingd/NSCopying.h>

@interface AWDSharingCMS2ServerTaskResponse : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	int _errorCode;
	unsigned _httpStatusCode;
	unsigned _idmsEnv;
	unsigned _type;
	SCD_Struct_SD6 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasHttpStatusCode; 
@property (assign,nonatomic) unsigned httpStatusCode;                   //@synthesize httpStatusCode=_httpStatusCode - In the implementation block
@property (assign,nonatomic) BOOL hasErrorCode; 
@property (assign,nonatomic) int errorCode;                             //@synthesize errorCode=_errorCode - In the implementation block
@property (assign,nonatomic) BOOL hasType; 
@property (assign,nonatomic) unsigned type;                             //@synthesize type=_type - In the implementation block
@property (assign,nonatomic) BOOL hasIdmsEnv; 
@property (assign,nonatomic) unsigned idmsEnv;                          //@synthesize idmsEnv=_idmsEnv - In the implementation block
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)description;
-(unsigned)type;
-(void)setType:(unsigned)arg1 ;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(int)errorCode;
-(void)mergeFrom:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(BOOL)hasTimestamp;
-(void)setErrorCode:(int)arg1 ;
-(void)setHasErrorCode:(BOOL)arg1 ;
-(BOOL)hasErrorCode;
-(void)setHasType:(BOOL)arg1 ;
-(BOOL)hasType;
-(unsigned)httpStatusCode;
-(void)setHttpStatusCode:(unsigned)arg1 ;
-(void)setHasHttpStatusCode:(BOOL)arg1 ;
-(BOOL)hasHttpStatusCode;
-(void)setIdmsEnv:(unsigned)arg1 ;
-(void)setHasIdmsEnv:(BOOL)arg1 ;
-(BOOL)hasIdmsEnv;
-(unsigned)idmsEnv;
@end

