/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:55 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSUUID, NSString;

@interface SDActivityPayloadReplyRecord : NSObject {

	NSUUID* _messageIdentifier;
	NSUUID* _requestIdentifier;
	NSUUID* _activityIdentifier;
	NSString* _deviceIdentifier;

}

@property (nonatomic,copy) NSUUID * messageIdentifier;               //@synthesize messageIdentifier=_messageIdentifier - In the implementation block
@property (nonatomic,copy) NSUUID * requestIdentifier;               //@synthesize requestIdentifier=_requestIdentifier - In the implementation block
@property (nonatomic,copy) NSUUID * activityIdentifier;              //@synthesize activityIdentifier=_activityIdentifier - In the implementation block
@property (nonatomic,copy) NSString * deviceIdentifier;              //@synthesize deviceIdentifier=_deviceIdentifier - In the implementation block
-(id)description;
-(NSUUID *)requestIdentifier;
-(NSString *)deviceIdentifier;
-(void)setDeviceIdentifier:(NSString *)arg1 ;
-(void)setRequestIdentifier:(NSUUID *)arg1 ;
-(NSUUID *)messageIdentifier;
-(void)setMessageIdentifier:(NSUUID *)arg1 ;
-(NSUUID *)activityIdentifier;
-(void)setActivityIdentifier:(NSUUID *)arg1 ;
@end

