/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:55 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/SDActivityRequestRecord.h>

@class NSUUID, RPCompanionLinkClient;

@interface SDActivityEncryptionKeyRequestRecord : SDActivityRequestRecord {

	NSUUID* _previousKeyIdentifier;
	RPCompanionLinkClient* _linkClient;

}

@property (nonatomic,retain) NSUUID * previousKeyIdentifier;                  //@synthesize previousKeyIdentifier=_previousKeyIdentifier - In the implementation block
@property (nonatomic,retain) RPCompanionLinkClient * linkClient;              //@synthesize linkClient=_linkClient - In the implementation block
-(id)description;
-(void)dealloc;
-(NSUUID *)previousKeyIdentifier;
-(void)setPreviousKeyIdentifier:(NSUUID *)arg1 ;
-(RPCompanionLinkClient *)linkClient;
-(void)setLinkClient:(RPCompanionLinkClient *)arg1 ;
@end

