/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:56 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, NSString, NSURLSession, NSDictionary, NSURLRequest;

@interface SDAppleIDServerTask : NSObject {

	BOOL _activated;
	BOOL _invalidated;
	NSObject*<OS_dispatch_queue> _dispatchQueue;
	/*^block*/id _responseHandler;
	NSString* _appleID;
	NSString* _gsToken;
	NSURLSession* _session;
	NSDictionary* _taskInfo;
	long long _type;
	NSURLRequest* _urlRequest;

}

@property (assign,nonatomic) BOOL activated;                                          //@synthesize activated=_activated - In the implementation block
@property (nonatomic,readonly) NSString * appleID;                                    //@synthesize appleID=_appleID - In the implementation block
@property (nonatomic,retain) NSString * gsToken;                                      //@synthesize gsToken=_gsToken - In the implementation block
@property (assign,nonatomic) BOOL invalidated;                                        //@synthesize invalidated=_invalidated - In the implementation block
@property (nonatomic,retain) NSURLSession * session;                                  //@synthesize session=_session - In the implementation block
@property (nonatomic,readonly) NSDictionary * taskInfo;                               //@synthesize taskInfo=_taskInfo - In the implementation block
@property (nonatomic,readonly) long long type;                                        //@synthesize type=_type - In the implementation block
@property (nonatomic,retain) NSURLRequest * urlRequest;                               //@synthesize urlRequest=_urlRequest - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> dispatchQueue;              //@synthesize dispatchQueue=_dispatchQueue - In the implementation block
@property (nonatomic,copy) id responseHandler;                                        //@synthesize responseHandler=_responseHandler - In the implementation block
-(id)description;
-(void)_activate;
-(void)invalidate;
-(void)_invalidate;
-(long long)type;
-(NSURLSession *)session;
-(void)setSession:(NSURLSession *)arg1 ;
-(BOOL)activated;
-(NSObject*<OS_dispatch_queue>)dispatchQueue;
-(void)activate;
-(BOOL)invalidated;
-(void)setInvalidated:(BOOL)arg1 ;
-(NSString *)appleID;
-(void)setResponseHandler:(id)arg1 ;
-(id)responseHandler;
-(void)setDispatchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(NSURLRequest *)urlRequest;
-(void)setActivated:(BOOL)arg1 ;
-(void)setUrlRequest:(NSURLRequest *)arg1 ;
-(NSDictionary *)taskInfo;
-(id)initWithType:(long long)arg1 appleID:(id)arg2 info:(id)arg3 ;
-(void)_callResponseHandlerWithInfo:(id)arg1 errorInfo:(id)arg2 error:(int)arg3 ;
-(NSString *)gsToken;
-(void)_handleURLIsAvailable:(id)arg1 error:(int)arg2 completion:(/*^block*/id)arg3 ;
-(void)_urlWithCompletion:(/*^block*/id)arg1 ;
-(BOOL)_isTaskInfoValid;
-(void)_sendRequest;
-(void)_callResponseHandlerWithInfo:(id)arg1 error:(int)arg2 ;
-(void)_handleTaskResponse:(id)arg1 withData:(id)arg2 error:(int)arg3 ;
-(void)_handleURLRequestIsAvailable;
-(void)_urlRequestWithCompletion:(/*^block*/id)arg1 ;
-(void)_handleServerError:(long long)arg1 withStatusCode:(long long)arg2 nextSuggestedAttemptDelay:(long long)arg3 ;
-(id)_parseServerResponse:(id)arg1 ;
-(id)_parseCreateCertificateResponse:(id)arg1 ;
-(id)_parseFetchCertificateResponse:(id)arg1 ;
-(id)_parseGetMyInfoResponse:(id)arg1 ;
-(id)_parseFindPersonResponse:(id)arg1 ;
-(void)setGsToken:(NSString *)arg1 ;
-(void)_handleGSTokenIsAvailable;
@end

