/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:54 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <sharingd/NSNetServiceBrowserDelegate.h>

@protocol OS_dispatch_source;
@class NSMutableSet, NSObject, NSNetServiceBrowser, NSString;

@interface SDDomainBrowser : NSObject <NSNetServiceBrowserDelegate> {

	int _clientCount;
	BOOL _sendNotification;
	NSMutableSet* _domains;
	NSObject*<OS_dispatch_source> _timer;
	CFDictionaryRef _domainTree;
	NSNetServiceBrowser* _domainBrowser;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedBrowser;
-(id)init;
-(void)start;
-(void)stop;
-(void)netServiceBrowser:(id)arg1 didNotSearch:(id)arg2 ;
-(void)netServiceBrowser:(id)arg1 didRemoveDomain:(id)arg2 moreComing:(BOOL)arg3 ;
-(void)netServiceBrowser:(id)arg1 didFindDomain:(id)arg2 moreComing:(BOOL)arg3 ;
-(void)postNotification;
-(void)restart;
-(void)statusChanged:(id)arg1 ;
-(id)childrenForNode:(SFNodeRef)arg1 ;
-(void)browseAfterDelay:(double)arg1 ;
-(void)scheduleBrowser;
-(id)displayNameForDomain:(id)arg1 ;
-(void)parseDomain:(id)arg1 ;
-(void)buildNodes;
@end

