/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:54 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SDUnlockIDSControllerDelegate <NSObject>
@optional
-(void)idsController:(id)arg1 didReceiveProtoData:(id)arg2 forType:(unsigned short)arg3;
-(void)idsControllerNearbyStateChanged:(id)arg1;
-(void)idsControllerSpaceDidBecomeAvailable:(id)arg1;

@end

