/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:56 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SFPairedDeviceDaemonInterface <SDXPCDaemonProtocol>
@required
-(void)requestAnimationDateWithCompletion:(/*^block*/id)arg1;
-(void)sendAnimationDate:(id)arg1;
-(void)initialViewControllerDidAppear;
-(void)initialViewControllerDidDisappear;
-(void)sendDismissUIWithReason:(long long)arg1;
-(void)sendDashboardEntryWithName:(id)arg1 dict:(id)arg2;
-(void)triggerChargingUIWithDismissHandler:(/*^block*/id)arg1;

@end

