/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:07:55 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVAirPlay.app/TVAirPlay
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol TVAirPlayAPRKSession <TVAirPlaySession>
@property (assign,nonatomic,__weak) id<TVAirPlayAPRKSessionDelegate> delegate; 
@required
-(id<TVAirPlayAPRKSessionDelegate>)delegate;
-(void)setDelegate:(id)arg1;

@end

