/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 2:01:20 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVNowPlayingService.app/TVNowPlayingService
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSIndexSet;

@interface TVNPArrayChange : NSObject {

	long long _changeType;
	NSIndexSet* _sourceIndexes;
	NSIndexSet* _destinationIndexes;

}

@property (nonatomic,readonly) long long changeType;                              //@synthesize changeType=_changeType - In the implementation block
@property (nonatomic,copy,readonly) NSIndexSet * sourceIndexes;                   //@synthesize sourceIndexes=_sourceIndexes - In the implementation block
@property (nonatomic,copy,readonly) NSIndexSet * destinationIndexes;              //@synthesize destinationIndexes=_destinationIndexes - In the implementation block
+(id)arrayChangeInsert:(id)arg1 ;
+(id)arrayChangeDelete:(id)arg1 ;
+(id)arrayChangeMove:(unsigned long long)arg1 toIndex:(unsigned long long)arg2 ;
-(id)description;
-(long long)changeType;
-(NSIndexSet *)sourceIndexes;
-(NSIndexSet *)destinationIndexes;
@end

