/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 2:01:20 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVNowPlayingService.app/TVNowPlayingService
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UICollectionViewFlowLayoutInvalidationContext.h>

@interface TVNPRoutingRoutesCollectionViewLayoutInvalidationContext : UICollectionViewFlowLayoutInvalidationContext {

	BOOL _invalidateVolumeSliderLayoutAttributes;

}

@property (assign,nonatomic) BOOL invalidateVolumeSliderLayoutAttributes;              //@synthesize invalidateVolumeSliderLayoutAttributes=_invalidateVolumeSliderLayoutAttributes - In the implementation block
-(BOOL)invalidateVolumeSliderLayoutAttributes;
-(void)setInvalidateVolumeSliderLayoutAttributes:(BOOL)arg1 ;
@end

