/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:55:31 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Siri.app/Siri
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Siri/Siri-Structs.h>
#import <UIKitCore/UIButton.h>

@class NSString;

@interface SRStarkGatekeeperButton : UIButton {

	NSString* _buttonTitle;

}

@property (nonatomic,retain) NSString * buttonTitle;              //@synthesize buttonTitle=_buttonTitle - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(NSString *)buttonTitle;
-(void)layoutSubviews;
-(void)setSemanticContentAttribute:(long long)arg1 ;
-(void)setButtonTitle:(NSString *)arg1 ;
-(BOOL)_isRTL;
-(void)_updateChevronForRTL:(BOOL)arg1 ;
@end

