/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:55:31 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Siri.app/Siri
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Siri/SRStarkConfirmationSnippetController.h>

@class NSTimer, SRStarkConfirmationSnippetView, SRStarkEmergencyCallConfirmationSnippetView;

@interface SRStarkEmergencyCallConfirmationSnippetController : SRStarkConfirmationSnippetController {

	long long _seconds;
	NSTimer* _countdownTimer;
	SRStarkConfirmationSnippetView* _snippetView;

}

@property (readonly) SRStarkEmergencyCallConfirmationSnippetView * emergencySnippetView; 
-(void)viewDidAppear:(BOOL)arg1 ;
-(long long)preferredUserInterfaceStyle;
-(id)initWithAceObject:(id)arg1 conversationItemIdentifier:(id)arg2 interactionStyle:(long long)arg3 currentTurnContext:(id)arg4 ;
-(void)_updateCountdown:(id)arg1 ;
-(id)snippetView;
-(SRStarkEmergencyCallConfirmationSnippetView *)emergencySnippetView;
-(void)setSnippetView:(id)arg1 ;
@end

