/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:54:57 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Setup.app/Setup
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, CALayer, NSDictionary;

@interface MicaAnimator : NSObject {

	NSString* _path;
	CALayer* _rootLayer;
	NSDictionary* _publishedObjects;
	double _secondsToLoad;
	double _requestedLoad;
	double _documentDuration;

}

@property (nonatomic,retain) NSString * path;                              //@synthesize path=_path - In the implementation block
@property (nonatomic,__weak,readonly) NSString * name; 
@property (nonatomic,retain) CALayer * rootLayer;                          //@synthesize rootLayer=_rootLayer - In the implementation block
@property (nonatomic,retain) NSDictionary * publishedObjects;              //@synthesize publishedObjects=_publishedObjects - In the implementation block
@property (assign,nonatomic) double secondsToLoad;                         //@synthesize secondsToLoad=_secondsToLoad - In the implementation block
@property (assign,nonatomic) double requestedLoad;                         //@synthesize requestedLoad=_requestedLoad - In the implementation block
@property (assign,nonatomic) double documentDuration;                      //@synthesize documentDuration=_documentDuration - In the implementation block
+(id)rootDictForPath:(id)arg1 ;
+(id)bestURLForUserInterfaceFileName:(id)arg1 ;
-(NSString *)name;
-(NSString *)path;
-(void)setPath:(NSString *)arg1 ;
-(id)initWithPath:(id)arg1 ;
-(void)removeFromSuperlayer;
-(void)setHidden:(BOOL)arg1 ;
-(CALayer *)rootLayer;
-(void)setRootLayer:(CALayer *)arg1 ;
-(void)setPublishedObjects:(NSDictionary *)arg1 ;
-(NSDictionary *)publishedObjects;
-(id)initWithFileName:(id)arg1 forUserInterface:(BOOL)arg2 ;
-(id)publishedLayerWithKey:(id)arg1 ;
-(void)addToLayer:(id)arg1 onTop:(BOOL)arg2 ;
-(id)initWithPath:(id)arg1 rootLayer:(id)arg2 publishedObjects:(id)arg3 ;
-(void)setRequestedLoad:(double)arg1 ;
-(void)setDocumentDuration:(double)arg1 ;
-(id)publishedObjectWithKey:(id)arg1 required:(BOOL)arg2 ;
-(double)secondsToLoad;
-(void)setSecondsToLoad:(double)arg1 ;
-(double)requestedLoad;
-(double)documentDuration;
@end

