/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:54:56 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Setup.app/Setup
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SATVChoiceViewDataSource <NSObject>
@optional
-(id)footerButtonTextForChoiceView:(id)arg1;
-(id)footnoteTextForChoiceView:(id)arg1;
-(id)auxiliaryButtonTextForChoiceView:(id)arg1;
-(id)footerButtonViewForChoiceView:(id)arg1;
-(id)auxiliaryButtonViewForChoiceView:(id)arg1;

@required
-(id)choiceView:(id)arg1 textForChoice:(unsigned long long)arg2;
-(id)titleTextForChoiceView:(id)arg1;
-(id)subtitleTextForChoiceView:(id)arg1;
-(id)choiceHeaderButtonTextForChoiceView:(id)arg1;

@end

