/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:54:56 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Setup.app/Setup
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Setup/SATVStepViewController.h>
#import <Setup/SATVTextEntryViewControllerDelegate.h>
#import <Setup/SATVAirplay2HomePickerViewControllerDelegate.h>
#import <Setup/SATVAirplay2RoomPickerViewControllerDelegate.h>
#import <Setup/SATVActionStep.h>

@class TVSStateMachine, UINavigationController, NSTimer, NSString;

@interface SATVAirplay2ViewController : SATVStepViewController <SATVTextEntryViewControllerDelegate, SATVAirplay2HomePickerViewControllerDelegate, SATVAirplay2RoomPickerViewControllerDelegate, SATVActionStep> {

	/*^block*/id _completionHandler;
	TVSStateMachine* _homeKitStateMachine;
	UINavigationController* _childNavigationController;
	/*^block*/id _textEntryCompletionHandler;
	NSTimer* _loadingTimer;

}

@property (getter=_childNavigationController,nonatomic,readonly) UINavigationController * childNavigationController;                             //@synthesize childNavigationController=_childNavigationController - In the implementation block
@property (setter=_setTextEntryCompletionHandler:,getter=_textEntryCompletionHandler,nonatomic,copy) id textEntryCompletionHandler;              //@synthesize textEntryCompletionHandler=_textEntryCompletionHandler - In the implementation block
@property (getter=_homeKitStateMachine,nonatomic,readonly) TVSStateMachine * homeKitStateMachine;                                                //@synthesize homeKitStateMachine=_homeKitStateMachine - In the implementation block
@property (setter=_setLoadingTimer:,getter=_loadingTimer,nonatomic,retain) NSTimer * loadingTimer;                                               //@synthesize loadingTimer=_loadingTimer - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy) id menuHandler; 
@property (nonatomic,readonly) BOOL isConfigured; 
@property (nonatomic,copy) id completionHandler;                                                                                                 //@synthesize completionHandler=_completionHandler - In the implementation block
+(BOOL)isSupported;
+(BOOL)isSupportedForUpgrade;
+(id)stableKey;
+(id)_trimCustomRoomName:(id)arg1 ;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)setCompletionHandler:(id)arg1 ;
-(id)completionHandler;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(id)_childNavigationController;
-(void)_moveOrAddLocalAccessoryToRoomWithName:(id)arg1 inHome:(id)arg2 ;
-(void)_moveOrAddLocalAccessoryToRoom:(id)arg1 inHome:(id)arg2 ;
-(void)textEntryViewController:(id)arg1 textDidChange:(id)arg2 ;
-(void)textEntryViewControllerDidCancel:(id)arg1 ;
-(void)textEntryViewController:(id)arg1 didEnterText:(id)arg2 ;
-(void)autoAdvance;
-(void)didEnterStateBackwards;
-(void)homePickerViewController:(id)arg1 didSelectHome:(id)arg2 ;
-(void)_postHomeConfigurationStateDidChangeEvent;
-(id)_homeKitStateMachine;
-(id)_makeRoomPickerViewControllerForHome:(id)arg1 ;
-(id)_makeHomePickerViewController;
-(void)_saveRoomName:(id)arg1 ;
-(void)__moveOrAddLocalAccessoryToRoomWithName:(id)arg1 inHome:(id)arg2 ;
-(void)_sendCompletionWithSuccess:(BOOL)arg1 ;
-(void)_presentCreateRoomFailedViewControllerWithError:(id)arg1 ;
-(void)_setLoadingTimer:(id)arg1 ;
-(void)_showPickerViewController;
-(void)_scheduleLoadingTimer;
-(void)_showLoadingViewController;
-(id)_makeLoadingViewController;
-(id)_makePickerViewController;
-(id)_loadingTimer;
-(void)_loadingTimerFired;
-(void)_setTextEntryCompletionHandler:(/*^block*/id)arg1 ;
-(/*^block*/id)_textEntryCompletionHandler;
-(void)roomPickerViewController:(id)arg1 didSelectExistingRoom:(id)arg2 ;
-(void)roomPickerViewController:(id)arg1 didSelectSuggestedRoom:(id)arg2 ;
-(void)roomPickerViewControllerWantsNewRoomViewController:(id)arg1 ;
-(void)_createDefaultHome;
@end

