/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:34 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/demod
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <demod/demod-Structs.h>
@class NSMutableArray;

@interface MSDDemoUpdateController : NSObject {

	BOOL _busy;
	BOOL _migrationDone;
	NSMutableArray* _order;
	NSRange _contentBeingInstalled;

}

@property (assign) BOOL busy;                                     //@synthesize busy=_busy - In the implementation block
@property (nonatomic,retain) NSMutableArray * order;              //@synthesize order=_order - In the implementation block
@property (assign) BOOL migrationDone;                            //@synthesize migrationDone=_migrationDone - In the implementation block
@property (assign) NSRange contentBeingInstalled;                 //@synthesize contentBeingInstalled=_contentBeingInstalled - In the implementation block
+(id)sharedInstance;
-(NSMutableArray *)order;
-(void)setOrder:(NSMutableArray *)arg1 ;
-(BOOL)busy;
-(void)setBusy:(BOOL)arg1 ;
-(NSRange)contentBeingInstalled;
-(BOOL)enrollWithServer:(id)arg1 name:(id)arg2 pairingCredential:(id)arg3 error:(id*)arg4 ;
-(BOOL)updateDemoContentWithServer:(id)arg1 ;
-(void)getDemoUpdateInProgress:(BOOL*)arg1 operationAllowed:(BOOL*)arg2 ;
-(BOOL)enrolledWith:(id)arg1 ;
-(BOOL)migrateDataWithBlockingUI:(int)arg1 ;
-(BOOL)continueToUpdateDemoContentWithServer:(id)arg1 ;
-(void)setTVSpecificSettings;
-(void)loadInstallationOrder:(id)arg1 ;
-(void)setContentBeingInstalled:(NSRange)arg1 ;
-(BOOL)installProvisioningProfiles;
-(void)checkWithTimeKeeper:(id)arg1 ;
-(BOOL)migrationDone;
-(BOOL)PLHasCompletedRestorePostProcessing;
-(BOOL)PLHasCompletedMomentAnalysis;
-(void)setMigrationDone:(BOOL)arg1 ;
-(BOOL)removeLowerPriorityAppsTillFreeSpace:(long long)arg1 ;
@end

