/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:34 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/demod
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, NSString, MSDProgressUpdater, NSSet, NSDictionary;

@interface MSDManifest : NSObject {

	NSMutableDictionary* _dict;
	NSString* _rootPath;
	MSDProgressUpdater* _progressUpdater;

}

@property (getter=pathSet,readonly) NSSet * pathSet; 
@property (retain) NSString * rootPath;                               //@synthesize rootPath=_rootPath - In the implementation block
@property (retain) NSDictionary * dict;                               //@synthesize dict=_dict - In the implementation block
@property (retain) MSDProgressUpdater * progressUpdater;              //@synthesize progressUpdater=_progressUpdater - In the implementation block
-(id)init;
-(void)dealloc;
-(id)initWithDictionary:(id)arg1 ;
-(NSDictionary *)dict;
-(void)setDict:(NSDictionary *)arg1 ;
-(NSString *)rootPath;
-(void)setRootPath:(NSString *)arg1 ;
-(id)metadataForFile:(id)arg1 ;
-(BOOL)addFilesFromPath:(id)arg1 relativeTo:(id)arg2 skip:(id)arg3 superSet:(id)arg4 ;
-(void)setMetadata:(id)arg1 forFile:(id)arg2 ;
-(BOOL)enumerateAndCollectMetaData:(id)arg1 relativeTo:(id)arg2 skip:(id)arg3 superSet:(id)arg4 handler:(/*^block*/id)arg5 ;
-(BOOL)folder:(id)arg1 contains:(id)arg2 ;
-(BOOL)path:(id)arg1 inSuperSet:(id)arg2 ;
-(BOOL)addFilesFromPath:(id)arg1 relativeTo:(id)arg2 skip:(id)arg3 ;
-(NSSet *)pathSet;
-(MSDProgressUpdater *)progressUpdater;
-(void)setProgressUpdater:(MSDProgressUpdater *)arg1 ;
@end

