/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:31 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/NRDUpdated
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NRDBackgroundActivitySchedulerInterface <NSObject>
@required
-(void)invalidate;
-(void)setTolerance:(double)arg1;
-(void)setInterval:(double)arg1;
-(void)setQualityOfService:(long long)arg1;
-(void)setPreregistered:(BOOL)arg1;
-(void)setDelay:(double)arg1;
-(void)setCheckInHandler:(id)arg1;
-(void)setRepeats:(BOOL)arg1;
-(void)set_appRefresh:(BOOL)arg1;
-(void)_setAdditionalXPCActivityProperties:(id)arg1;
-(void)identifier:(/*^block*/id)arg1;
-(void)qualityOfService:(/*^block*/id)arg1;
-(void)repeats:(/*^block*/id)arg1;
-(void)interval:(/*^block*/id)arg1;
-(void)tolerance:(/*^block*/id)arg1;
-(void)scheduleWithRemoteableBlock:(id)arg1;
-(void)shouldDefer:(/*^block*/id)arg1;
-(void)preregistered:(/*^block*/id)arg1;
-(void)delay:(/*^block*/id)arg1;
-(void)_isAppRefresh:(/*^block*/id)arg1;

@end

