/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:31 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/NRDUpdated
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NRDUpdated/NRDRemoteableBlockInterface.h>

@class NSString;

@interface NRDRemoteableBlock : NSObject <NRDRemoteableBlockInterface> {

	/*^block*/id _block;
	/*^block*/id _progressBlock;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithBlock:(/*^block*/id)arg1 ;
-(void)execute:(/*^block*/id)arg1 ;
-(id)initWithProgressBlock:(/*^block*/id)arg1 ;
-(void)progress:(id)arg1 ;
@end

