/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 2:01:09 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVPeripheralAgent.app/TVPeripheralAgent
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct __IOHIDManager* IOHIDManagerRef;

typedef struct IONotificationPort* IONotificationPortRef;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct __CFNumber* CFNumberRef;

