/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:12:59 AM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/lib/libtzupdate.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface TZUtilities : NSObject
+(id)stringWithContentsOfFileAtURL:(id)arg1 error:(id*)arg2 ;
+(BOOL)fileExistsAndIsSymbolicLinkAtURL:(id)arg1 ;
@end

