/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:52:09 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/AppStore.app/AppStore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AppStore/AppStore-Structs.h>
#import <AppStore/AppStore.BaseCollectionViewCell.h>

@interface AppStore.SearchButton : AppStore.BaseCollectionViewCell {

	 backgroundEffectView;
	 imageView;

}

@property (readonly,nonatomic) CGSize intrinsicContentSize; 
@property (readonly,nonatomic) double lastBaselineFromBottom; 
-(id)initWithFrame:(CGRect)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(CGSize)intrinsicContentSize;
-(void)layoutSubviews;
-(void)tintColorDidChange;
-(JUMeasurements)measurementsWithFitting:(CGSize)arg1 in:(id)arg2 ;
-(double)lastBaselineFromBottom;
@end

