/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:33 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/coreduetd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSProxy.h>

@protocol _DKDaemonInterface;
@class NSObject, NSXPCConnection, NSString, NSCountedSet;

@interface CDKnowledgeClientProxy : NSProxy {

	int _notifyToken;
	NSObject*<_DKDaemonInterface> _daemon;
	NSXPCConnection* _connection;
	NSString* _procName;
	NSCountedSet* _selectorInvocations;

}

@property (nonatomic,__weak,readonly) NSObject*<_DKDaemonInterface> daemon;              //@synthesize daemon=_daemon - In the implementation block
@property (nonatomic,__weak,readonly) NSXPCConnection * connection;                      //@synthesize connection=_connection - In the implementation block
@property (nonatomic,readonly) NSString * procName;                                      //@synthesize procName=_procName - In the implementation block
@property (nonatomic,readonly) NSCountedSet * selectorInvocations;                       //@synthesize selectorInvocations=_selectorInvocations - In the implementation block
-(BOOL)respondsToSelector:(SEL)arg1 ;
-(id)description;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(void)forwardInvocation:(id)arg1 ;
-(void)dealloc;
-(NSXPCConnection *)connection;
-(NSString *)procName;
-(NSObject*<_DKDaemonInterface>)daemon;
-(id)initWithDaemon:(id)arg1 connection:(id)arg2 ;
-(void)_logInvocationForSelector:(id)arg1 ;
-(NSCountedSet *)selectorInvocations;
@end

