/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:42 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/installd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <installd/MIContainer.h>

@class MIExecutableBundle, MIBundleMetadata;

@interface MIBundleContainer : MIContainer {

	MIExecutableBundle* _bundle;
	MIBundleMetadata* _bundleMetadata;

}

@property (nonatomic,copy) MIBundleMetadata * bundleMetadata;                   //@synthesize bundleMetadata=_bundleMetadata - In the implementation block
@property (nonatomic,readonly) MIExecutableBundle * bundle;                     //@synthesize bundle=_bundle - In the implementation block
@property (nonatomic,readonly) unsigned bundleMaxLinkedSDKVersion; 
+(id)appBundleContainerWithIdentifier:(id)arg1 createIfNeeded:(BOOL)arg2 created:(BOOL*)arg3 error:(id*)arg4 ;
+(id)vpnPluginBundleContainerWithIdentifier:(id)arg1 createIfNeeded:(BOOL)arg2 created:(BOOL*)arg3 error:(id*)arg4 ;
+(id)pluginKitPluginBundleContainerWithIdentifier:(id)arg1 createIfNeeded:(BOOL)arg2 created:(BOOL*)arg3 error:(id*)arg4 ;
+(id)tempAppBundleContainerWithIdentifier:(id)arg1 error:(id*)arg2 ;
+(id)tempVPNPluginBundleContainerWithIdentifier:(id)arg1 error:(id*)arg2 ;
+(id)tempPluginKitPluginBundleContainerWithIdentifier:(id)arg1 error:(id*)arg2 ;
+(id)allAppBundleContainersWithError:(id*)arg1 ;
+(id)allVPNPluginBundleContainersWithError:(id*)arg1 ;
+(id)updateSinfDataForAppWithIdentifier:(id)arg1 sinfData:(id)arg2 error:(id*)arg3 ;
+(BOOL)updateiTunesMetadataForAppWithIdentifier:(id)arg1 plistData:(id)arg2 error:(id*)arg3 ;
-(MIExecutableBundle *)bundle;
-(id)initWithContainer:(id)arg1 ;
-(MIBundleMetadata *)bundleMetadata;
-(id)_bundleMetadataURL;
-(void)setBundleMetadata:(MIBundleMetadata *)arg1 ;
-(id)bundleMetadataWithError:(id*)arg1 ;
-(BOOL)makeContainerLiveReplacingContainer:(id)arg1 reason:(unsigned long long)arg2 waitForDeletion:(BOOL)arg3 withError:(id*)arg4 ;
-(BOOL)saveBundleMetadataWithError:(id*)arg1 ;
-(BOOL)captureBundleByMoving:(id)arg1 withError:(id*)arg2 ;
-(unsigned)bundleMaxLinkedSDKVersion;
@end

