/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:42 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/installd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSMutableArray, NSObject;

@interface MISystemAppMigrationState : NSObject {

	BOOL _systemAppMigrationComplete;
	NSMutableArray* _blockArray;
	NSObject*<OS_dispatch_queue> _systemAppMigrationStateQueue;

}

@property (nonatomic,retain) NSMutableArray * blockArray;                                              //@synthesize blockArray=_blockArray - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> systemAppMigrationStateQueue;              //@synthesize systemAppMigrationStateQueue=_systemAppMigrationStateQueue - In the implementation block
@property (assign,nonatomic) BOOL systemAppMigrationComplete;                                          //@synthesize systemAppMigrationComplete=_systemAppMigrationComplete - In the implementation block
+(id)defaultManager;
-(id)init;
-(void)setSystemAppMigrationComplete:(BOOL)arg1 ;
-(void)waitForSystemAppMigrationToComplete:(/*^block*/id)arg1 ;
-(BOOL)systemAppMigrationComplete;
-(NSObject*<OS_dispatch_queue>)systemAppMigrationStateQueue;
-(NSMutableArray *)blockArray;
-(void)setBlockArray:(NSMutableArray *)arg1 ;
@end

