/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 12:58:56 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVGameCenterUIService.app/TVGameCenterUIService
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TVGameCenterUIService/TVGameCenterUIService-Structs.h>
#import <TVGameCenterUIService/GKDaemonProxyDataUpdateDelegate.h>
#import <UIKit/UIApplicationDelegate.h>

@class UIWindow, NSString;

@interface AppDelegateService : NSObject <GKDaemonProxyDataUpdateDelegate, UIApplicationDelegate>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) UIWindow * window; 
-(id)init;
-(BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2 ;
-(void)setLocalPlayer:(id)arg1 ;
-(void)refreshContentsForDataType:(unsigned)arg1 userInfo:(id)arg2 ;
@end

