/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:54:30 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/PineBoard.app/PineBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class PBPIPContainerViewControllerLayout, NSDictionary;

@interface _PBPIPPresentationRequest : NSObject {

	PBPIPContainerViewControllerLayout* _layout;
	NSDictionary* _userInfo;

}

@property (nonatomic,retain) PBPIPContainerViewControllerLayout * layout;              //@synthesize layout=_layout - In the implementation block
@property (nonatomic,retain) NSDictionary * userInfo;                                  //@synthesize userInfo=_userInfo - In the implementation block
-(NSDictionary *)userInfo;
-(void)setUserInfo:(NSDictionary *)arg1 ;
-(PBPIPContainerViewControllerLayout *)layout;
-(void)setLayout:(PBPIPContainerViewControllerLayout *)arg1 ;
-(id)initWithLayout:(id)arg1 userInfo:(id)arg2 ;
@end

