/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:54:28 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/PineBoard.app/PineBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PineBoard/TVSSerialTransactionManagerPolicy.h>

@class NSString;

@interface _PBSerialTransactionManagerPolicyForegroundOpenApp : NSObject <TVSSerialTransactionManagerPolicy>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)resultingQueueAfterAddingTransaction:(id)arg1 inCurrentQueue:(id)arg2 ;
-(long long)actionOnRunningTransaction:(id)arg1 afterAddingTransaction:(id)arg2 ;
@end

