/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:54:27 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/PineBoard.app/PineBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PineBoard/PBOpenAppTransitionerObserver.h>
#import <PineBoard/PBPIPRootViewControllerDelegate.h>
#import <PineBoard/PGPictureInPictureControllerDelegate.h>
#import <PineBoard/PBSystemOverlayUIProvider.h>
#import <PineBoard/PBPresentationElementFocusCoordinatorObserver.h>
#import <PineBoard/PBSceneManagerObserver.h>
#import <PineBoard/PBSystemUIManaging.h>

@class TVSStateMachine, PGPictureInPictureController, PBPIPRootViewController, NSHashTable, PBSystemOverlayController, _PBPIPContentPresentingViewController, NSMutableSet, UIApplicationSceneDeactivationAssertion, NSString, PBSPictureInPictureState;

@interface PBPictureInPictureManager : NSObject <PBOpenAppTransitionerObserver, PBPIPRootViewControllerDelegate, PGPictureInPictureControllerDelegate, PBSystemOverlayUIProvider, PBPresentationElementFocusCoordinatorObserver, PBSceneManagerObserver, PBSystemUIManaging> {

	TVSStateMachine* _stateMachine;
	PGPictureInPictureController* _pictureInPictureController;
	PBPIPRootViewController* _pipRootViewController;
	NSHashTable* _observers;
	PBSystemOverlayController* _overlayController;
	_PBPIPContentPresentingViewController* _contentPresentingViewController;
	long long _initialQuadrant;
	NSMutableSet* _activeInterruptions;
	UIApplicationSceneDeactivationAssertion* _pipSceneDeactivationAssertion;

}

@property (nonatomic,readonly) TVSStateMachine * stateMachine;                                                              //@synthesize stateMachine=_stateMachine - In the implementation block
@property (nonatomic,readonly) PGPictureInPictureController * pictureInPictureController;                                   //@synthesize pictureInPictureController=_pictureInPictureController - In the implementation block
@property (setter=setPIPRootViewController:,nonatomic,retain) PBPIPRootViewController * pipRootViewController;              //@synthesize pipRootViewController=_pipRootViewController - In the implementation block
@property (nonatomic,readonly) NSHashTable * observers;                                                                     //@synthesize observers=_observers - In the implementation block
@property (nonatomic,readonly) PBSystemOverlayController * overlayController;                                               //@synthesize overlayController=_overlayController - In the implementation block
@property (nonatomic,retain) _PBPIPContentPresentingViewController * contentPresentingViewController;                       //@synthesize contentPresentingViewController=_contentPresentingViewController - In the implementation block
@property (nonatomic,readonly) long long initialQuadrant;                                                                   //@synthesize initialQuadrant=_initialQuadrant - In the implementation block
@property (nonatomic,readonly) NSMutableSet * activeInterruptions;                                                          //@synthesize activeInterruptions=_activeInterruptions - In the implementation block
@property (nonatomic,retain) UIApplicationSceneDeactivationAssertion * pipSceneDeactivationAssertion;                       //@synthesize pipSceneDeactivationAssertion=_pipSceneDeactivationAssertion - In the implementation block
@property (nonatomic,readonly) NSString * activePictureInPictureApplicationBundleID; 
@property (nonatomic,readonly) PBSPictureInPictureState * currentState; 
@property (getter=isEditing,nonatomic,readonly) BOOL editing; 
@property (assign,getter=isHidden,nonatomic) BOOL hidden; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (getter=isPresenting,nonatomic,readonly) BOOL presenting; 
+(id)sharedInstance;
+(BOOL)isPictureInPictureSupported;
-(id)init;
-(void)dealloc;
-(void)removeObserver:(id)arg1 ;
-(void)addObserver:(id)arg1 ;
-(BOOL)isPresenting;
-(BOOL)isEditing;
-(BOOL)isHidden;
-(PBSPictureInPictureState *)currentState;
-(void)setHidden:(BOOL)arg1 ;
-(NSHashTable *)observers;
-(TVSStateMachine *)stateMachine;
-(void)_present;
-(void)_dismiss;
-(void)setHidden:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)pictureInPictureController:(id)arg1 didCreatePictureInPictureViewController:(id)arg2 ;
-(void)pictureInPictureController:(id)arg1 willDestroyPictureInPictureViewController:(id)arg2 ;
-(BOOL)pictureInPictureController:(id)arg1 shouldCancelPictureInPictureForApplication:(id)arg2 whenStartingPictureInPictureForApplication:(id)arg3 ;
-(BOOL)pictureInPictureController:(id)arg1 shouldDenyNewConnection:(id)arg2 ;
-(PGPictureInPictureController *)pictureInPictureController;
-(id)_createStateMachine;
-(void)fetchCurrentPictureInPictureStateWithReply:(/*^block*/id)arg1 ;
-(void)applyPictureInPictureInsetsValue:(id)arg1 fromSource:(id)arg2 withAnimationSettings:(id)arg3 usingAnimationFence:(id)arg4 ;
-(/*^block*/id)_machineStateChangeHandler;
-(void)prepareUIForSystemOverlayPresentationWithCompletion:(/*^block*/id)arg1 ;
-(PBSystemOverlayController *)overlayController;
-(void)cancelPictureInPictureWithReason:(id)arg1 ;
-(void)sceneManager:(id)arg1 didChangeFocusFromScene:(id)arg2 toScene:(id)arg3 ;
-(void)sceneManager:(id)arg1 defaultKioskScene:(id)arg2 didUpdateAppGridHidden:(BOOL)arg3 ;
-(void)appTransitioner:(id)arg1 willLaunchProcessForAppTransition:(id)arg2 ;
-(PBPIPRootViewController *)pipRootViewController;
-(void)_dismissEditingControlsWithReason:(id)arg1 animationStyle:(long long)arg2 ;
-(void)_setAcceptsEventFocus:(BOOL)arg1 ;
-(void)_notifyObserversPictureInPictureShouldMute:(BOOL)arg1 skippingBundleID:(id)arg2 ;
-(void)_notifyObserversSendPictureInPicturePlaybackCommand:(unsigned long long)arg1 ;
-(void)sendPictureInPicturePlaybackCommand:(unsigned long long)arg1 ;
-(void)_notifyObserversPictureInPictureDidUpdateState;
-(UIApplicationSceneDeactivationAssertion *)pipSceneDeactivationAssertion;
-(void)pictureInPictureInterruptionBegan:(id)arg1 ;
-(void)pictureInPictureInterruptionEnded:(id)arg1 ;
-(void)muteActivePictureInPicture:(BOOL)arg1 sourceBundleID:(id)arg2 ;
-(BOOL)_shouldInterruptForLayoutLevel:(long long)arg1 ;
-(void)rootViewController:(id)arg1 didStopPictureInPictureForApplication:(id)arg2 ;
-(void)rootViewController:(id)arg1 didCancelPictureInPictureForApplication:(id)arg2 ;
-(void)rootViewController:(id)arg1 didUpdatePresentationState:(unsigned long long)arg2 ;
-(void)rootViewController:(id)arg1 didRequestEditingControlsDismissalWithStyle:(long long)arg2 ;
-(void)rootViewController:(id)arg1 didMovePictureInPictureToQuadrant:(long long)arg2 ;
-(void)rootViewControllerDidRequestTogglePlayPause:(id)arg1 ;
-(void)presentationElementFocusCoordinator:(id)arg1 didUpdateToActiveLayoutLevel:(long long)arg2 fromLevel:(long long)arg3 ;
-(NSString *)activePictureInPictureApplicationBundleID;
-(void)presentEditingControlsWithReason:(id)arg1 ;
-(void)dismissEditingControlsWithReason:(id)arg1 ;
-(void)setPIPRootViewController:(id)arg1 ;
-(_PBPIPContentPresentingViewController *)contentPresentingViewController;
-(void)setContentPresentingViewController:(_PBPIPContentPresentingViewController *)arg1 ;
-(long long)initialQuadrant;
-(NSMutableSet *)activeInterruptions;
-(void)setPipSceneDeactivationAssertion:(UIApplicationSceneDeactivationAssertion *)arg1 ;
@end

