/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:54:30 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/PineBoard.app/PineBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol PBPIPContainerViewControllerAnimationDelegate <NSObject>
@required
-(void)containerViewController:(id)arg1 prepareStartAnimationWithInitialLayerFrame:(CGRect)arg2 completionHandler:(/*^block*/id)arg3;
-(void)containerViewController:(id)arg1 performStartAnimationWithAnimationHandler:(/*^block*/id)arg2 completionHandler:(/*^block*/id)arg3;
-(void)containerViewController:(id)arg1 prepareStopAnimationWithCompletionHandler:(/*^block*/id)arg2;
-(void)containerViewController:(id)arg1 performStopAnimationWithFinalLayerFrame:(CGRect)arg2 animationHandler:(/*^block*/id)arg3 completionHandler:(/*^block*/id)arg4;

@end

