/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:54:27 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/PineBoard.app/PineBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PineBoard/PBOpenAppTransitionerObserver.h>
#import <PineBoard/PBSystemOverlayControllerDelegate.h>
#import <PineBoard/PBSystemOverlayUIProvider.h>
#import <PineBoard/PBSystemUIManaging.h>

@class TVSPreferences, NSHashTable, PBSystemOverlayController, PBDialogHiddenAssertion, NSString;

@interface PBScreenSaverManager : NSObject <PBOpenAppTransitionerObserver, PBSystemOverlayControllerDelegate, PBSystemOverlayUIProvider, PBSystemUIManaging> {

	BOOL _holdOffForMusicEnabled;
	double _screenSaverActivationDelayInMinutes;
	TVSPreferences* _screenSaverPrefs;
	NSHashTable* _observers;
	PBSystemOverlayController* _overlayController;
	PBDialogHiddenAssertion* _hideDialogAssertion;

}

@property (assign,nonatomic) double screenSaverActivationDelayInMinutes;                   //@synthesize screenSaverActivationDelayInMinutes=_screenSaverActivationDelayInMinutes - In the implementation block
@property (nonatomic,readonly) TVSPreferences * screenSaverPrefs;                          //@synthesize screenSaverPrefs=_screenSaverPrefs - In the implementation block
@property (nonatomic,readonly) NSHashTable * observers;                                    //@synthesize observers=_observers - In the implementation block
@property (nonatomic,readonly) PBSystemOverlayController * overlayController;              //@synthesize overlayController=_overlayController - In the implementation block
@property (nonatomic,readonly) PBDialogHiddenAssertion * hideDialogAssertion;              //@synthesize hideDialogAssertion=_hideDialogAssertion - In the implementation block
@property (assign,nonatomic) BOOL holdOffForMusicEnabled;                                  //@synthesize holdOffForMusicEnabled=_holdOffForMusicEnabled - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (getter=isPresenting,nonatomic,readonly) BOOL presenting; 
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)removeObserver:(id)arg1 ;
-(void)addObserver:(id)arg1 ;
-(BOOL)isPresenting;
-(NSHashTable *)observers;
-(BOOL)dismissScreenSaver;
-(void)prepareUIForSystemOverlayPresentationWithCompletion:(/*^block*/id)arg1 ;
-(void)overlayController:(id)arg1 willPresentSession:(id)arg2 ;
-(void)overlayController:(id)arg1 didPresentSession:(id)arg2 ;
-(void)overlayController:(id)arg1 willDismissSession:(id)arg2 withContext:(id)arg3 ;
-(void)overlayController:(id)arg1 didDismissSession:(id)arg2 ;
-(PBSystemOverlayController *)overlayController;
-(void)activateScreenSaverFromUserAction:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)_updateActivationDelay;
-(void)_notifyPhotosSourcesDaemon;
-(id)_screenSaverAppBundleID;
-(id)_screenSaverControllerClassNameForAppBundleID:(id)arg1 ;
-(BOOL)holdOffForMusicEnabled;
-(double)screenSaverActivationDelayInMinutes;
-(void)setScreenSaverActivationDelayInMinutes:(double)arg1 ;
-(void)appTransitioner:(id)arg1 willBeginAppTransition:(id)arg2 ;
-(void)fetchInitialPhotoAssets;
-(void)setHoldOffForMusicEnabled:(BOOL)arg1 ;
-(void)_postSystemDidChangeIdleState:(BOOL)arg1 ;
-(TVSPreferences *)screenSaverPrefs;
-(PBDialogHiddenAssertion *)hideDialogAssertion;
@end

