/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:54:29 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/PineBoard.app/PineBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PineBoard/AFContextProvider.h>

@interface PBSiriScreenActionContextProvider : NSObject <AFContextProvider>
+(id)_JSONSerializedSemanticContext:(id)arg1 ;
-(id)init;
-(void)dealloc;
-(id)getCurrentContext;
-(BOOL)allowContextProvider:(id)arg1 ;
-(id)_screenActionInfoForScreenItem:(id)arg1 ;
@end

