/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:54:28 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/PineBoard.app/PineBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class TVSBackgroundTask, PBDialogContext;

@interface PBWhatsNewService : NSObject {

	BOOL _monitoringStarted;
	BOOL _shouldRetryShowingWhatsNew;
	BOOL _presentingWhatsNew;
	TVSBackgroundTask* _whatsNewCheckTask;
	double _checkTimeInterval;
	double _currentCheckTimeInterval;
	int _whatsNewNotifyToken;
	PBDialogContext* _dialogContext;

}

@property (assign,nonatomic) double checkTimeInterval; 
+(id)sharedInstance;
-(void)dealloc;
-(void)noteGoodTimeToShowWhatsNew;
-(void)_presentWhatsNewDialog;
-(double)checkTimeInterval;
-(void)_scheduleWhatsNewCheckTaskWithInterval:(double)arg1 ;
-(BOOL)_isHeadBoardAppFocused;
-(void)startWhatsNewMonitoring;
-(void)setCheckTimeInterval:(double)arg1 ;
@end

