/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:11 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/HeadBoard.app/HeadBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol HBAppGridViewControllerDelegate <NSObject>
@optional
-(void)appGridViewController:(id)arg1 didUpdateFocusInContext:(SCD_Struct_HB7)arg2 withAnimationCoordinator:(id)arg3;
-(void)gridViewController:(id)arg1 itemMovedIntoDock:(id)arg2;
-(void)gridViewController:(id)arg1 itemMovedOutOfDock:(id)arg2 replacedWithItem:(id)arg3;
-(void)gridViewControllerDidEndDecelerating:(id)arg1;
-(void)gridViewControllerDidScrollCloseEnoughToTop:(id)arg1;
-(void)gridViewControllerItemsBecameReady:(id)arg1;
-(void)gridViewControllerEditingStateChanged:(id)arg1;

@end

