/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:10 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/HeadBoard.app/HeadBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <HeadBoard/HeadBoard-Structs.h>
#import <UIKitCore/UIResponder.h>
#import <UIKit/UIApplicationDelegatePrivate.h>
#import <HeadBoard/APSConnectionDelegate.h>
#import <UIKit/UIApplicationDelegate.h>

@class UIWindow, HBWindow, HBMainViewController, APSConnection, NSString;

@interface HBAppDelegate : UIResponder <UIApplicationDelegatePrivate, APSConnectionDelegate, UIApplicationDelegate> {

	HBWindow* _window;
	HBMainViewController* _mainViewController;
	APSConnection* _apsConnection;

}

@property (nonatomic,retain) APSConnection * apsConnection;                                 //@synthesize apsConnection=_apsConnection - In the implementation block
@property (nonatomic,retain) HBWindow * window;                                             //@synthesize window=_window - In the implementation block
@property (assign,nonatomic,__weak) HBMainViewController * mainViewController;              //@synthesize mainViewController=_mainViewController - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedApplicationDelegate;
+(BOOL)isiCloudHomeScreenSyncEnabled;
-(HBWindow *)window;
-(APSConnection *)apsConnection;
-(void)setApsConnection:(APSConnection *)arg1 ;
-(void)connection:(id)arg1 didReceivePublicToken:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveIncomingMessage:(id)arg2 ;
-(void)connection:(id)arg1 didChangeConnectedStatus:(BOOL)arg2 ;
-(void)connectionDidReconnect:(id)arg1 ;
-(void)connection:(id)arg1 didReceiveToken:(id)arg2 forTopic:(id)arg3 identifier:(id)arg4 ;
-(void)connection:(id)arg1 didReceiveMessageForTopic:(id)arg2 userInfo:(id)arg3 ;
-(void)connection:(id)arg1 didSendOutgoingMessage:(id)arg2 ;
-(void)connection:(id)arg1 didFailToSendOutgoingMessage:(id)arg2 error:(id)arg3 ;
-(void)setWindow:(HBWindow *)arg1 ;
-(BOOL)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2 ;
-(BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2 ;
-(BOOL)application:(id)arg1 openURL:(id)arg2 options:(id)arg3 ;
-(BOOL)application:(id)arg1 runTest:(id)arg2 options:(id)arg3 ;
-(long long)overrideAssetLibraryCacheDeleteUrgency;
-(HBMainViewController *)mainViewController;
-(void)setMainViewController:(HBMainViewController *)arg1 ;
-(BOOL)runTestName:(id)arg1 options:(id)arg2 ;
-(void)_startLogTest:(id)arg1 ;
-(id)_findFirstViewOfClass:(Class)arg1 inViewHierarchy:(id)arg2 ;
-(void)_runSwipeTest:(unsigned long long)arg1 of:(unsigned long long)arg2 testName:(id)arg3 axis:(int)arg4 ;
-(void)_runTopShelfScrollTest:(id)arg1 withDelta:(int)arg2 iterations:(int)arg3 ;
-(void)_runAppGridScrollTest:(id)arg1 withDelta:(int)arg2 iterations:(int)arg3 ;
-(void)_appGridViewController:(id)arg1 randomMoveTestWithItems:(id)arg2 iterations:(unsigned long long)arg3 testName:(id)arg4 ;
-(id)_randomizeArray:(id)arg1 ;
-(id)_findFirstViewOfClass:(Class)arg1 inViewHierarchy:(id)arg2 depth:(int)arg3 ;
-(BOOL)shouldCreateProbesAutomatically;
@end

