/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:09 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/HeadBoard.app/HeadBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol HBCloudSyncOperationDelegate, OS_dispatch_queue;
#import <HeadBoard/HeadBoard-Structs.h>
@class HBCloudSyncDatabaseServices, HBRawFolder, PendingChanges, NSDictionary, NSMutableDictionary, NSObject, NSOperation;

@interface HBCloudSyncDatabaseFacade : NSObject {

	struct {
		unsigned delegateOperationWillBegin : 1;
		unsigned delegateOperationDidFailWithError : 1;
		unsigned delegateOperationDidCompleteSuccessfully : 1;
	}  _flags;
	BOOL _syncStateIsDirtyForDevice;
	id<HBCloudSyncOperationDelegate> _cloudSyncOperationDelegate;
	HBCloudSyncDatabaseServices* _cloudSyncDBServices;
	HBRawFolder* _rootFolder;
	PendingChanges* _pendingChangesToBeProcessed;
	NSDictionary* _syncedItemsToParentMapping;
	NSDictionary* _syncedFolderIdsToDisplayNamesMapping;
	NSMutableDictionary* _appIdentifiersToSyncedAlternateIconNames;
	NSObject*<OS_dispatch_queue> _cloudSyncFacadeSerialQueue;

}

@property (nonatomic,retain) HBCloudSyncDatabaseServices * cloudSyncDBServices;                               //@synthesize cloudSyncDBServices=_cloudSyncDBServices - In the implementation block
@property (nonatomic,retain) HBRawFolder * rootFolder;                                                        //@synthesize rootFolder=_rootFolder - In the implementation block
@property (nonatomic,retain) PendingChanges * pendingChangesToBeProcessed;                                    //@synthesize pendingChangesToBeProcessed=_pendingChangesToBeProcessed - In the implementation block
@property (nonatomic,copy) NSDictionary * syncedItemsToParentMapping;                                         //@synthesize syncedItemsToParentMapping=_syncedItemsToParentMapping - In the implementation block
@property (nonatomic,copy) NSDictionary * syncedFolderIdsToDisplayNamesMapping;                               //@synthesize syncedFolderIdsToDisplayNamesMapping=_syncedFolderIdsToDisplayNamesMapping - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * appIdentifiersToSyncedAlternateIconNames;                  //@synthesize appIdentifiersToSyncedAlternateIconNames=_appIdentifiersToSyncedAlternateIconNames - In the implementation block
@property (assign,nonatomic) BOOL syncStateIsDirtyForDevice;                                                  //@synthesize syncStateIsDirtyForDevice=_syncStateIsDirtyForDevice - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> cloudSyncFacadeSerialQueue;                         //@synthesize cloudSyncFacadeSerialQueue=_cloudSyncFacadeSerialQueue - In the implementation block
@property (nonatomic,readonly) NSOperation * currentOperation; 
@property (assign,nonatomic,__weak) id<HBCloudSyncOperationDelegate> cloudSyncOperationDelegate;              //@synthesize cloudSyncOperationDelegate=_cloudSyncOperationDelegate - In the implementation block
+(void)initialize;
+(id)sharedCloudSyncDatabaseFacade;
-(id)init;
-(void)dealloc;
-(NSOperation *)currentOperation;
-(void)appInstallsBeganPostSync:(id)arg1 ;
-(void)_unarchiveLastKnownCloudSyncedState;
-(NSObject*<OS_dispatch_queue>)cloudSyncFacadeSerialQueue;
-(id)_deserializeRootFolder;
-(void)setRootFolder:(HBRawFolder *)arg1 ;
-(id<HBCloudSyncOperationDelegate>)cloudSyncOperationDelegate;
-(void)_updateLocalDeviceStateWithChangedCloudRecords:(id)arg1 deletedRecordIDs:(id)arg2 shouldPerformMigration:(BOOL)arg3 shouldMergeInPlace:(BOOL)arg4 ;
-(void)_registerForNotificationsToListenForZoneChangesWithCompletion:(/*^block*/id)arg1 ;
-(void)_updateDeviceByFetchingChangesForZoneID:(id)arg1 ;
-(HBRawFolder *)rootFolder;
-(void)_createAndSaveRecordsToCloudWithFolder:(id)arg1 ;
-(void)_syncDeviceChangesToCloud;
-(HBCloudSyncDatabaseServices *)cloudSyncDBServices;
-(void)_saveSubscriptionsPostMigration;
-(void)_fetchOneHomeScreenZoneDeletionStatus:(/*^block*/id)arg1 ;
-(PendingChanges *)pendingChangesToBeProcessed;
-(void)_updateInstallableRecordsList:(id)arg1 fromInstallingProxies:(id)arg2 ;
-(void)_finishAndSaveFolderIfRequired:(id)arg1 operationError:(id)arg2 userInfo:(id)arg3 mergeInPlace:(BOOL)arg4 ;
-(void)setPendingChangesToBeProcessed:(PendingChanges *)arg1 ;
-(NSDictionary *)syncedItemsToParentMapping;
-(NSDictionary *)syncedFolderIdsToDisplayNamesMapping;
-(void)setSyncedItemsToParentMapping:(NSDictionary *)arg1 ;
-(void)setSyncedFolderIdsToDisplayNamesMapping:(NSDictionary *)arg1 ;
-(void)_deleteOldZonesPostMigration;
-(BOOL)syncStateIsDirtyForDevice;
-(BOOL)_doDeviceChangesNeedToBeSyncedToCloudBasedOffCloudRecords:(id)arg1 rootFolder:(id)arg2 ;
-(void)setSyncStateIsDirtyForDevice:(BOOL)arg1 ;
-(NSMutableDictionary *)appIdentifiersToSyncedAlternateIconNames;
-(void)_setAlternateIconNamesForApps:(id)arg1 rootFolder:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)_installableAppRecordsFromNewFolder:(id)arg1 changedRecords:(id)arg2 ;
-(id)_applicationsToBeUninstalledFromDeletedRecordIDs:(id)arg1 oldFolder:(id)arg2 ;
-(id)_validInstallableAppRecordsFromRecords:(id)arg1 ;
-(id)_deletableItemsListWithHashedIdsFromList:(id)arg1 ;
-(void)_generateUUIDForAddedFoldersInList:(id)arg1 ;
-(void)_archiveLastKnownCloudSyncedState;
-(BOOL)_saveFolder:(id)arg1 shouldSendNotification:(BOOL)arg2 mergeInPlace:(BOOL)arg3 ;
-(void)setCloudSyncOperationDelegate:(id<HBCloudSyncOperationDelegate>)arg1 ;
-(void)resetSyncParameters;
-(void)updateDeviceStateFromCloud;
-(void)updateCloudStateFromDevice;
-(void)migrateCloudData;
-(void)beginMigrationCheck;
-(void)syncDeviceFolderStructureToCloud;
-(void)discardOneHomeScreenZone;
-(void)setCloudSyncDBServices:(HBCloudSyncDatabaseServices *)arg1 ;
-(void)setAppIdentifiersToSyncedAlternateIconNames:(NSMutableDictionary *)arg1 ;
-(void)setCloudSyncFacadeSerialQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
@end

