/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:10 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/HeadBoard.app/HeadBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray, NSString;

@interface HBFolderNameInfo : NSObject {

	NSArray* _folderNames;
	NSString* _fallbackFolderName;

}

@property (nonatomic,readonly) NSArray * folderNames;                      //@synthesize folderNames=_folderNames - In the implementation block
@property (nonatomic,readonly) NSString * fallbackFolderName;              //@synthesize fallbackFolderName=_fallbackFolderName - In the implementation block
+(id)localizedDefaultFolderName;
+(id)proposedFolderNameWithTargetFolderNameInfo:(id)arg1 editingFolderNameInfo:(id)arg2 ;
-(id)description;
-(id)initWithBundleIdentifier:(id)arg1 ;
-(id)initWithApplicationProxy:(id)arg1 ;
-(NSArray *)folderNames;
-(NSString *)fallbackFolderName;
@end

