/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:11 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/HeadBoard.app/HeadBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <HeadBoard/HeadBoard-Structs.h>
#import <UIKitCore/UIViewController.h>
#import <HeadBoard/HBAppGridViewControllerDelegate.h>
#import <HeadBoard/HBFolderObserver.h>
#import <HeadBoard/MCProfileConnectionObserver.h>
#import <UIKit/UITextFieldDelegate.h>
#import <HeadBoard/HBRootFolderProvider.h>
#import <HeadBoard/HBUILaunchAnimationEnvironment.h>

@protocol HBRootFolderProvider;
@class HBFolder, HBAppGridViewController, UIView, UITextField, UIFocusGuide, UIPageControl, HBFolderAnimationView, HBApp, _HBFolderClosingView, NSString;

@interface HBFolderViewController : UIViewController <HBAppGridViewControllerDelegate, HBFolderObserver, MCProfileConnectionObserver, UITextFieldDelegate, HBRootFolderProvider, HBUILaunchAnimationEnvironment> {

	BOOL _closing;
	BOOL _resignTransitionToLeft;
	HBFolder* _folder;
	id<HBRootFolderProvider> _rootFolderProvider;
	HBAppGridViewController* _gridViewController;
	UIView* _folderStyleView;
	UIView* _folderContainerView;
	UITextField* _renameFolderTextField;
	UIFocusGuide* _leadingRenameFolderTextFieldFocusGuide;
	UIFocusGuide* _trailingRenameFolderTextFieldFocusGuide;
	UIPageControl* _pageControl;
	UIView* _animationContainerView;
	UIView* _animationBackgroundView;
	HBFolderAnimationView* _animationImageView;
	HBApp* _transitionApp;
	UIView* _transitionView;
	_HBFolderClosingView* _focusSink;

}

@property (nonatomic,retain) HBAppGridViewController * gridViewController;                             //@synthesize gridViewController=_gridViewController - In the implementation block
@property (nonatomic,retain) UIView * folderStyleView;                                                 //@synthesize folderStyleView=_folderStyleView - In the implementation block
@property (nonatomic,retain) UIView * folderContainerView;                                             //@synthesize folderContainerView=_folderContainerView - In the implementation block
@property (nonatomic,readonly) UITextField * renameFolderTextField;                                    //@synthesize renameFolderTextField=_renameFolderTextField - In the implementation block
@property (nonatomic,readonly) UIFocusGuide * leadingRenameFolderTextFieldFocusGuide;                  //@synthesize leadingRenameFolderTextFieldFocusGuide=_leadingRenameFolderTextFieldFocusGuide - In the implementation block
@property (nonatomic,readonly) UIFocusGuide * trailingRenameFolderTextFieldFocusGuide;                 //@synthesize trailingRenameFolderTextFieldFocusGuide=_trailingRenameFolderTextFieldFocusGuide - In the implementation block
@property (nonatomic,readonly) UIPageControl * pageControl;                                            //@synthesize pageControl=_pageControl - In the implementation block
@property (nonatomic,retain) UIView * animationContainerView;                                          //@synthesize animationContainerView=_animationContainerView - In the implementation block
@property (nonatomic,retain) UIView * animationBackgroundView;                                         //@synthesize animationBackgroundView=_animationBackgroundView - In the implementation block
@property (nonatomic,retain) HBFolderAnimationView * animationImageView;                               //@synthesize animationImageView=_animationImageView - In the implementation block
@property (assign,getter=isClosing,nonatomic) BOOL closing;                                            //@synthesize closing=_closing - In the implementation block
@property (nonatomic,retain) HBApp * transitionApp;                                                    //@synthesize transitionApp=_transitionApp - In the implementation block
@property (nonatomic,retain) UIView * transitionView;                                                  //@synthesize transitionView=_transitionView - In the implementation block
@property (assign,getter=isResignTransitionToLeft,nonatomic) BOOL resignTransitionToLeft;              //@synthesize resignTransitionToLeft=_resignTransitionToLeft - In the implementation block
@property (nonatomic,readonly) _HBFolderClosingView * focusSink;                                       //@synthesize focusSink=_focusSink - In the implementation block
@property (nonatomic,retain) HBFolder * folder;                                                        //@synthesize folder=_folder - In the implementation block
@property (assign,nonatomic,__weak) id<HBRootFolderProvider> rootFolderProvider;                       //@synthesize rootFolderProvider=_rootFolderProvider - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) HBFolder * rootFolder; 
-(void)dealloc;
-(id)initWithCoder:(id)arg1 ;
-(void)profileConnectionDidReceiveProfileListChangedNotification:(id)arg1 userInfo:(id)arg2 ;
-(void)_close;
-(HBFolder *)folder;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)setFolder:(HBFolder *)arg1 ;
-(void)textFieldDidEndEditing:(id)arg1 reason:(long long)arg2 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(UIPageControl *)pageControl;
-(void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2 ;
-(BOOL)shouldUpdateFocusInContext:(id)arg1 ;
-(id)preferredFocusEnvironments;
-(BOOL)isClosing;
-(void)setGridViewController:(HBAppGridViewController *)arg1 ;
-(HBAppGridViewController *)gridViewController;
-(id)nextLaunchAnimationEnvironments;
-(UIView *)transitionView;
-(void)itemsDidChange:(id)arg1 ;
-(id)initWithFolder:(id)arg1 ;
-(HBFolder *)rootFolder;
-(void)setResignTransitionToLeft:(BOOL)arg1 ;
-(void)fadeLaunchItemTransitionAnimationCompleteWithApp:(id)arg1 withTransitionView:(id)arg2 ;
-(void)prepareZoomLaunchAnimationWithCellConfiguration:(id)arg1 initialPosition:(CGPoint)arg2 scale:(double)arg3 ;
-(void)applyZoomLaunchAnimationEndPositions;
-(void)zoomLaunchAnimationComplete;
-(void)prepareZoomResignAnimation;
-(void)applyZoomResignAnimationEndPositions:(CGPoint)arg1 ;
-(void)zoomResignAnimationComplete;
-(void)prepareZoomLaunchAnimationWithTransitionApp:(id)arg1 withTransitionView:(id)arg2 cellConfiguration:(id)arg3 initialPosition:(CGPoint)arg4 ;
-(void)applyZoomLaunchItemTransitionAnimationEndPositions;
-(void)zoomLaunchItemTransitionAnimationComplete;
-(void)prepareZoomResignAnimationWithTransitionApp:(id)arg1 transitionView:(id)arg2 resignTransitionToLeft:(BOOL)arg3 ;
-(void)applyZoomResignItemTransitionAnimationEndPositions:(CGPoint)arg1 ;
-(void)zoomResignItemTransitionAnimationComplete:(id)arg1 ;
-(id)_iconImagesForZoomAnimation;
-(UIView *)folderContainerView;
-(void)_prepareZoomLaunchAnimationWithInitialPosition:(CGPoint)arg1 cellConfiguration:(id)arg2 ;
-(UIView *)animationBackgroundView;
-(UIView *)animationContainerView;
-(HBFolderAnimationView *)animationImageView;
-(void)setAnimationImageView:(HBFolderAnimationView *)arg1 ;
-(void)setAnimationBackgroundView:(UIView *)arg1 ;
-(void)setAnimationContainerView:(UIView *)arg1 ;
-(void)_zoomLaunchAnimationComplete;
-(void)setTransitionApp:(HBApp *)arg1 ;
-(void)setTransitionView:(UIView *)arg1 ;
-(HBApp *)transitionApp;
-(void)_prepareZoomResignAnimationWithImages:(id)arg1 ;
-(void)_applyZoomResignAnimationEndPositions:(CGPoint)arg1 endsInFocusedState:(BOOL)arg2 ;
-(id)_iconImagesForZoomAnimationExcludingApps:(id)arg1 ;
-(BOOL)isResignTransitionToLeft;
-(void)setRootFolderProvider:(id<HBRootFolderProvider>)arg1 ;
-(void)_folderCloseAction:(id)arg1 ;
-(void)_updatePageControlPagesCount;
-(id<HBRootFolderProvider>)rootFolderProvider;
-(_HBFolderClosingView *)focusSink;
-(void)setClosing:(BOOL)arg1 ;
-(void)appGridViewController:(id)arg1 didUpdateFocusInContext:(SCD_Struct_HB7)arg2 withAnimationCoordinator:(id)arg3 ;
-(void)gridViewControllerEditingStateChanged:(id)arg1 ;
-(UIView *)folderStyleView;
-(void)setFolderStyleView:(UIView *)arg1 ;
-(void)setFolderContainerView:(UIView *)arg1 ;
-(UITextField *)renameFolderTextField;
-(UIFocusGuide *)leadingRenameFolderTextFieldFocusGuide;
-(UIFocusGuide *)trailingRenameFolderTextFieldFocusGuide;
@end

