/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:11 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/HeadBoard.app/HeadBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIViewController.h>

@class HBTopShelfStaticImageModel, _HBTopShelfStaticMirrorImageView, UIImageView;

@interface HBTopShelfStaticImageModelViewController : UIViewController {

	HBTopShelfStaticImageModel* _model;
	_HBTopShelfStaticMirrorImageView* _backInsetImageView;
	_HBTopShelfStaticMirrorImageView* _frontInsetImageView;
	UIImageView* _fullScreenImageView;

}

@property (nonatomic,readonly) _HBTopShelfStaticMirrorImageView * backInsetImageView;               //@synthesize backInsetImageView=_backInsetImageView - In the implementation block
@property (nonatomic,readonly) _HBTopShelfStaticMirrorImageView * frontInsetImageView;              //@synthesize frontInsetImageView=_frontInsetImageView - In the implementation block
@property (nonatomic,readonly) UIImageView * fullScreenImageView;                                   //@synthesize fullScreenImageView=_fullScreenImageView - In the implementation block
@property (nonatomic,retain) HBTopShelfStaticImageModel * model;                                    //@synthesize model=_model - In the implementation block
-(HBTopShelfStaticImageModel *)model;
-(void)setModel:(HBTopShelfStaticImageModel *)arg1 ;
-(void)viewDidLoad;
-(void)viewDidLayoutSubviews;
-(void)_updateImageViewForModel;
-(_HBTopShelfStaticMirrorImageView *)backInsetImageView;
-(_HBTopShelfStaticMirrorImageView *)frontInsetImageView;
-(UIImageView *)fullScreenImageView;
@end

