//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  9 2019 14:18:44).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaPlayer/MPIdentifierSet.h>

@interface MPIdentifierSet (TVMusic)
- (_Bool)tvm_identifiesSameItemAs:(id)arg1;	// IMP=0x0000000100018c34
- (id)tvm_dictionaryRepresentation;	// IMP=0x0000000100018a00
@end

