/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:43 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <locationd/locationd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <locationd/NSCopying.h>

@interface ALCMElevation : PBCodable <NSCopying> {

	unsigned _elevationAscended;
	unsigned _elevationDescended;
	int _gradeType;
	int _rawGradeType;
	int _source;
	float _verticalSpeed;
	SCD_Struct_AL1 _has;

}

@property (assign,nonatomic) unsigned elevationAscended;               //@synthesize elevationAscended=_elevationAscended - In the implementation block
@property (assign,nonatomic) BOOL hasElevationDescended; 
@property (assign,nonatomic) unsigned elevationDescended;              //@synthesize elevationDescended=_elevationDescended - In the implementation block
@property (assign,nonatomic) BOOL hasGradeType; 
@property (assign,nonatomic) int gradeType;                            //@synthesize gradeType=_gradeType - In the implementation block
@property (assign,nonatomic) BOOL hasVerticalSpeed; 
@property (assign,nonatomic) float verticalSpeed;                      //@synthesize verticalSpeed=_verticalSpeed - In the implementation block
@property (assign,nonatomic) BOOL hasRawGradeType; 
@property (assign,nonatomic) int rawGradeType;                         //@synthesize rawGradeType=_rawGradeType - In the implementation block
@property (assign,nonatomic) BOOL hasSource; 
@property (assign,nonatomic) int source;                               //@synthesize source=_source - In the implementation block
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)description;
-(void)setSource:(int)arg1 ;
-(int)source;
-(id)dictionaryRepresentation;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasSource:(BOOL)arg1 ;
-(BOOL)hasSource;
-(unsigned)elevationAscended;
-(unsigned)elevationDescended;
-(int)gradeType;
-(id)sourceAsString:(int)arg1 ;
-(int)StringAsSource:(id)arg1 ;
-(void)setElevationDescended:(unsigned)arg1 ;
-(void)setHasElevationDescended:(BOOL)arg1 ;
-(BOOL)hasElevationDescended;
-(void)setGradeType:(int)arg1 ;
-(void)setHasGradeType:(BOOL)arg1 ;
-(BOOL)hasGradeType;
-(id)gradeTypeAsString:(int)arg1 ;
-(int)StringAsGradeType:(id)arg1 ;
-(void)setVerticalSpeed:(float)arg1 ;
-(void)setHasVerticalSpeed:(BOOL)arg1 ;
-(BOOL)hasVerticalSpeed;
-(int)rawGradeType;
-(void)setRawGradeType:(int)arg1 ;
-(void)setHasRawGradeType:(BOOL)arg1 ;
-(BOOL)hasRawGradeType;
-(id)rawGradeTypeAsString:(int)arg1 ;
-(int)StringAsRawGradeType:(id)arg1 ;
-(float)verticalSpeed;
-(void)setElevationAscended:(unsigned)arg1 ;
@end

