/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:44 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <LocationSupport/CLIntersiloService.h>
#import <locationd/CLATVAirplayMonitorServiceProtocol.h>
#import <locationd/WPAirPlaySoloDelegate.h>

@class NSMutableSet, WPAirPlaySolo, CLTimer, NSMutableArray, NSString;

@interface CLATVAirplayMonitor : CLIntersiloService <CLATVAirplayMonitorServiceProtocol, WPAirPlaySoloDelegate> {

	BOOL _power;
	NSMutableSet* _clients;
	WPAirPlaySolo* _airplaySolo;
	CLTimer* _scanDeliveryDelayTimer;
	NSMutableArray* _bufferedDevices;

}

@property (nonatomic,retain) NSMutableSet * clients;                        //@synthesize clients=_clients - In the implementation block
@property (nonatomic,retain) WPAirPlaySolo * airplaySolo;                   //@synthesize airplaySolo=_airplaySolo - In the implementation block
@property (assign,nonatomic) BOOL power;                                    //@synthesize power=_power - In the implementation block
@property (nonatomic,retain) CLTimer * scanDeliveryDelayTimer;              //@synthesize scanDeliveryDelayTimer=_scanDeliveryDelayTimer - In the implementation block
@property (nonatomic,retain) NSMutableArray * bufferedDevices;              //@synthesize bufferedDevices=_bufferedDevices - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) BOOL valid; 
+(void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2 ;
+(id)getSilo;
+(void)performSyncOnSilo:(id)arg1 invoker:(/*^block*/id)arg2 ;
-(id)init;
-(void)dealloc;
-(void)setClients:(NSMutableSet *)arg1 ;
-(NSMutableSet *)clients;
-(BOOL)power;
-(void)setPower:(BOOL)arg1 ;
-(void)beginService;
-(void)endService;
-(void)stopScan;
-(void)removeClient:(R)arg1 :(id)arg2 ;
-(void)airPlaySoloDidUpdateState:(id)arg1 ;
-(void)airPlaySolo:(id)arg1 foundDevice:(id)arg2 withData:(id)arg3 ;
-(void)airPlaySoloStartedScanning:(id)arg1 ;
-(void)airPlaySoloStoppedScanning:(id)arg1 ;
-(void)airPlaySolo:(id)arg1 failedToStartScanningWithError:(id)arg2 ;
-(void)startScan;
-(void)getPowerWithCompletion:(/*^block*/id)arg1 ;
-(void)addClient:(R)arg1 :(id)arg2 ;
-(void)withClients:(/*^block*/id)arg1 ;
-(void)beginServiceWithAirPlaySolo:(id)arg1 ;
-(void)setAirplaySolo:(WPAirPlaySolo *)arg1 ;
-(WPAirPlaySolo *)airplaySolo;
-(void)setScanDeliveryDelayTimer:(CLTimer *)arg1 ;
-(void)sendBufferedScanNotifications;
-(CLTimer *)scanDeliveryDelayTimer;
-(void)setBufferedDevices:(NSMutableArray *)arg1 ;
-(void)releaseData;
-(NSMutableArray *)bufferedDevices;
-(void)startMonitoringDevicesForClient:(R)arg1 :(id)arg2 ;
-(void)stopMonitoringDevicesForClient:(R)arg1 :(id)arg2 ;
@end

