/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:47 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <locationd/locationd-Structs.h>
#import <CoreMotion/CLNotifierServiceAdapter.h>
#import <locationd/CLBeaconFenceAuthorizationManagerProtocol.h>

@class NSString;

@interface CLBeaconFenceAuthorizationManagerAdapter : CLNotifierServiceAdapter <CLBeaconFenceAuthorizationManagerProtocol>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) BOOL valid; 
+(void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2 ;
+(id)getSilo;
+(void)performSyncOnSilo:(id)arg1 invoker:(/*^block*/id)arg2 ;
-(id)init;
-(void)beginService;
-(void)endService;
-(void)doAsync:(/*^block*/id)arg1 ;
-(void)doAsync:(/*^block*/id)arg1 withReply:(/*^block*/id)arg2 ;
-(BOOL)syncgetDoSync:(/*^block*/id)arg1 ;
-(CLBeaconFenceAuthorizationManager*)adaptee;
-(BOOL)syncgetAddFence:(const MonitoredRegion*)arg1 ;
-(BOOL)syncgetRemoveFence:(const MonitoredRegion*)arg1 ;
-(BOOL)syncgetFences:(list<CLBTLEBeaconRegion_Type::MonitoredRegion, std::__1::allocator<CLBTLEBeaconRegion_Type::MonitoredRegion> >*)arg1 forBundle:(id)arg2 ;
-(BOOL)syncgetFences:(list<CLBTLEBeaconRegion_Type::MonitoredRegion, std::__1::allocator<CLBTLEBeaconRegion_Type::MonitoredRegion> >*)arg1 forBundle:(id)arg2 onBehalfOf:(id)arg3 ;
-(int)syncgetCanBundle:(id)arg1 performFenceOperationFor:(id)arg2 ;
@end

