/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:43 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <locationd/locationd-Structs.h>
@class NSMutableDictionary;

@interface CLFallModelSelector : NSObject {

	NSMutableDictionary* fSelectionFeatures;
	FallModel fTripFallModel;
	FallModel fSlipFallModel;
	FallModel fOtherFallModel;
	FallThresholds fThresholds;

}
-(id)init;
-(void)dealloc;
-(BOOL)setSelectionFeatureValue:(id)arg1 value:(id)arg2 ;
-(BOOL)selectModels;
-(BOOL)fillTripFallModel:(FallModel*)arg1 ;
-(BOOL)fillSlipFallModel:(FallModel*)arg1 ;
-(BOOL)fillOtherFallModel:(FallModel*)arg1 ;
-(BOOL)fillFallThresholds:(FallThresholds*)arg1 ;
@end

