/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:47 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <locationd/locationd-Structs.h>
#import <locationd/NSSecureCoding.h>

@class NSString, CLPAccessoryMeta;

@interface CLHarvestDataTracks : NSObject <NSSecureCoding> {

	BOOL _motionVehicleConnectedStateChanged;
	BOOL _motionVehicleConnected;
	int _rat;
	int _mcc;
	int _mnc;
	int _context;
	int _modeIndicator;
	double _tripTimestamp;
	NSString* _tripId;
	NSString* _bundleId;
	NSString* _bundleIds;
	CLPAccessoryMeta* _activeAccessory;
	CLMotionActivity _rawMotionActivity;
	CLMotionActivity _motionActivity;
	CLMotionActivity _dominantMotionActivity;
	CLDaemonLocation _location;

}

@property (assign,nonatomic) CLDaemonLocation location;                            //@synthesize location=_location - In the implementation block
@property (assign,nonatomic) double tripTimestamp;                                 //@synthesize tripTimestamp=_tripTimestamp - In the implementation block
@property (nonatomic,copy) NSString * tripId;                                      //@synthesize tripId=_tripId - In the implementation block
@property (assign,nonatomic) int rat;                                              //@synthesize rat=_rat - In the implementation block
@property (assign,nonatomic) int mcc;                                              //@synthesize mcc=_mcc - In the implementation block
@property (assign,nonatomic) int mnc;                                              //@synthesize mnc=_mnc - In the implementation block
@property (assign,nonatomic) int context;                                          //@synthesize context=_context - In the implementation block
@property (nonatomic,copy) NSString * bundleId;                                    //@synthesize bundleId=_bundleId - In the implementation block
@property (nonatomic,copy) NSString * bundleIds;                                   //@synthesize bundleIds=_bundleIds - In the implementation block
@property (assign,nonatomic) int modeIndicator;                                    //@synthesize modeIndicator=_modeIndicator - In the implementation block
@property (nonatomic,retain) CLPAccessoryMeta * activeAccessory;                   //@synthesize activeAccessory=_activeAccessory - In the implementation block
@property (assign,nonatomic) BOOL motionVehicleConnectedStateChanged;              //@synthesize motionVehicleConnectedStateChanged=_motionVehicleConnectedStateChanged - In the implementation block
@property (assign,nonatomic) BOOL motionVehicleConnected;                          //@synthesize motionVehicleConnected=_motionVehicleConnected - In the implementation block
@property (assign,nonatomic) CLMotionActivity rawMotionActivity;                   //@synthesize rawMotionActivity=_rawMotionActivity - In the implementation block
@property (assign,nonatomic) CLMotionActivity motionActivity;                      //@synthesize motionActivity=_motionActivity - In the implementation block
@property (assign,nonatomic) CLMotionActivity dominantMotionActivity;              //@synthesize dominantMotionActivity=_dominantMotionActivity - In the implementation block
+(BOOL)supportsSecureCoding;
-(id)description;
-(void)dealloc;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setBundleId:(NSString *)arg1 ;
-(int)context;
-(void)setContext:(int)arg1 ;
-(NSString *)bundleId;
-(int)rat;
-(void)setRat:(int)arg1 ;
-(CLDaemonLocation)location;
-(void)setLocation:(CLDaemonLocation)arg1 ;
-(int)mcc;
-(void)setMcc:(int)arg1 ;
-(int)mnc;
-(void)setMnc:(int)arg1 ;
-(NSString *)bundleIds;
-(void)setBundleIds:(NSString *)arg1 ;
-(void)setMotionActivity:(CLMotionActivity)arg1 ;
-(CLMotionActivity)motionActivity;
-(void)setRawMotionActivity:(CLMotionActivity)arg1 ;
-(void)setDominantMotionActivity:(CLMotionActivity)arg1 ;
-(void)setMotionVehicleConnectedStateChanged:(BOOL)arg1 ;
-(void)setMotionVehicleConnected:(BOOL)arg1 ;
-(int)modeIndicator;
-(void)setModeIndicator:(int)arg1 ;
-(BOOL)motionVehicleConnectedStateChanged;
-(BOOL)motionVehicleConnected;
-(CLMotionActivity)rawMotionActivity;
-(CLMotionActivity)dominantMotionActivity;
-(void)setTripId:(NSString *)arg1 ;
-(NSString *)tripId;
-(id)jsonObject;
-(void)setTripTimestamp:(double)arg1 ;
-(void)setActiveAccessory:(CLPAccessoryMeta *)arg1 ;
-(double)tripTimestamp;
-(CLPAccessoryMeta *)activeAccessory;
-(id)initWithTracksData:(HarvestData)arg1 andLocation:(CLDaemonLocation)arg2 ;
@end

