/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:44 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CLMotionStateMediatorProtocol <CLNotifierServiceProtocol>
@required
-(void)doAsync:(/*^block*/id)arg1;
-(void)doAsync:(/*^block*/id)arg1 withReply:(/*^block*/id)arg2;
-(BOOL)syncgetDoSync:(/*^block*/id)arg1;
-(void)userDismissedWorkoutAlert;
-(void)setWorkoutSuggestedStopTimeout:(double)arg1;
-(/*^block*/id)syncgetActivityOverride;
-(void)addClient:(byref id)arg1 prepareSessionEndForSessionType:(long long)arg2;
-(void)removeClient:(byref id)arg1 prepareSessionEndForSessionType:(long long)arg2;

@end

