/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:45 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <locationd/locationd-Structs.h>
#import <CoreMotion/CLNotifierServiceAdapter.h>
#import <locationd/CLMotionAlarmNotifierProtocol.h>

@class NSString;

@interface CLMotionAlarmNotifierAdapter : CLNotifierServiceAdapter <CLMotionAlarmNotifierProtocol>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) BOOL valid; 
+(void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2 ;
+(id)getSilo;
+(void)performSyncOnSilo:(id)arg1 invoker:(/*^block*/id)arg2 ;
-(id)init;
-(void)beginService;
-(void)endService;
-(void)doAsync:(/*^block*/id)arg1 ;
-(void)doAsync:(/*^block*/id)arg1 withReply:(/*^block*/id)arg2 ;
-(BOOL)syncgetDoSync:(/*^block*/id)arg1 ;
-(CLMotionAlarmNotifier*)adaptee;
-(void)unregisterClient:(/*^block*/id)arg1 ;
-(void)registerClient:(/*^block*/id)arg1 adapter:(R)arg2 :(id)arg3 ;
-(void)registerAlarm:(id)arg1 withReply:(/*^block*/id)arg2 ;
-(void)unregisterAlarm:(id)arg1 withReply:(/*^block*/id)arg2 ;
-(void)acknowledgeAlarm:(id)arg1 withReply:(/*^block*/id)arg2 ;
-(void)launchRemoteApplication:(id)arg1 withReply:(/*^block*/id)arg2 ;
-(void)launchWatchApplicationForCompanion:(id)arg1 ;
@end

