/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:46 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CLOdometerAlarmManagerProtocol;
@interface CLOdometerAlarm : NSObject {

	BOOL invalid;
	double odometerTarget;
	/*^block*/id handler;
	id<CLOdometerAlarmManagerProtocol> _manager;

}

@property (assign,nonatomic) double odometerTarget; 
@property (nonatomic,copy) id handler; 
@property (assign,nonatomic) BOOL invalid; 
@property (nonatomic,retain) id<CLOdometerAlarmManagerProtocol> manager;              //@synthesize manager=_manager - In the implementation block
-(id)init;
-(void)dealloc;
-(void)invalidate;
-(id)handler;
-(BOOL)invalid;
-(void)setHandler:(id)arg1 ;
-(id<CLOdometerAlarmManagerProtocol>)manager;
-(void)setManager:(id<CLOdometerAlarmManagerProtocol>)arg1 ;
-(void)setInvalid:(BOOL)arg1 ;
-(void)setOdometerTarget:(double)arg1 ;
-(double)odometerTarget;
-(void)fire:(double)arg1 withError:(id)arg2 ;
-(id)initWithDistance:(double)arg1 inUniverse:(id)arg2 handler:(/*^block*/id)arg3 ;
@end

