/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:45 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <locationd/locationd-Structs.h>
@class PCPersistentTimer, CLSilo, NSString;

@interface CLPersistentTimerInternal : NSObject {

	PCPersistentTimer* _pcTimer;
	CLPersistentTimer* _clTimer;
	CLSilo* _silo;
	basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > _strIdentifier;
	NSString* _serviceIdentifier;
	BOOL _wakeDevice;
	double _timeInterval;
	double _minimumEarlyFireProportion;

}
-(void)dealloc;
-(void)invalidate;
-(void)timerFired:(id)arg1 ;
-(void)setNextFireTime:(double)arg1 ;
-(void)setTimerWithInterval:(double)arg1 ;
-(void)bounce_timerFired:(id)arg1 ;
-(id)initWithFireTime:(double)arg1 timeInterval:(double)arg2 serviceIdentifier:(const char*)arg3 wakeDevice:(BOOL)arg4 clTimer:(CLPersistentTimer*)arg5 silo:(id)arg6 minimumEarlyFireProportion:(double)arg7 ;
@end

