/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:46 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface CLWeatherServiceData : NSObject {

	float _weatherPressure;
	double _timestamp;

}

@property (assign,nonatomic) double timestamp;                   //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) float weatherPressure;              //@synthesize weatherPressure=_weatherPressure - In the implementation block
-(double)timestamp;
-(void)setTimestamp:(double)arg1 ;
-(float)weatherPressure;
-(void)setWeatherPressure:(float)arg1 ;
@end

