#import <locationd/CLTileSyncSyChange.h>
#import <locationd/CLTileSyncSySerializer.h>
#import <locationd/CLTileSyncDelegate.h>
#import <locationd/ALCMElevation.h>
#import <locationd/CLHealthAssessmentNotifierAdapter.h>
#import <locationd/CLStreamedLocationProviderAdapter.h>
#import <locationd/CLStreamedLocationProviderAssertion.h>
#import <locationd/CLStreamedLocationProviderDisablementAssertion.h>
#import <locationd/CLStreamedLocationProviderEmergencyEnablementAssertion.h>
#import <locationd/ALMotionState.h>
#import <locationd/ALCMMotionContextMotionState.h>
#import <locationd/CLCertificatePinningHelper.h>
#import <locationd/ALCLStrideCalEntry.h>
#import <locationd/ALCLStepCountEntry.h>
#import <locationd/ALCLSedentaryAlarmData.h>
#import <locationd/ALCLNatalieFeatures.h>
#import <locationd/ALCLBodyMetrics.h>
#import <locationd/ALCLMotionActivity.h>
#import <locationd/ALActivityOverrideMsg.h>
#import <locationd/ALActivityLog.h>
#import <locationd/CLActivityLoggerAdapter.h>
#import <locationd/CLHarvesterService.h>
#import <locationd/CLOdometerNotifierAdapter.h>
#import <locationd/TRANSITPbRegionPreloadTile.h>
#import <locationd/CMStrideCalibrationStepCountBuffer.h>
#import <locationd/CLHarvestAccessoryLocationProviderAdapter.h>
#import <locationd/CLFileDownloadTaskDelegate.h>
#import <locationd/CLFallHealthKitManager.h>
#import <locationd/CLSedentaryTimerNotifierAdapter.h>
#import <locationd/CLFallModelSelector.h>
#import <locationd/ALCLJacksonData.h>
#import <locationd/TRANSITPbTransitTile.h>
#import <locationd/CLMescalSigner.h>
#import <locationd/CLDuetForegroundApp.h>
#import <locationd/CLDuetHomeKitScene.h>
#import <locationd/CLDuetHomeKitAccessory.h>
#import <locationd/CLDuetHomeKitAppView.h>
#import <locationd/CLDuetNowPlaying.h>
#import <locationd/CLKeychainItemWrapper.h>
#import <locationd/CLLocationStreamingMessage.h>
#import <locationd/CLLocationStreamingConnectionManager.h>
#import <locationd/CLHomeKitProviderAdapter.h>
#import <locationd/CLHomeKitDelegate.h>
#import <locationd/CLTelephonyServiceAdapter.h>
#import <locationd/CLWifiServiceAdapter.h>
#import <locationd/ALCLStrideCalEntryDeprecated.h>
#import <locationd/CLMotionStateRoutineAdapter.h>
#import <locationd/CLMotionStateAdapter.h>
#import <locationd/CLGyroCalibrationDatabaseLocationdAdapter.h>
#import <locationd/CLDaemonSettingsManager.h>
#import <locationd/CLLocationDerivedSpeedEstimator.h>
#import <locationd/CLCompanionNotifierAdapter.h>
#import <locationd/CLDaemonStatusStateTracker.h>
#import <locationd/CLDaemonStatusInternal.h>
#import <locationd/CLDaemonStatusAdapter.h>
#import <locationd/CLHarvestDataMotionActivity.h>
#import <locationd/CLHarvestDataAccessPoint.h>
#import <locationd/CLAccessoryObserverHelper.h>
#import <locationd/ALSLocationDelegate.h>
#import <locationd/CLBarometerCalibrationSource.h>
#import <locationd/CLTimeManagerAdapter.h>
#import <locationd/CLLocationControllerAdapter.h>
#import <locationd/CLWifiLocationProviderAdapter.h>
#import <locationd/CLMotionStateMediatorAdapter.h>
#import <locationd/CLClientNotificationHelper.h>
#import <locationd/CLNetworkLocationProviderAdapter.h>
#import <locationd/CLAccessoryLocationProviderAdapter.h>
#import <locationd/CLDaemonStatsFetchLocationSystemStateAdapter.h>
#import <locationd/CLFilteredLocationControllerAdapter.h>
#import <locationd/CLSensorMonitor.h>
#import <locationd/CLRouteListener.h>
#import <locationd/TRANSITPbRegionPreloadManifest.h>
#import <locationd/ALCLSessionCatherine.h>
#import <locationd/ALCMCalorieData.h>
#import <locationd/CLClientManagerStateTracker.h>
#import <locationd/CLClientManagerAdapter.h>
#import <locationd/CLSignificantVisitManager.h>
#import <locationd/CLCarrierSettingsAdapter.h>
#import <locationd/TRANSITPbLocationFingerprints.h>
#import <locationd/CLWatchOrientationSettingsNotifierAdapter.h>
#import <locationd/CLDiagnosticManager.h>
#import <locationd/CLLocationCorrectiveCompensator.h>
#import <locationd/TRANSITPbRegionPreloadMarket.h>
#import <locationd/CLLocationStreamer.h>
#import <locationd/CLCachedLocationControllerAdapter.h>
#import <locationd/CLTileDownloadSchedulingService.h>
#import <locationd/CLGeoAccessMapGeometryGeoRestrictionsAllowNetworkLoad.h>
#import <locationd/CMStrideCalDataContainer.h>
#import <locationd/CLATVAirplayDevice.h>
#import <locationd/CLATVAirplayMonitor.h>
#import <locationd/CMStrideCalibrator.h>
#import <locationd/CLFitnessTrackingNotifierAdapter.h>
#import <locationd/CLClientManagerUsageSyncMessage.h>
#import <locationd/CLClientManagerUsageSyncMessageError.h>
#import <locationd/CLUsageSyncManager.h>
#import <locationd/CLHealthAssessmentResult.h>
#import <locationd/TRANSITPbTransitMacTile.h>
#import <locationd/CLTimeZoneManagerAdapter.h>
#import <locationd/CLFenceManagerAdapter.h>
#import <locationd/CLMotionAlarmSubscriptionAdapter.h>
#import <locationd/CLAuthSyncVectorClock.h>
#import <locationd/ALCMCoarseElevation.h>
#import <locationd/CLTransitMacTileDataProvider.h>
#import <locationd/CLTransitMacTileDataProviderResult.h>
#import <locationd/ALCLStairClimbingModel.h>
#import <locationd/CLHealthAssessmentChoreaDetectionService.h>
#import <locationd/CMStrideCalibrationStats.h>
#import <locationd/CLPersistentTimerInternal.h>
#import <locationd/ALCLAllDayHeartRate.h>
#import <locationd/ClientRegistration.h>
#import <locationd/CLMotionAlarmNotifierAdapter.h>
#import <locationd/ALCLRowingModel.h>
#import <locationd/CLSimulatedLocationProviderAdapter.h>
#import <locationd/CLCompanionActivityAWDAggregator.h>
#import <locationd/CLAuthSyncManager.h>
#import <locationd/CLCatherineNotifierAdapter.h>
#import <locationd/CLFallNotifierClientAdapter.h>
#import <locationd/CLFallNotifierAdapter.h>
#import <locationd/CLFallNotifierSysdiagnoseLogCollector.h>
#import <locationd/ALCLIDSStatus.h>
#import <locationd/CLCompassDatabaseLocationdAdapter.h>
#import <locationd/CMStrideCalibrationActivityBuffer.h>
#import <locationd/CLDuetRegistration.h>
#import <locationd/CLDuetMonitorRegistrationId.h>
#import <locationd/CLDuetMonitor.h>
#import <locationd/CLDuetPredicates.h>
#import <locationd/CLBarometerCalibration.h>
#import <locationd/CLSuggestedActionManagerAppRecommendationResult.h>
#import <locationd/CLSuggestedActionManager.h>
#import <locationd/CLAvailabilityRegionChangeMonitor.h>
#import <locationd/CLCompanionTransport.h>
#import <locationd/ALCMCalorieDataDeprecated.h>
#import <locationd/TRANSITPbLocationFingerprint.h>
#import <locationd/CLBundleLocationProviderContext.h>
#import <locationd/CLMotionLoggerAdapter.h>
#import <locationd/CLNewAppDiscovery.h>
#import <locationd/CLSimulationControllerAdapter.h>
#import <locationd/CLStepDistanceEstimator.h>
#import <locationd/CLBluetoothServiceAdapter.h>
#import <locationd/CLSubHarvesterAvengerExternalAdapter.h>
#import <locationd/CLOnBodyNotifierAdapter.h>
#import <locationd/CMPedometerTable.h>
#import <locationd/CLPlaceInferenceSubscriptionAdapter.h>
#import <locationd/CLCompanionSyncAuthObject.h>
#import <locationd/CLPressureCalibrationDatabaseAdapter.h>
#import <locationd/CLCapabilityMonitor.h>
#import <locationd/ALCLElevationDeprecated.h>
#import <locationd/CLSignificantChangeManagerAdapter.h>
#import <locationd/CLApplicationLifecycleManagerAdapter.h>
#import <locationd/CLCoarseCellTilesManagerAdapter.h>
#import <locationd/CMStrideCalLocationFSM.h>
#import <locationd/SYService.h>
#import <locationd/SYSession.h>
#import <locationd/SYDictionaryObject.h>
#import <locationd/CMStrideCalibrationDatabase.h>
#import <locationd/CLFallMslSink.h>
#import <locationd/CLUsageReportCoordinate.h>
#import <locationd/CLInterval.h>
#import <locationd/CLRoutineMonitor.h>
#import <locationd/CLFenceMonitorAdapter.h>
#import <locationd/CLGeomagneticModelProviderLocationdAdapter.h>
#import <locationd/TRANSITPbTransitMac.h>
#import <locationd/CLSignalEnvironmentProviderAdapter.h>
#import <locationd/CLWeatherServiceData.h>
#import <locationd/CLWeatherService.h>
#import <locationd/CLRemoteMotionAlarm.h>
#import <locationd/CLUnifiedCellLocationProviderAdapter.h>
#import <locationd/CLRunningAggregatorAWD.h>
#import <locationd/CLSkiNotifierAdapter.h>
#import <locationd/CLPolygonSimplifier.h>
#import <locationd/CLGnssProviderAdapter.h>
#import <locationd/CLDataProtectionManagerAdapter.h>
#import <locationd/CLStatusBarIconManagerAdapter.h>
#import <locationd/CLDaemonInUseAssertionAdapter.h>
#import <locationd/CLStreamingAwareLocationProviderAdapter.h>
#import <locationd/CLStepCountSubscriptionAdapter.h>
#import <locationd/CLAvengerScanner.h>
#import <locationd/ALSCdmaCellTower.h>
#import <locationd/ALCLSedentaryAlarmDataDeprecated.h>
#import <locationd/ALSCdmaEvdoTower.h>
#import <locationd/CLSensorCalibrationControllerAdapter.h>
#import <locationd/ALSCellTower.h>
#import <locationd/ALSLocation.h>
#import <locationd/ALSLocationRequest.h>
#import <locationd/ALSLocationResponse.h>
#import <locationd/ALSLteCellTower.h>
#import <locationd/ALSNearbyRequest.h>
#import <locationd/CLBarometerCalibrationTrack.h>
#import <locationd/CLBarometerCalibrationContextManager.h>
#import <locationd/CLMicroLocationNotifierAdapter.h>
#import <locationd/CLMicroLocationIntersiloDelegate.h>
#import <locationd/ALSNearbyResponse.h>
#import <locationd/CLBarometerCalibrationAdapter.h>
#import <locationd/ALSWirelessAP.h>
#import <locationd/CLALSRequester.h>
#import <locationd/TRANSITPbLocationFingerprintV1.h>
#import <locationd/CLEmergencyControllerAdapter.h>
#import <locationd/CLAutopauseProviderAdapter.h>
#import <locationd/CLPeerRangingNotifierAdapter.h>
#import <locationd/CLTilesManagerAdapter.h>
#import <locationd/CLContextManagerSignificantLocationVisit.h>
#import <locationd/CLStreamedLocationInternal.h>
#import <locationd/CMPedometerTableRawSpeedToKValue.h>
#import <locationd/ALCMCoarseElevationDeprecated.h>
#import <locationd/CLOdometerAlarm.h>
#import <locationd/CLPressureBiasAdapter.h>
#import <locationd/CLOdometerAlarmManager.h>
#import <locationd/ALCMWorkoutEventDeprecated.h>
#import <locationd/CalibrationTrack.h>
#import <locationd/CMGpsOdometerEntry.h>
#import <locationd/CMPedometerEntry.h>
#import <locationd/CalTrackFinder.h>
#import <locationd/ALCLNatalieDataDeprecated.h>
#import <locationd/CLDaemonHealthClientAdapter.h>
#import <locationd/CLBarometerCalibrationSourceAggregator.h>
#import <locationd/CLStreamedLocationPrivate.h>
#import <locationd/CLDaemonClientAdapter.h>
#import <locationd/CLDigitalElevationModelAdapter.h>
#import <locationd/CLVehicleConnectionNotifierAdapter.h>
#import <locationd/CLMotionSyncStoreAdapter.h>
#import <locationd/CLLocationAwarenessProviderAdapter.h>
#import <locationd/CLFitnessMachineNotifierAdapter.h>
#import <locationd/CLAppMonitorAdapter.h>
#import <locationd/TRANSITPbLocationFingerprintsV1.h>
#import <locationd/CLMotionStateObserverAdapter.h>
#import <locationd/CLLocationSubscriptionStatusBarAssertion.h>
#import <locationd/CLLocationSubscriptionAdapter.h>
#import <locationd/CLPushServiceState.h>
#import <locationd/CLCellTilesManagerAdapter.h>
#import <locationd/CLFallLoggerManager.h>
#import <locationd/CLSensorRecorderSensorMetaSerializer.h>
#import <locationd/CLWifiTilesManagerAdapter.h>
#import <locationd/CLNatalimetryNotifierAdapter.h>
#import <locationd/CLCallbackDropNullDelegate.h>
#import <locationd/CLHRequestArchive.h>
#import <locationd/CLHLocationAwareRequestArchive.h>
#import <locationd/CLHRequestStore.h>
#import <locationd/CLAppTileDataProvider.h>
#import <locationd/CLAppTileDataProviderResult.h>
#import <locationd/CLAppTileDataProviderRequest.h>
#import <locationd/ALCMExerciseMinute.h>
#import <locationd/CLSensorRecorderNotifierAdapter.h>
#import <locationd/CLSensorRecorderAlmanacListener.h>
#import <locationd/CLBTLEBeaconProviderMockAdapter.h>
#import <locationd/CMStrideCalibrationElevationBuffer.h>
#import <locationd/CLHarvestDataTracks.h>
#import <locationd/CLBTLEFenceManagerAdapter.h>
#import <locationd/CLSpringTrackingNotifierAdapter.h>
#import <locationd/CLPeripheralManagerDelegate.h>
#import <locationd/CLHUploadRequest.h>
#import <locationd/CLHNetworkController.h>
#import <locationd/CLWPZone.h>
#import <locationd/CLWPBridge.h>
#import <locationd/CLGpsAssistantAdapter.h>
#import <locationd/CLBarometerCalibrationSourceWifi.h>
#import <locationd/TRANSITPbMacModePair.h>
#import <locationd/CMActivityAlarmLocal.h>
#import <locationd/CLBTLEBeaconProviderAdapter.h>
#import <locationd/CLDarwinNotifierAdapter.h>
#import <locationd/CLFallLogger.h>
#import <locationd/CLBeaconFenceAuthorizationManagerAdapter.h>
#import <locationd/ALSScdmaCellTower.h>
#import <locationd/CLBTLERangeManagerAdapter.h>
#import <locationd/CMPedometerTableStepCadenceToStrideLength.h>
#import <locationd/CLTransitMacMonitorAccessPoint.h>
#import <locationd/CLTransitMacMonitor.h>
#import <locationd/CLTurnStateAdapter.h>
#import <locationd/CLTileDownloadSchedulingClient.h>
#import <locationd/CLHarvestRoutineAdapter.h>
#import <locationd/CLHEndpointSelector.h>
#import <locationd/CLWorkoutGeoFenceController.h>
#import <locationd/CLDaemonSpringTrackingClientAdapter.h>
#import <locationd/CLPredictedApplication.h>
#import <locationd/CLHLocationClassifier.h>
#import <locationd/ALCMWorkoutEvent.h>
#import <locationd/CLNotifierClientAdapter.h>
#import <locationd/CLNotifierServiceAdapter.h>
#import <locationd/CLClientManagerAuthorizationContext.h>
#import <locationd/CLClientAuthorizationCache.h>
#import <locationd/CLVisitMonitoringSubscriptionAdapter.h>
#import <locationd/CLFallServer.h>
#import <locationd/CLHealthAssessmentTremorDetectionService.h>
#import <locationd/ALCMFitnessTracking.h>
#import <locationd/CLVehicleStateNotifierRoutineAdapter.h>
#import <locationd/CLVehicleStateNotifierTransitMacMonitorAdapter.h>
#import <locationd/CLVehicleStateNotifierAdapter.h>
#import <locationd/ALCLOdometer.h>
#import <locationd/CLSmootherMonitor.h>
#import <locationd/CLStepCountNotifierAdapter.h>
#import <locationd/CLBarometerCalibrationSourcePressure.h>
#import <locationd/CLSwimNotifierAdapter.h>
#import <locationd/CLSwimNotifierIntersiloDelegate.h>
#import <locationd/CLIntersiloDelegate.h>
#import <locationd/CLInternalService.h>
#import <locationd/CLWorkoutRecording.h>
#import <locationd/CLWorkoutRecorder.h>
#import <locationd/CLPrivacyManager.h>
#import <locationd/CLWorkoutRecorderPublisher.h>
#import <locationd/CLMotionHintLoggerAdapter.h>
