/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:45 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <locationd/locationd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <locationd/NSCopying.h>

@interface TRANSITPbLocationFingerprint : PBCodable <NSCopying> {

	SCD_Struct_TR108* _macs;
	SCD_Struct_TR109* _modes;
	double _latitude;
	unsigned long long _locationId;
	double _longitude;
	SCD_Struct_AL5 _has;

}

@property (assign,nonatomic) BOOL hasLocationId; 
@property (assign,nonatomic) unsigned long long locationId;                //@synthesize locationId=_locationId - In the implementation block
@property (assign,nonatomic) BOOL hasLatitude; 
@property (assign,nonatomic) double latitude;                              //@synthesize latitude=_latitude - In the implementation block
@property (assign,nonatomic) BOOL hasLongitude; 
@property (assign,nonatomic) double longitude;                             //@synthesize longitude=_longitude - In the implementation block
@property (nonatomic,readonly) unsigned long long macsCount; 
@property (nonatomic,readonly) unsigned long long* macs; 
@property (nonatomic,readonly) unsigned long long modesCount; 
@property (nonatomic,readonly) double* modes; 
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)description;
-(void)dealloc;
-(id)dictionaryRepresentation;
-(double*)modes;
-(double)latitude;
-(double)longitude;
-(void)setLongitude:(double)arg1 ;
-(void)setLatitude:(double)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(unsigned long long)macsCount;
-(void)clearMacs;
-(unsigned long long*)macs;
-(void)setMacs:(unsigned long long*)arg1 count:(unsigned long long)arg2 ;
-(void)setHasLatitude:(BOOL)arg1 ;
-(BOOL)hasLatitude;
-(void)setHasLongitude:(BOOL)arg1 ;
-(BOOL)hasLongitude;
-(unsigned long long)locationId;
-(void)setLocationId:(unsigned long long)arg1 ;
-(void)addMacs:(unsigned long long)arg1 ;
-(unsigned long long)macsAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)modesCount;
-(void)clearModes;
-(double)modesAtIndex:(unsigned long long)arg1 ;
-(void)addModes:(double)arg1 ;
-(void)setHasLocationId:(BOOL)arg1 ;
-(BOOL)hasLocationId;
-(void)setModes:(double*)arg1 count:(unsigned long long)arg2 ;
@end

