/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:59:24 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVSettings.app/TVSettings
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TVSettings/CastleRequest.h>

@class NSArray;

@interface QuotaAppDetailsRequest : CastleRequest {

	NSArray* _bundleIds;
	NSArray* _bundleIDs;

}

@property (nonatomic,retain) NSArray * bundleIDs;              //@synthesize bundleIDs=_bundleIDs - In the implementation block
+(Class)responseClass;
-(NSArray *)bundleIDs;
-(void)setBundleIDs:(NSArray *)arg1 ;
-(id)urlRequest;
-(id)initWithAccount:(id)arg1 bundleIDs:(id)arg2 quotaInfo:(id)arg3 ;
@end

