/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:59:24 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVSettings.app/TVSettings
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSOperationQueue, NSObject, QuotaInfoResponse, NSMutableDictionary;

@interface QuotaRequestManager : NSObject {

	NSOperationQueue* _requestQueue;
	NSObject*<OS_dispatch_queue> _quota_info_queue;
	QuotaInfoResponse* _quotaInfo;
	NSMutableDictionary* _appDetailsCache;

}
+(id)sharedManager;
+(id)noAccountError;
-(id)init;
-(void)clearCachedQuotaInfo;
-(id)_sendSynchronousAARequest:(id)arg1 ;
-(id)quotaInfoError:(id*)arg1 ;
-(id)appDetailsForBundleIDs:(id)arg1 error:(id*)arg2 ;
-(void)noteQuotaInfoChanged;
-(void)getQuotaInfoForHandler:(/*^block*/id)arg1 ;
-(void)clearCachedAppDetails;
-(void)getAppDetailsForBundleIDs:(id)arg1 handler:(/*^block*/id)arg2 ;
@end

