/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:59:24 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVSettings.app/TVSettings
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TVSettingKit/TSKViewController.h>

@interface TVSettingsSetupViewController : TSKViewController
-(id)loadSettingGroups;
-(id)_resetViewController;
-(void)_showConfirmReset;
-(void)_showConfirmRestore;
-(void)_handleResetAllSettingsResultWithError:(id)arg1 ;
-(void)_showFailureWithText:(id)arg1 ;
@end

