/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 12:52:40 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVIdleScreen.app/TVIdleScreen
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSMutableDictionary, NSMutableSet, NSCountedSet, NSURL, NSObject;

@interface TVIAssetCache : NSObject {

	unsigned long long _guaranteedAssetLimit;
	NSMutableDictionary* _assetToURLMap;
	NSMutableSet* _internalProtectedAssets;
	NSCountedSet* _protectedAssets;
	NSURL* _protectedDirectory;
	NSURL* _purgeableDirectory;
	NSObject*<OS_dispatch_queue> _workQ;

}

@property (nonatomic,retain) NSMutableDictionary * assetToURLMap;                  //@synthesize assetToURLMap=_assetToURLMap - In the implementation block
@property (nonatomic,retain) NSMutableSet * internalProtectedAssets;               //@synthesize internalProtectedAssets=_internalProtectedAssets - In the implementation block
@property (nonatomic,retain) NSCountedSet * protectedAssets;                       //@synthesize protectedAssets=_protectedAssets - In the implementation block
@property (nonatomic,retain) NSURL * protectedDirectory;                           //@synthesize protectedDirectory=_protectedDirectory - In the implementation block
@property (nonatomic,retain) NSURL * purgeableDirectory;                           //@synthesize purgeableDirectory=_purgeableDirectory - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> workQ;                   //@synthesize workQ=_workQ - In the implementation block
@property (assign,nonatomic) unsigned long long guaranteedAssetLimit;              //@synthesize guaranteedAssetLimit=_guaranteedAssetLimit - In the implementation block
-(unsigned long long)_count;
-(BOOL)containsAsset:(id)arg1 ;
-(void)_initializeCache;
-(NSObject*<OS_dispatch_queue>)workQ;
-(void)setWorkQ:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)initWithDirectory:(id)arg1 guaranteedAssetLimit:(unsigned long long)arg2 ;
-(void)setGuaranteedAssetLimit:(unsigned long long)arg1 ;
-(BOOL)markAsset:(id)arg1 asProtected:(BOOL)arg2 ;
-(id)urlForProtectedAsset:(id)arg1 ;
-(BOOL)removeAssetWithIdentifier:(id)arg1 ;
-(BOOL)addAsset:(id)arg1 atURL:(id)arg2 extension:(id)arg3 ;
-(unsigned long long)guaranteedAssetLimit;
-(void)_cleanupInternallyProtectedAssets;
-(BOOL)_containsAssetWithIdentifier:(id)arg1 ;
-(BOOL)_isAssetWithIdentiferExternallyProtected:(id)arg1 ;
-(id)_urlForAssetIdentifier:(id)arg1 ;
-(BOOL)_markAssetWithIdentifier:(id)arg1 asProtected:(BOOL)arg2 error:(id*)arg3 ;
-(BOOL)_removeAssetWithIdentifier:(id)arg1 ;
-(id)_filenameForAssetWithIdentifier:(id)arg1 extension:(id)arg2 ;
-(BOOL)_moveAssetWithIdentifier:(id)arg1 atURL:(id)arg2 toDirectory:(id)arg3 filename:(id)arg4 error:(id*)arg5 ;
-(void)_addInternallyProtectedAssetWithIdentifier:(id)arg1 ;
-(void)_addProtectedAssetWithIdentifier:(id)arg1 ;
-(void)_setCacheTimestamp:(id)arg1 forAssetWithIdentifier:(id)arg2 ;
-(id)_assetIdentifierForFile:(id)arg1 ;
-(void)_setURL:(id)arg1 forAssetIdentifier:(id)arg2 ;
-(BOOL)_markAssetWithIdentifier:(id)arg1 asInternallyProtected:(BOOL)arg2 error:(id*)arg3 ;
-(void)_enumerateAssetFilesInDirectory:(id)arg1 usingBlock:(/*^block*/id)arg2 ;
-(BOOL)_createPurgeableDirectoryWithError:(id*)arg1 ;
-(id)_cacheTimestampKeyForAssetWithIdentifier:(id)arg1 ;
-(void)_removeURLForAssetIdentifier:(id)arg1 ;
-(void)_removeInternallyProtectedAssetWithIdentifier:(id)arg1 ;
-(void)_removeProtectedAssetWithIdentifier:(id)arg1 ;
-(BOOL)_isAssetWithIdentifierProtected:(id)arg1 ;
-(BOOL)_moveAssetWithIdentifier:(id)arg1 toDirectory:(id)arg2 error:(id*)arg3 ;
-(unsigned long long)_countForProtectedAssetWithIdentifier:(id)arg1 ;
-(id)_cacheTimestampForAssetWithIdentifier:(id)arg1 ;
-(id)_allAssetIdentifiers;
-(BOOL)_isAssetWithIdentifierInternallyProtected:(id)arg1 ;
-(NSMutableDictionary *)assetToURLMap;
-(void)setAssetToURLMap:(NSMutableDictionary *)arg1 ;
-(NSMutableSet *)internalProtectedAssets;
-(void)setInternalProtectedAssets:(NSMutableSet *)arg1 ;
-(NSCountedSet *)protectedAssets;
-(void)setProtectedAssets:(NSCountedSet *)arg1 ;
-(NSURL *)protectedDirectory;
-(void)setProtectedDirectory:(NSURL *)arg1 ;
-(NSURL *)purgeableDirectory;
-(void)setPurgeableDirectory:(NSURL *)arg1 ;
@end

