/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 12:52:40 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVIdleScreen.app/TVIdleScreen
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_semaphore;
@class NSObject, NSHashTable;

@interface TVIAssetDownloadManager : NSObject {

	NSObject*<OS_dispatch_semaphore> _concurrentDownloadsSemaphore;
	NSHashTable* _downloadTasks;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_semaphore> concurrentDownloadsSemaphore;              //@synthesize concurrentDownloadsSemaphore=_concurrentDownloadsSemaphore - In the implementation block
@property (nonatomic,retain) NSHashTable * downloadTasks;                                                //@synthesize downloadTasks=_downloadTasks - In the implementation block
-(id)init;
-(void)setDownloadTasks:(NSHashTable *)arg1 ;
-(NSHashTable *)downloadTasks;
-(void)cancelDownloads;
-(long long)assetDownloadInterval;
-(id)mostRecentDownloadDate;
-(void)downloadAssetAtURL:(id)arg1 withCompletion:(/*^block*/id)arg2 ;
-(NSObject*<OS_dispatch_semaphore>)concurrentDownloadsSemaphore;
-(void)setConcurrentDownloadsSemaphore:(NSObject*<OS_dispatch_semaphore>)arg1 ;
@end

