/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:59:25 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVSettings.app/TVSettings
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class ACAccount;

@interface TVSettingsITMSSandboxFacade : NSObject {

	BOOL _isSandboxUIEnabled;
	BOOL _isAuthenticationInProgress;
	ACAccount* _sandboxAccount;

}

@property (assign,nonatomic) BOOL isSandboxUIEnabled;                      //@synthesize isSandboxUIEnabled=_isSandboxUIEnabled - In the implementation block
@property (nonatomic,retain) ACAccount * sandboxAccount;                   //@synthesize sandboxAccount=_sandboxAccount - In the implementation block
@property (assign,nonatomic) BOOL isAuthenticationInProgress;              //@synthesize isAuthenticationInProgress=_isAuthenticationInProgress - In the implementation block
-(id)init;
-(void)dealloc;
-(void)_accountStoreDidChange:(id)arg1 ;
-(BOOL)isAuthenticationInProgress;
-(void)setIsAuthenticationInProgress:(BOOL)arg1 ;
-(BOOL)isSandboxUIEnabled;
-(ACAccount *)sandboxAccount;
-(void)signInSandboxAccountWithPresentingViewController:(id)arg1 ;
-(void)updateSandboxAccountState;
-(id)_getSandboxAccount;
-(void)setIsSandboxUIEnabled:(BOOL)arg1 ;
-(void)setSandboxAccount:(ACAccount *)arg1 ;
@end

