/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:59:24 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVSettings.app/TVSettings
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TVSettings/TVSettings-Structs.h>
#import <UIKitCore/UIView.h>

@class UILabel, NSString;

@interface TVSettingsOverscanView : UIView {

	UILabel* _titleLabel;
	UILabel* _textLabel;
	UILabel* _actionSafeLabel;
	UILabel* _fullscreenLabel;
	NSString* _actionSafeText;
	NSString* _fullscreenText;

}

@property (nonatomic,copy) NSString * titleText; 
@property (nonatomic,copy) NSString * instructionText; 
@property (nonatomic,copy) NSString * actionSafeText;               //@synthesize actionSafeText=_actionSafeText - In the implementation block
@property (nonatomic,copy) NSString * fullscreenText;               //@synthesize fullscreenText=_fullscreenText - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(NSString *)titleText;
-(void)setTitleText:(NSString *)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setInstructionText:(NSString *)arg1 ;
-(void)setActionSafeText:(NSString *)arg1 ;
-(void)setFullscreenText:(NSString *)arg1 ;
-(NSString *)instructionText;
-(NSString *)actionSafeText;
-(NSString *)fullscreenText;
@end

