/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:59:23 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVSettings.app/TVSettings
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TVSettings/HMHomeManagerDelegate.h>
#import <TVSettings/HMHomeDelegate.h>

@class TVSettingsUser, NSArray, NSString, HMHomeManager, AMSBag;

@interface TVSettingsAccountsFacade : NSObject <HMHomeManagerDelegate, HMHomeDelegate> {

	BOOL _isAddingLocalUser;
	BOOL _isRemovingLocalUser;
	BOOL _doesAnyUserNeedHomeInviteInfomation;
	TVSettingsUser* _currentUser;
	NSArray* _users;
	NSString* _homeName;
	HMHomeManager* _homeManager;
	AMSBag* _amsBag;

}

@property (nonatomic,retain) TVSettingsUser * currentUser;                          //@synthesize currentUser=_currentUser - In the implementation block
@property (nonatomic,copy) NSArray * users;                                         //@synthesize users=_users - In the implementation block
@property (assign,nonatomic) BOOL isAddingLocalUser;                                //@synthesize isAddingLocalUser=_isAddingLocalUser - In the implementation block
@property (assign,nonatomic) BOOL isRemovingLocalUser;                              //@synthesize isRemovingLocalUser=_isRemovingLocalUser - In the implementation block
@property (nonatomic,retain) NSString * homeName;                                   //@synthesize homeName=_homeName - In the implementation block
@property (nonatomic,retain) HMHomeManager * homeManager;                           //@synthesize homeManager=_homeManager - In the implementation block
@property (assign,nonatomic) BOOL doesAnyUserNeedHomeInviteInfomation;              //@synthesize doesAnyUserNeedHomeInviteInfomation=_doesAnyUserNeedHomeInviteInfomation - In the implementation block
@property (nonatomic,retain) AMSBag * amsBag;                                       //@synthesize amsBag=_amsBag - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(TVSettingsUser *)currentUser;
-(void)setCurrentUser:(TVSettingsUser *)arg1 ;
-(NSArray *)users;
-(void)setUsers:(NSArray *)arg1 ;
-(void)homeManagerDidUpdateHomes:(id)arg1 ;
-(void)homeDidUpdateName:(id)arg1 ;
-(void)home:(id)arg1 didAddAccessory:(id)arg2 ;
-(void)home:(id)arg1 didRemoveAccessory:(id)arg2 ;
-(void)home:(id)arg1 didAddUser:(id)arg2 ;
-(void)home:(id)arg1 didRemoveUser:(id)arg2 ;
-(NSString *)homeName;
-(void)setHomeName:(NSString *)arg1 ;
-(HMHomeManager *)homeManager;
-(void)setHomeManager:(HMHomeManager *)arg1 ;
-(void)setAmsBag:(AMSBag *)arg1 ;
-(AMSBag *)amsBag;
-(BOOL)isAddingLocalUser;
-(void)addLocalUserWithPresentingViewController:(id)arg1 ;
-(void)switchCurrentUserToUser:(id)arg1 ;
-(void)_initialLoad;
-(void)setIsAddingLocalUser:(BOOL)arg1 ;
-(void)setIsRemovingLocalUser:(BOOL)arg1 ;
-(void)_asyncReloadUsers;
-(void)_updateHomeInviteForUsersThatNeedIt;
-(void)_setCurrentUser:(id)arg1 users:(id)arg2 doesAnyUserNeedHomeInviteInfomation:(BOOL)arg3 ;
-(void)removeLocalUser:(id)arg1 completion:(/*^block*/id)arg2 ;
-(BOOL)isRemovingLocalUser;
-(BOOL)doesAnyUserNeedHomeInviteInfomation;
-(void)setDoesAnyUserNeedHomeInviteInfomation:(BOOL)arg1 ;
@end

