/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:59:25 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVSettings.app/TVSettings
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TVSettings/TVSettings-Structs.h>
#import <UIKitCore/UIView.h>
#import <TVSettings/TVSettingsPasscodeDigitViewDelegate.h>

@protocol TVSettingsIPEntryViewDelegate;
@class NSArray, NSString, UIButton;

@interface TVSettingsIPEntryView : UIView <TVSettingsPasscodeDigitViewDelegate> {

	id<TVSettingsIPEntryViewDelegate> _delegate;
	NSArray* _digitViews;
	NSArray* _dotViews;
	NSString* _ipString;
	UIButton* _doneButton;

}

@property (nonatomic,retain) NSArray * digitViews;                                           //@synthesize digitViews=_digitViews - In the implementation block
@property (nonatomic,retain) NSArray * dotViews;                                             //@synthesize dotViews=_dotViews - In the implementation block
@property (nonatomic,retain) NSString * ipString;                                            //@synthesize ipString=_ipString - In the implementation block
@property (nonatomic,retain) UIButton * doneButton;                                          //@synthesize doneButton=_doneButton - In the implementation block
@property (nonatomic,copy) NSString * IPAddress; 
@property (assign,nonatomic,__weak) id<TVSettingsIPEntryViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id<TVSettingsIPEntryViewDelegate>)delegate;
-(void)setDelegate:(id<TVSettingsIPEntryViewDelegate>)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(NSString *)ipString;
-(void)layoutSubviews;
-(BOOL)canBecomeFocused;
-(id)preferredFocusEnvironments;
-(UIButton *)doneButton;
-(void)setDoneButton:(UIButton *)arg1 ;
-(NSString *)IPAddress;
-(void)setDigitViews:(NSArray *)arg1 ;
-(NSArray *)digitViews;
-(void)setIPAddress:(NSString *)arg1 ;
-(void)passcodeDigitView:(id)arg1 didChangeText:(id)arg2 ;
-(id)initWithIPAddress:(id)arg1 ;
-(void)doneButton:(id)arg1 ;
-(void)_updateDigitLimits;
-(long long)_octetForBlockIndex:(unsigned long long)arg1 ;
-(void)passcodeDigitViewDidBecomeFirstResponder:(id)arg1 ;
-(void)passcodeDigitViewDidResignFirstResponder:(id)arg1 ;
-(NSArray *)dotViews;
-(void)setDotViews:(NSArray *)arg1 ;
-(void)setIpString:(NSString *)arg1 ;
@end

