/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:33 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/backboardd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <backboardd/BSDescriptionProviding.h>

@protocol BKHIDEventSenderInfo;
@class NSSet, NSString;

@interface _BKPointerEventRecord : NSObject <BSDescriptionProviding> {

	BOOL _didTrackPointerMovement;
	BOOL _didTrackButtonDown;
	BOOL _trackingPointerMovement;
	BOOL _trackingButtonDown;
	id<BKHIDEventSenderInfo> _senderInfo;
	NSSet* _destinations;
	double _destinationCaptureTime;

}

@property (nonatomic,retain) id<BKHIDEventSenderInfo> senderInfo;              //@synthesize senderInfo=_senderInfo - In the implementation block
@property (nonatomic,retain) NSSet * destinations;                             //@synthesize destinations=_destinations - In the implementation block
@property (assign,nonatomic) double destinationCaptureTime;                    //@synthesize destinationCaptureTime=_destinationCaptureTime - In the implementation block
@property (assign,nonatomic) BOOL trackingPointerMovement;                     //@synthesize trackingPointerMovement=_trackingPointerMovement - In the implementation block
@property (assign,nonatomic) BOOL trackingButtonDown;                          //@synthesize trackingButtonDown=_trackingButtonDown - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)descriptionWithMultilinePrefix:(id)arg1 ;
-(id)succinctDescriptionBuilder;
-(id)descriptionBuilderWithMultilinePrefix:(id)arg1 ;
-(id)succinctDescription;
-(NSSet *)destinations;
-(void)setDestinations:(NSSet *)arg1 ;
-(id<BKHIDEventSenderInfo>)senderInfo;
-(void)setSenderInfo:(id<BKHIDEventSenderInfo>)arg1 ;
-(void)setTrackingPointerMovement:(BOOL)arg1 ;
-(void)setTrackingButtonDown:(BOOL)arg1 ;
-(double)destinationCaptureTime;
-(void)setDestinationCaptureTime:(double)arg1 ;
-(BOOL)trackingPointerMovement;
-(BOOL)trackingButtonDown;
@end

