/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:32 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/backboardd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <backboardd/BKDisplayAnnotationContent.h>

@class NSString;

@interface BKDisplayAnnotationStringContent : NSObject <BKDisplayAnnotationContent> {

	NSString* _string;

}

@property (nonatomic,retain) NSString * string;                     //@synthesize string=_string - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)contentWithString:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(NSString *)description;
-(NSString *)string;
-(void)setString:(NSString *)arg1 ;
@end

