/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:31 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/backboardd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <backboardd/backboardd-Structs.h>
#import <backboardd/BKHIDEventProcessor.h>

@class NSMutableDictionary, NSString;

@interface BKGenericGestureHIDEventProcessor : NSObject <BKHIDEventProcessor> {

	NSMutableDictionary* _pendingDestinationsPerSenderID;

}

@property (nonatomic,retain) NSMutableDictionary * pendingDestinationsPerSenderID;              //@synthesize pendingDestinationsPerSenderID=_pendingDestinationsPerSenderID - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(long long)processEvent:(IOHIDEventRef)arg1 sender:(id)arg2 dispatcher:(id)arg3 ;
-(NSMutableDictionary *)pendingDestinationsPerSenderID;
-(void)setPendingDestinationsPerSenderID:(NSMutableDictionary *)arg1 ;
@end

