/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:32 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/backboardd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <backboardd/backboardd-Structs.h>
@class NSPointerArray, NSBundle, NSString;

@interface BKImageSequence : NSObject {

	long long _maximumImageCount;
	double _scale;
	NSPointerArray* _images;
	NSBundle* _bundle;
	NSString* _basename;
	NSString* _idiomSuffix;

}

@property (nonatomic,retain) NSPointerArray * images;                    //@synthesize images=_images - In the implementation block
@property (nonatomic,retain) NSBundle * bundle;                          //@synthesize bundle=_bundle - In the implementation block
@property (nonatomic,copy) NSString * basename;                          //@synthesize basename=_basename - In the implementation block
@property (nonatomic,retain) NSString * idiomSuffix;                     //@synthesize idiomSuffix=_idiomSuffix - In the implementation block
@property (nonatomic,readonly) long long maximumImageCount;              //@synthesize maximumImageCount=_maximumImageCount - In the implementation block
@property (nonatomic,readonly) double scale;                             //@synthesize scale=_scale - In the implementation block
-(double)scale;
-(NSBundle *)bundle;
-(NSPointerArray *)images;
-(void)setImages:(NSPointerArray *)arg1 ;
-(CGImageRef)imageAtIndex:(long long)arg1 ;
-(void)setBundle:(NSBundle *)arg1 ;
-(NSString *)basename;
-(void)setBasename:(NSString *)arg1 ;
-(id)allImages;
-(id)_idiomSuffix;
-(id)initWithBasename:(id)arg1 bundle:(id)arg2 imageCount:(long long)arg3 scale:(double)arg4 ;
-(CGImageRef)_createImageForIndex:(unsigned long long)arg1 basename:(id)arg2 scale:(double)arg3 idiom:(id)arg4 bundle:(id)arg5 ;
-(CGImageRef)_imageAtIndex:(long long)arg1 ;
-(void)_loadAllImages;
-(long long)maximumImageCount;
-(NSString *)idiomSuffix;
-(void)setIdiomSuffix:(NSString *)arg1 ;
@end

