/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:54:29 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/PineBoard.app/PineBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <PineBoard/PineBoard-Structs.h>
@class NSArray, BKSAssertion, SSIndicatorLight;

@interface ATVHIDSystemClient : NSObject {

	IOHIDEventSystemClientRef _hidSystemClient;
	IOHIDEventSystemClientRef _btKeyboardHIDSystemClient;
	NSArray* _normalEventRouters;
	BKSAssertion* _dispatchingRulesAssertion;
	SSIndicatorLight* _sil;

}
+(id)sharedInstance;
+(BOOL)isIRRemoteButtonEvent:(IOHIDEventRef)arg1 ;
+(BOOL)isCECButtonEvent:(IOHIDEventRef)arg1 ;
+(BOOL)isRemoteAppEvent:(IOHIDEventRef)arg1 ;
+(BOOL)isBluetoothKeyboardButtonEvent:(IOHIDEventRef)arg1 ;
+(BOOL)_buttonEvent:(IOHIDEventRef)arg1 containsUsage:(long long)arg2 ;
-(id)init;
-(void)dealloc;
-(int)_init;
-(void)setupHIDEventRouters;
-(void)setSILState_On;
-(void)setSILStateForHIDEvent:(IOHIDEventRef)arg1 ;
-(void)flashSILMorseCode:(id)arg1 ;
-(void)_setSILState_On:(id)arg1 ;
-(void)_setSILState_Off:(id)arg1 ;
-(void)_startKeyboardHIDClient;
-(void)_processAppleVendorIRRemoteEvent:(IOHIDEventRef)arg1 ;
-(void)_processAppleVendorDebugEvent:(IOHIDEventRef)arg1 ;
-(void)_processBatterySystemEvent:(IOHIDEventRef)arg1 ;
-(void)_processConsumerEvent:(IOHIDEventRef)arg1 ;
-(void)_processGenericDesktopEvent:(IOHIDEventRef)arg1 ;
-(void)_setSILForButtonDown:(BOOL)arg1 ;
-(id)_routingRulesThatIgnoreEvents;
-(void)_processHIDEvent:(IOHIDEventRef)arg1 ;
-(void)setSILState_Off;
-(void)disableAllEventRouting;
-(void)enableSleepEventRouting;
-(void)enableNormalEventRouting;
@end

