/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:54:29 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/PineBoard.app/PineBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PineBoard/PineBoard-Structs.h>
#import <PineBoardServices/PBSAppInfo.h>
#import <PineBoard/PBAppInfo.h>
@class PBApplicationInfo, PBApplicationPlaceholder;


@protocol PBAppInfo <NSObject>
@property (nonatomic,readonly) PBApplicationInfo * applicationInfo; 
@property (nonatomic,readonly) PBApplicationPlaceholder * applicationPlaceholder; 
@required
-(PBApplicationInfo *)applicationInfo;
-(id)initWithApplicationInfo:(id)arg1;
-(id)initWithApplicationPlaceholder:(id)arg1;
-(PBApplicationPlaceholder *)applicationPlaceholder;

@end


@class PBApplicationInfo, PBApplicationPlaceholder, FBSSceneIdentity, NSString;

@interface PBAppInfo : PBSAppInfo <PBAppInfo> {

	PBApplicationInfo* _applicationInfo;
	PBApplicationPlaceholder* _applicationPlaceholder;

}

@property (nonatomic,readonly) FBSSceneIdentity * defaultSceneIdentity; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) PBApplicationInfo * applicationInfo;                            //@synthesize applicationInfo=_applicationInfo - In the implementation block
@property (nonatomic,readonly) PBApplicationPlaceholder * applicationPlaceholder;              //@synthesize applicationPlaceholder=_applicationPlaceholder - In the implementation block
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(NSString *)description;
-(Class)classForCoder;
-(PBApplicationInfo *)applicationInfo;
-(id)initWithApplicationInfo:(id)arg1 ;
-(id)initWithAppInfo:(id)arg1 ;
-(id)initWithApplicationPlaceholder:(id)arg1 ;
-(FBSSceneIdentity *)defaultSceneIdentity;
-(BOOL)isPBAppInfo;
-(PBApplicationPlaceholder *)applicationPlaceholder;
@end

