/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:54:28 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/PineBoard.app/PineBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PineBoard/MCProfileConnectionObserver.h>
#import <PineBoard/PBAppInfoStorePolicyProviding.h>

@protocol OS_dispatch_queue;
@class NSObservation, NSObject, NSArray, NSSet, NSString;

@interface PBAppInfoPolicy : NSObject <MCProfileConnectionObserver, PBAppInfoStorePolicyProviding> {

	BOOL _queue_showInternalApps;
	BOOL _queue_showNonDefaultSystemApps;
	BOOL _queue_enforceSystemAppProvisioning;
	NSObservation* _enforceProvisioningObserver;
	NSObservation* _internalAppsEnabledObserver;
	NSObservation* _nonDefaultSystemAppsEnabledObserver;
	NSObject*<OS_dispatch_queue> _accessQueue;
	NSArray* _queue_appWhitelistOptions;
	NSArray* _queue_restrictedHomscreenLayout;
	NSSet* _queue_exclusionTags;

}

@property (nonatomic,readonly) NSObservation * enforceProvisioningObserver;                      //@synthesize enforceProvisioningObserver=_enforceProvisioningObserver - In the implementation block
@property (nonatomic,readonly) NSObservation * internalAppsEnabledObserver;                      //@synthesize internalAppsEnabledObserver=_internalAppsEnabledObserver - In the implementation block
@property (nonatomic,readonly) NSObservation * nonDefaultSystemAppsEnabledObserver;              //@synthesize nonDefaultSystemAppsEnabledObserver=_nonDefaultSystemAppsEnabledObserver - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> accessQueue;                         //@synthesize accessQueue=_accessQueue - In the implementation block
@property (nonatomic,copy,readonly) NSArray * queue_appWhitelistOptions;                         //@synthesize queue_appWhitelistOptions=_queue_appWhitelistOptions - In the implementation block
@property (nonatomic,copy,readonly) NSArray * queue_restrictedHomscreenLayout;                   //@synthesize queue_restrictedHomscreenLayout=_queue_restrictedHomscreenLayout - In the implementation block
@property (nonatomic,copy,readonly) NSSet * queue_exclusionTags;                                 //@synthesize queue_exclusionTags=_queue_exclusionTags - In the implementation block
@property (nonatomic,readonly) BOOL queue_showInternalApps;                                      //@synthesize queue_showInternalApps=_queue_showInternalApps - In the implementation block
@property (nonatomic,readonly) BOOL queue_showNonDefaultSystemApps;                              //@synthesize queue_showNonDefaultSystemApps=_queue_showNonDefaultSystemApps - In the implementation block
@property (nonatomic,readonly) BOOL queue_enforceSystemAppProvisioning;                          //@synthesize queue_enforceSystemAppProvisioning=_queue_enforceSystemAppProvisioning - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)_whitelistBlacklistExemptBundleIdentifiers;
+(BOOL)_checkApplicationIsRestricted:(id)arg1 ;
+(id)_provisioningExemptBundleIdentifiers;
+(BOOL)_isApplicationHiddenWithPreference:(id)arg1 ;
+(BOOL)_isAppRestrictionProfileInstalled;
+(id)_simulatorDisabledBundleIdentifiers;
-(id)init;
-(void)dealloc;
-(void)profileConnectionDidReceiveAppWhitelistChangedNotification:(id)arg1 userInfo:(id)arg2 ;
-(void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)arg1 userInfo:(id)arg2 ;
-(NSObject*<OS_dispatch_queue>)accessQueue;
-(id)configurationForProposedAppInfos:(id)arg1 ;
-(BOOL)isPlaceholderHidden:(id)arg1 ;
-(BOOL)isPlaceholderEnabled:(id)arg1 reasons:(unsigned long long*)arg2 ;
-(BOOL)isApplicationHidden:(id)arg1 ;
-(BOOL)isApplicationEnabled:(id)arg1 reasons:(unsigned long long*)arg2 ;
-(BOOL)_queueUpdateCachedPreferences;
-(void)managedHomeScreenLayoutChanged:(id)arg1 ;
-(void)programmingGuideDidUpdate:(id)arg1 ;
-(void)_updateCachedPreferences;
-(void)_refreshCachedAppWhitelistOptions;
-(void)_refreshCachedManagedAppLayout;
-(void)_setNeedsReload;
-(NSObservation *)enforceProvisioningObserver;
-(NSObservation *)internalAppsEnabledObserver;
-(NSObservation *)nonDefaultSystemAppsEnabledObserver;
-(NSArray *)queue_appWhitelistOptions;
-(NSArray *)queue_restrictedHomscreenLayout;
-(NSSet *)queue_exclusionTags;
-(BOOL)queue_showInternalApps;
-(BOOL)queue_showNonDefaultSystemApps;
-(BOOL)queue_enforceSystemAppProvisioning;
@end

