/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:54:29 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/PineBoard.app/PineBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PBIssueDataReporter : NSObject
-(void)reportLatestIssueData;
-(void)_reportLatestIssueDataWithRemainingAttempts:(long long)arg1 ;
-(void)reportIssueDataAtPath:(id)arg1 ;
-(id)_latestSysdiagnoseFilePath;
-(void)_uploadSysdiagnoseAtPath:(id)arg1 toURL:(id)arg2 deleteAfterUpload:(BOOL)arg3 ;
@end

