/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:49 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/rapportd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary, RPServer;

@interface RPXPCMatchingEntry : NSObject {

	BOOL _appSignIn;
	BOOL _state;
	NSDictionary* _event;
	/*^block*/id _handler;
	RPServer* _server;
	unsigned long long _token;

}

@property (assign,nonatomic) BOOL appSignIn;                        //@synthesize appSignIn=_appSignIn - In the implementation block
@property (nonatomic,copy) NSDictionary * event;                    //@synthesize event=_event - In the implementation block
@property (nonatomic,copy) id handler;                              //@synthesize handler=_handler - In the implementation block
@property (nonatomic,retain) RPServer * server;                     //@synthesize server=_server - In the implementation block
@property (assign,nonatomic) BOOL state;                            //@synthesize state=_state - In the implementation block
@property (assign,nonatomic) unsigned long long token;              //@synthesize token=_token - In the implementation block
-(id)handler;
-(unsigned long long)token;
-(BOOL)state;
-(void)setState:(BOOL)arg1 ;
-(RPServer *)server;
-(void)setServer:(RPServer *)arg1 ;
-(void)setHandler:(id)arg1 ;
-(NSDictionary *)event;
-(void)setToken:(unsigned long long)arg1 ;
-(void)setEvent:(NSDictionary *)arg1 ;
-(void)setAppSignIn:(BOOL)arg1 ;
-(BOOL)appSignIn;
@end

