/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 2:00:52 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVPhotos.app/TVPhotos
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIView.h>

@protocol TVPSharedPSActivityBannerFocusDelegate;
@class NSString, UIImage, UILabel, UIView, UIBezierPath, TVPImageStackView, UIMotionEffectGroup;

@interface TVPSharedPSActivityBannerView : UIView {

	NSString* _bannerTitle;
	UIImage* _bannerImage;
	id<TVPSharedPSActivityBannerFocusDelegate> _delegate;
	UILabel* _bannerTitleLabel;
	UIView* _bannerTitleShadowView;
	UIBezierPath* _bannerTitleShadowPath;
	TVPImageStackView* _imageStackView;
	UIMotionEffectGroup* _motionEffectGroup;

}

@property (nonatomic,retain) UILabel * bannerTitleLabel;                                              //@synthesize bannerTitleLabel=_bannerTitleLabel - In the implementation block
@property (nonatomic,retain) UIView * bannerTitleShadowView;                                          //@synthesize bannerTitleShadowView=_bannerTitleShadowView - In the implementation block
@property (nonatomic,retain) UIBezierPath * bannerTitleShadowPath;                                    //@synthesize bannerTitleShadowPath=_bannerTitleShadowPath - In the implementation block
@property (nonatomic,retain) TVPImageStackView * imageStackView;                                      //@synthesize imageStackView=_imageStackView - In the implementation block
@property (nonatomic,retain) UIMotionEffectGroup * motionEffectGroup;                                 //@synthesize motionEffectGroup=_motionEffectGroup - In the implementation block
@property (nonatomic,copy) NSString * bannerTitle;                                                    //@synthesize bannerTitle=_bannerTitle - In the implementation block
@property (nonatomic,retain) UIImage * bannerImage;                                                   //@synthesize bannerImage=_bannerImage - In the implementation block
@property (assign,nonatomic,__weak) id<TVPSharedPSActivityBannerFocusDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id)init;
-(id<TVPSharedPSActivityBannerFocusDelegate>)delegate;
-(void)setDelegate:(id<TVPSharedPSActivityBannerFocusDelegate>)arg1 ;
-(NSString *)bannerTitle;
-(void)layoutSubviews;
-(void)setBannerTitle:(NSString *)arg1 ;
-(BOOL)canBecomeFocused;
-(BOOL)_applyKeyPathsAndRelativeValues:(id)arg1 forMotionEffect:(id)arg2 ;
-(void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2 ;
-(void)pressesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)pressesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)pressesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)setBannerImage:(UIImage *)arg1 ;
-(UIImage *)bannerImage;
-(void)_attachMotionEffects;
-(void)_detachMotionEffects;
-(void)setImageStackView:(TVPImageStackView *)arg1 ;
-(TVPImageStackView *)imageStackView;
-(BOOL)_unapplyMotionEffect:(id)arg1 ;
-(UILabel *)bannerTitleLabel;
-(void)setBannerTitleLabel:(UILabel *)arg1 ;
-(UIView *)bannerTitleShadowView;
-(void)setBannerTitleShadowView:(UIView *)arg1 ;
-(UIBezierPath *)bannerTitleShadowPath;
-(void)setBannerTitleShadowPath:(UIBezierPath *)arg1 ;
-(UIMotionEffectGroup *)motionEffectGroup;
-(void)setMotionEffectGroup:(UIMotionEffectGroup *)arg1 ;
@end

