/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 2:00:38 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVProfileMappingService.app/TVProfileMappingService
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIViewController.h>
#import <TVProfileMappingService/TVProfileMappingViewControllerDelegate.h>
#import <TVProfileMappingService/PBSViewServicePresenter.h>

@class UINavigationController, NSString;

@interface TVProfileMappingRemoteViewController : UIViewController <TVProfileMappingViewControllerDelegate, PBSViewServicePresenter> {

	UINavigationController* _navigationController;

}

@property (nonatomic,retain) UINavigationController * navigationController;              //@synthesize navigationController=_navigationController - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)_exportedInterface;
+(id)_remoteViewControllerInterface;
-(UINavigationController *)navigationController;
-(void)setNavigationController:(UINavigationController *)arg1 ;
-(void)viewServiceBeginPresentationWithOptions:(id)arg1 ;
-(void)viewServiceEndPresentationWithOptions:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)profileMappingViewController:(id)arg1 didFinishWithMap:(id)arg2 ;
@end

