/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:54:56 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Setup.app/Setup
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Setup/Setup-Structs.h>
#import <UIKitCore/UIView.h>

@interface SATVHighlightView : UIView {

	BOOL _isAnimating;

}
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setHighlightProgress:(double)arg1 ;
-(void)_setHighlightProgress:(double)arg1 ;
@end

