/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:10 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/HeadBoard.app/HeadBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <HeadBoard/HeadBoard-Structs.h>
#import <HeadBoard/NSSecureCoding.h>

@class NSArray;

@interface _HBApplicationIconFileMetadata : NSObject <NSSecureCoding> {

	double _imageScale;
	NSArray* _layers;
	CGSize _imageSize;

}

@property (assign,nonatomic) CGSize imageSize;               //@synthesize imageSize=_imageSize - In the implementation block
@property (assign,nonatomic) double imageScale;              //@synthesize imageScale=_imageScale - In the implementation block
@property (nonatomic,retain) NSArray * layers;               //@synthesize layers=_layers - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSArray *)layers;
-(CGSize)imageSize;
-(void)setLayers:(NSArray *)arg1 ;
-(double)imageScale;
-(void)setImageSize:(CGSize)arg1 ;
-(void)setImageScale:(double)arg1 ;
@end

