/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:09 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/HeadBoard.app/HeadBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <HeadBoard/PBSAppInfoControllerObserver.h>

@protocol HBAppInfoControllerDelegate;
@class PBSAppInfoConfiguration, PBSAppInfoController, NSMutableDictionary, NSDictionary, NSString;

@interface HBAppInfoController : NSObject <PBSAppInfoControllerObserver> {

	id<HBAppInfoControllerDelegate> _delegate;
	PBSAppInfoConfiguration* _configuration;
	PBSAppInfoController* _appInfoController;
	NSMutableDictionary* _mutableAppInfos;

}

@property (getter=_appInfoController,nonatomic,readonly) PBSAppInfoController * appInfoController;              //@synthesize appInfoController=_appInfoController - In the implementation block
@property (getter=_mutableAppInfos,nonatomic,readonly) NSMutableDictionary * mutableAppInfos;                   //@synthesize mutableAppInfos=_mutableAppInfos - In the implementation block
@property (setter=_setConfiguration:,nonatomic,retain) PBSAppInfoConfiguration * configuration;                 //@synthesize configuration=_configuration - In the implementation block
@property (assign,nonatomic,__weak) id<HBAppInfoControllerDelegate> delegate;                                   //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) NSDictionary * appInfos; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSString *)description;
-(id)init;
-(id<HBAppInfoControllerDelegate>)delegate;
-(void)setDelegate:(id<HBAppInfoControllerDelegate>)arg1 ;
-(PBSAppInfoConfiguration *)configuration;
-(void)_setConfiguration:(id)arg1 ;
-(NSDictionary *)appInfos;
-(void)appInfoController:(id)arg1 didUpdate:(id)arg2 ;
-(id)_appInfoController;
-(id)_initWithAppInfoController:(id)arg1 ;
-(id)_mutableAppInfos;
-(void)_notifyDelegateDidAddAppInfos:(id)arg1 ;
-(void)_notifyDelegateDidRemoveAppInfos:(id)arg1 ;
-(void)_notifyDelegateDidUpdateAlternateAppIconsForAppInfos:(id)arg1 ;
-(void)_didAddAppInfos:(id)arg1 ;
-(void)_didRemoveAppInfos:(id)arg1 ;
-(void)_didUpdateAppInfos:(id)arg1 ;
-(void)_didUpdateConfiguration:(id)arg1 ;
-(void)enumerateAppInfosUsingBlock:(/*^block*/id)arg1 ;
-(id)appInfoWithBundleIdentifier:(id)arg1 ;
@end

