/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:35 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/dmd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <dmd/DMDPayloadMetadata.h>

@interface DMDCommandPayloadMetadata : DMDPayloadMetadata
+(id)fetchRequestForCommandsFromOrganizationWithIdentifier:(id)arg1 matchingPredicate:(id)arg2 ;
+(id)fetchRequestForCommandsFromOrganizationWithIdentifier:(id)arg1 ;
+(id)fetchRequestForCommandsPendingExecutionFromOrganizationWithIdentifier:(id)arg1 ;
+(id)fetchRequestForCommandsPendingRemovalFromOrganizationWithIdentifier:(id)arg1 ;
+(id)fetchRequestForCommandsPendingDeleteFromOrganizationWithIdentifier:(id)arg1 ;
+(id)commandsWithPayloadDictionaries:(id)arg1 organizationIdentifier:(id)arg2 context:(id)arg3 error:(id*)arg4 ;
@end

