/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:35 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/dmd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <dmd/DMDEngineDatabaseOperation.h>

@protocol DMDDeviceStateProvider;
@class NSObject;

@interface DMDEngineDatabaseInitializationOperation : DMDEngineDatabaseOperation {

	NSObject*<DMDDeviceStateProvider> _deviceStateProvider;

}

@property (nonatomic,retain) NSObject*<DMDDeviceStateProvider> deviceStateProvider;              //@synthesize deviceStateProvider=_deviceStateProvider - In the implementation block
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)main;
-(BOOL)isReady;
-(void)loadPersistentStoresWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)operationWillStart;
-(void)setDeviceStateProvider:(NSObject*<DMDDeviceStateProvider>)arg1 ;
-(NSObject*<DMDDeviceStateProvider>)deviceStateProvider;
-(void)destroyLegacyDatabaseIfNeeded;
-(void)fixupDatabaseWithCompletionHandler:(/*^block*/id)arg1 ;
-(BOOL)updateMetadataForManagedObjectContext:(id)arg1 error:(id*)arg2 ;
-(BOOL)destroyPersistentStoresWithError:(id*)arg1 ;
@end

