/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:35 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/dmd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <dmd/DMDDeviceController.h>

@interface DMDiphoneOSDeviceController : DMDDeviceController
-(id)uniqueIdentifier;
-(id)productName;
-(id)deviceName;
-(id)model;
-(id)deviceType;
-(id)buildVersion;
-(id)serialNumber;
-(id)isInSingleAppMode;
-(id)isSupervised;
-(id)isAwaitingConfiguration;
-(id)modelName;
-(id)osVersion;
-(id)wifiAddress;
-(id)bluetoothAddress;
-(id)marketingName;
-(id)isAppleInternal;
-(id)iTunesStoreAccountHash;
-(id)iTunesStoreAccountIsActive;
-(id)lastCloudBackupDate;
@end

