/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:35 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/dmd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <dmd/DMDAppController.h>

@class NSString, NSMutableDictionary, FBSDisplayLayoutMonitor, NSArray, ASDJobManager, ASDSoftwareUpdatesStore;

@interface DMDiphoneOSAppController : DMDAppController {

	NSString* _singleAppModeBundleIndentifier;
	NSMutableDictionary* _bundleIDsToAssertions;
	FBSDisplayLayoutMonitor* _layoutMonitor;
	NSArray* __foregroundBundleIdentifiers;

}

@property (nonatomic,retain) NSMutableDictionary * bundleIDsToAssertions;                //@synthesize bundleIDsToAssertions=_bundleIDsToAssertions - In the implementation block
@property (nonatomic,retain) FBSDisplayLayoutMonitor * layoutMonitor;                    //@synthesize layoutMonitor=_layoutMonitor - In the implementation block
@property (nonatomic,retain) NSArray * _foregroundBundleIdentifiers;                     //@synthesize _foregroundBundleIdentifiers=__foregroundBundleIdentifiers - In the implementation block
@property (nonatomic,copy) NSString * singleAppModeBundleIndentifier;                    //@synthesize singleAppModeBundleIndentifier=_singleAppModeBundleIndentifier - In the implementation block
@property (nonatomic,readonly) BOOL userIsSignedIn; 
@property (nonatomic,copy,readonly) ASDJobManager * jobManager; 
@property (nonatomic,copy,readonly) ASDSoftwareUpdatesStore * updatesStore; 
+(id)changeTypeAsString:(long long)arg1 ;
+(id)metadataPath;
-(id)initPrivate;
-(NSArray *)_foregroundBundleIdentifiers;
-(FBSDisplayLayoutMonitor *)layoutMonitor;
-(void)setLayoutMonitor:(FBSDisplayLayoutMonitor *)arg1 ;
-(void)didFinishUpdatingForLifeCycle:(id)arg1 ;
-(void)didCancelUpdatingForLifeCycle:(id)arg1 ;
-(void)didFailUpdatingForLifeCycle:(id)arg1 ;
-(void)startRedeemingAppWithCode:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)startUpdatingAppForRequest:(id)arg1 metadata:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)resumeAppUpdateWithBundleIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)_allPropertyKeys;
-(void)_installUserAppForRequest:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_installDeviceLicensedAppForRequest:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_downloadAppForRequest:(id)arg1 type:(long long)arg2 completion:(/*^block*/id)arg3 ;
-(void)_updateForegroundBundleIdentifiers;
-(NSMutableDictionary *)bundleIDsToAssertions;
-(void)setBundleIDsToAssertions:(NSMutableDictionary *)arg1 ;
-(BOOL)writeManagementInformationToDiskWithError:(id*)arg1 ;
-(void)_getMetadataForBundleIdentifier:(id)arg1 storeItemIdentifier:(id)arg2 accountIdentifier:(id)arg3 completion:(/*^block*/id)arg4 ;
-(id)_managedDefaultsForBundleIdentifier:(id)arg1 ;
-(id)_dataContainerPathForBundleIdentifier:(id)arg1 ;
-(void)_applyStoreDictionary:(id)arg1 toAppMetadata:(id)arg2 ;
-(void)sendAppRequestWithBundleIdentifier:(id)arg1 storeItemIdentifier:(id)arg2 accountIdentifier:(id)arg3 type:(long long)arg4 skipDownloads:(BOOL)arg5 completion:(/*^block*/id)arg6 ;
-(void)set_foregroundBundleIdentifiers:(NSArray *)arg1 ;
-(id)foregroundBundleIdentifiers;
-(ASDJobManager *)jobManager;
-(ASDSoftwareUpdatesStore *)updatesStore;
-(void)addTerminationAssertion:(id)arg1 forBundleIdentifier:(id)arg2 ;
-(void)removeTerminationAssertionForBundleIdentifier:(id)arg1 ;
-(BOOL)userIsSignedIn;
-(void)promptUserToSignInWithCompletion:(/*^block*/id)arg1 ;
-(void)installSystemAppWithBundleIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getBundleIdentifierForStoreItemIdentifier:(id)arg1 accountIdentifier:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)getMetadataForNonEnterpriseAppRequest:(id)arg1 accountIdentifier:(id)arg2 completion:(/*^block*/id)arg3 ;
-(BOOL)setConfiguration:(id)arg1 forBundleIdentifier:(id)arg2 error:(id*)arg3 ;
-(NSString *)singleAppModeBundleIndentifier;
-(void)setSingleAppModeBundleIndentifier:(NSString *)arg1 ;
-(void)_uninstallAppWithBundleIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_startUpdatingAppForRequest:(id)arg1 metadata:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)_updateEndedForLifeCycle:(id)arg1 ;
-(id)configurationForBundleIdentifier:(id)arg1 ;
-(id)feedbackForBundleIdentifier:(id)arg1 ;
-(BOOL)setFeedback:(id)arg1 forBundleIdentifier:(id)arg2 error:(id*)arg3 ;
-(void)handleFetchRequest:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)startInstallingEnterpriseAppWithManifestURL:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)startInstallingNonEnterpriseAppForRequest:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)resumeAppInstallationWithBundleIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)startUninstallingAppWithBundleIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)cancelAppInstallationWithBundleIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)cancelAppUpdateWithBundleIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
@end

