/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:36 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/dmd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <dmd/DMDAppOperation.h>

@interface DMDRemoveAppOperation : DMDAppOperation
+(id)requiredEntitlements;
+(id)whitelistedClassesForRequest;
+(BOOL)removeAppMetadataForBundleIdentifier:(id)arg1 error:(id*)arg2 ;
+(void)removeAppWithBundleIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)runWithRequest:(id)arg1 bundleIdentifier:(id)arg2 ;
@end

