/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:59 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/terminusd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <terminusd/terminusd-Structs.h>
#import <terminusd/NRBabelInterface.h>

@protocol OS_dispatch_source, OS_nw_path_evaluator, OS_nw_interface;
@class NSString, NSObject;

@interface NRBabelInterfaceSocket : NRBabelInterface {

	unsigned _ifIndex;
	int _fd;
	NSString* _ifName;
	NSObject*<OS_dispatch_source> _socketReadSource;
	NSObject*<OS_nw_path_evaluator> _pathEvaluator;
	NSObject*<OS_nw_interface> _nwIf;

}

@property (assign,nonatomic) unsigned ifIndex;                                            //@synthesize ifIndex=_ifIndex - In the implementation block
@property (nonatomic,retain) NSString * ifName;                                           //@synthesize ifName=_ifName - In the implementation block
@property (assign,nonatomic) int fd;                                                      //@synthesize fd=_fd - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_source> socketReadSource;              //@synthesize socketReadSource=_socketReadSource - In the implementation block
@property (nonatomic,retain) NSObject*<OS_nw_path_evaluator> pathEvaluator;               //@synthesize pathEvaluator=_pathEvaluator - In the implementation block
@property (nonatomic,retain) NSObject*<OS_nw_interface> nwIf;                             //@synthesize nwIf=_nwIf - In the implementation block
-(BOOL)isEqual:(id)arg1 ;
-(id)description;
-(void)dealloc;
-(NSObject*<OS_nw_path_evaluator>)pathEvaluator;
-(int)fd;
-(unsigned)ifIndex;
-(void)setIfIndex:(unsigned)arg1 ;
-(void)setFd:(int)arg1 ;
-(void)setPathEvaluator:(NSObject*<OS_nw_path_evaluator>)arg1 ;
-(void)setIfName:(NSString *)arg1 ;
-(NSString *)ifName;
-(BOOL)setupLocalAddressCheckAgainst:(const in6_addr*)arg1 ;
-(void)sendPacket:(iovec*)arg1 iovLen:(unsigned)arg2 toAddr:(const in6_addr*)arg3 ;
-(void)addToProhibited:(id)arg1 ;
-(void)readPackets;
-(BOOL)setupLocalAddress;
-(id)initWithInstance:(id)arg1 interface:(unsigned)arg2 ;
-(BOOL)handlePathUpdate:(id)arg1 ;
-(NSObject*<OS_dispatch_source>)socketReadSource;
-(void)setSocketReadSource:(NSObject*<OS_dispatch_source>)arg1 ;
-(NSObject*<OS_nw_interface>)nwIf;
-(void)setNwIf:(NSObject*<OS_nw_interface>)arg1 ;
@end

