/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:59 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/terminusd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue, OS_nw_path_evaluator;
#import <terminusd/terminusd-Structs.h>
@class NSObject, NSMutableArray, NSString;

@interface NRBabelInstance : NSObject {

	unsigned short _nodeSeqno;
	NSObject*<OS_dispatch_queue> _queue;
	unsigned long long _routerID;
	NSMutableArray* _interfaces;
	NSMutableArray* _neighbors;
	NSMutableArray* _sources;
	NSMutableArray* _routes;
	NSMutableArray* _posrs;
	NSObject*<OS_nw_path_evaluator> _ifBringupPathEvaluator;
	NEVirtualInterface_sRef _nevi;
	NSString* _addrStr;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;                                  //@synthesize queue=_queue - In the implementation block
@property (assign,nonatomic) unsigned short nodeSeqno;                                            //@synthesize nodeSeqno=_nodeSeqno - In the implementation block
@property (assign,nonatomic) unsigned long long routerID;                                         //@synthesize routerID=_routerID - In the implementation block
@property (nonatomic,retain) NSMutableArray * interfaces;                                         //@synthesize interfaces=_interfaces - In the implementation block
@property (nonatomic,retain) NSMutableArray * neighbors;                                          //@synthesize neighbors=_neighbors - In the implementation block
@property (nonatomic,retain) NSMutableArray * sources;                                            //@synthesize sources=_sources - In the implementation block
@property (nonatomic,retain) NSMutableArray * routes;                                             //@synthesize routes=_routes - In the implementation block
@property (nonatomic,retain) NSMutableArray * posrs;                                              //@synthesize posrs=_posrs - In the implementation block
@property (nonatomic,retain) NSObject*<OS_nw_path_evaluator> ifBringupPathEvaluator;              //@synthesize ifBringupPathEvaluator=_ifBringupPathEvaluator - In the implementation block
@property (assign,nonatomic) NEVirtualInterface_sRef nevi;                                        //@synthesize nevi=_nevi - In the implementation block
@property (nonatomic,retain) NSString * addrStr;                                                  //@synthesize addrStr=_addrStr - In the implementation block
-(id)description;
-(id)init;
-(void)dealloc;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(NSMutableArray *)interfaces;
-(NSMutableArray *)sources;
-(NSMutableArray *)neighbors;
-(void)setNeighbors:(NSMutableArray *)arg1 ;
-(void)setSources:(NSMutableArray *)arg1 ;
-(NSMutableArray *)routes;
-(void)setRoutes:(NSMutableArray *)arg1 ;
-(void)setInterfaces:(NSMutableArray *)arg1 ;
-(NSString *)addrStr;
-(BOOL)purgeInterface:(id)arg1 ;
-(void)handlePacket:(const char*)arg1 length:(unsigned)arg2 remoteAddr:(const in6_addr*)arg3 localAddr:(const in6_addr*)arg4 babelInterface:(id)arg5 dtls:(BOOL)arg6 ;
-(void)sendImmediateRouteUpdateToNeighbor:(id)arg1 ;
-(void)updateRoutes;
-(id)createUpdateTLVsWithInterval:(unsigned short)arg1 ;
-(unsigned long long)routerID;
-(void)setRouterID:(unsigned long long)arg1 ;
-(unsigned short)nodeSeqno;
-(NSMutableArray *)posrs;
-(void)handleIfBringupPathUpdate:(id)arg1 ;
-(void)setupInterfaces;
-(void)setupAddress:(in6_addr*)arg1 ;
-(id)copyNeighborWithAddr:(const in6_addr*)arg1 babelInterface:(id)arg2 isNewNeighbor:(BOOL*)arg3 ;
-(id)copySourceWithPrefix:(id)arg1 routerID:(unsigned long long)arg2 ;
-(BOOL)isNewDistanceUnfeasibleForPrefix:(id)arg1 routerID:(unsigned long long)arg2 seqno:(unsigned short)arg3 metric:(unsigned short)arg4 ;
-(id)copyRouteWithPrefix:(id)arg1 neighbor:(id)arg2 ;
-(id)copyPendingOutgoingSeqnoReqWithPrefix:(id)arg1 routerID:(unsigned long long)arg2 isNewPOSR:(BOOL*)arg3 ;
-(void)handleAckReqFromAddr:(const in6_addr*)arg1 babelInterface:(id)arg2 nonce:(unsigned short)arg3 interval:(unsigned short)arg4 ;
-(void)handleHelloFromAddr:(const in6_addr*)arg1 babelInterface:(id)arg2 seqno:(unsigned short)arg3 interval:(unsigned short)arg4 personal:(BOOL)arg5 ;
-(void)handleIHUFromAddr:(const in6_addr*)arg1 babelInterface:(id)arg2 rxcost:(unsigned short)arg3 interval:(unsigned short)arg4 ;
-(BOOL)purgeAllRoutesFromNeighbor:(id)arg1 ;
-(BOOL)handleUpdateFromAddr:(const in6_addr*)arg1 ForPrefix:(const in6_addr*)arg2 plen:(unsigned char)arg3 nextHop:(const in6_addr*)arg4 babelInterface:(id)arg5 routerID:(unsigned long long)arg6 seqno:(unsigned short)arg7 interval:(unsigned short)arg8 metric:(unsigned short)arg9 ae:(unsigned char)arg10 ;
-(void)handleRouteReqFromAddr:(const in6_addr*)arg1 babelInterface:(id)arg2 ForPrefix:(const in6_addr*)arg3 plen:(unsigned char)arg4 ;
-(void)sendSeqnoReqIfNecessaryTo:(id)arg1 forPrefix:(id)arg2 routerID:(unsigned long long)arg3 seqno:(unsigned short)arg4 hopCount:(unsigned char)arg5 originator:(id)arg6 ;
-(void)handleSeqnoReqFromAddr:(const in6_addr*)arg1 babelInterface:(id)arg2 ForPrefix:(const in6_addr*)arg3 plen:(unsigned char)arg4 routerID:(unsigned long long)arg5 seqno:(unsigned short)arg6 hopCount:(unsigned char)arg7 ;
-(void)addRouterID:(unsigned long long)arg1 toTLVs:(id)arg2 ;
-(void)addUpdateForRoute:(id)arg1 interval:(unsigned short)arg2 toTLVs:(id)arg3 ;
-(id)createSelectedRoutesArrayForPrefix:(id)arg1 ;
-(void)updateFeasabilityDistanceForRoute:(id)arg1 ;
-(id)createUpdateTLVsForRoutes:(id)arg1 interval:(unsigned short)arg2 ;
-(id)createUpdateTLVsForRoutes:(id)arg1 ;
-(id)createUpdateTLVsForPrefix:(id)arg1 interval:(unsigned short)arg2 ;
-(id)createUpdateTLVsForPrefix:(id)arg1 ;
-(id)createUpdateTLVs;
-(void)sendImmediateRouteUpdateToAllNeighbors;
-(id)copyRouteString;
-(void)setNodeSeqno:(unsigned short)arg1 ;
-(void)setPosrs:(NSMutableArray *)arg1 ;
-(NSObject*<OS_nw_path_evaluator>)ifBringupPathEvaluator;
-(void)setIfBringupPathEvaluator:(NSObject*<OS_nw_path_evaluator>)arg1 ;
-(NEVirtualInterface_sRef)nevi;
-(void)setNevi:(NEVirtualInterface_sRef)arg1 ;
-(void)setAddrStr:(NSString *)arg1 ;
@end

