/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:37 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/gamed
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <gamed/GKCacheObject.h>

@interface GKPurgeableCacheObject : GKCacheObject
+(void)purgeFromManagedObjectContext:(id)arg1 level:(int)arg2 ;
-(BOOL)purgeable;
-(void)purge;
@end

