/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:37 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/gamed
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_semaphore;
@class GKThreadsafeDictionary, NSPredicate, NSObject;

@interface GKUniqueObjectIDLookup : NSObject {

	Class _objectClass;
	GKThreadsafeDictionary* _lookup;
	NSPredicate* _predicate;
	NSObject*<OS_dispatch_semaphore> _semaphore;
	int _valid;

}
-(void)dealloc;
-(id)initWithObjectClass:(Class)arg1 context:(id)arg2 predicate:(id)arg3 ;
-(void)_populateWithContext:(id)arg1 ;
-(id)initWithObjectClass:(Class)arg1 context:(id)arg2 ;
-(id)uniqueObjectsForKeys:(id)arg1 context:(id)arg2 newObject:(/*^block*/id)arg3 ;
-(id)insertObjectsForServerRepresentations:(id)arg1 context:(id)arg2 newObject:(/*^block*/id)arg3 ;
@end

