/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:23 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PodcastsTVTopShelfExtension/IMAMSMetricsEvent.h>

@interface IMPageAMSMetricsEvent : IMAMSMetricsEvent

@property (assign,nonatomic) double pageRenderTime; 
-(id)init;
-(double)timeIntervalFromMilliseconds:(id)arg1 ;
-(id)millisecondsFromTimeInterval:(double)arg1 ;
-(double)pageRenderTime;
-(void)setPageRenderTime:(double)arg1 ;
@end

