/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:18 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTEpisodeIdentifier.h>
@class NSString, NSNumber;


@protocol MTEpisodeIdentifier <MTPodcastIdentifier>
@property (nonatomic,readonly) NSString * episodeUUID; 
@property (nonatomic,readonly) NSString * episodeGUID; 
@property (nonatomic,readonly) NSNumber * episodeAdamID; 
@property (nonatomic,readonly) NSNumber * episodeSerpentID; 
@required
-(NSString *)episodeUUID;
-(NSString *)episodeGUID;
-(NSNumber *)episodeAdamID;
-(NSNumber *)episodeSerpentID;

@end

#import <Podcasts/MTPodcastIdentifier.h>

@class NSString, NSNumber;

@interface MTEpisodeIdentifier : NSObject <MTEpisodeIdentifier, MTPodcastIdentifier> {

	NSString* _episodeUUID;
	NSString* _episodeGUID;
	NSNumber* _episodeAdamID;
	NSNumber* _episodeSerpentID;
	NSString* _podcastUUID;
	NSNumber* _podcastAdamID;
	NSString* _currentPodcastFeedURL;
	NSString* _originalPodcastFeedURL;

}

@property (nonatomic,copy) NSString * episodeUUID;                         //@synthesize episodeUUID=_episodeUUID - In the implementation block
@property (nonatomic,copy) NSString * episodeGUID;                         //@synthesize episodeGUID=_episodeGUID - In the implementation block
@property (nonatomic,retain) NSNumber * episodeAdamID;                     //@synthesize episodeAdamID=_episodeAdamID - In the implementation block
@property (nonatomic,retain) NSNumber * episodeSerpentID;                  //@synthesize episodeSerpentID=_episodeSerpentID - In the implementation block
@property (nonatomic,copy) NSString * podcastUUID;                         //@synthesize podcastUUID=_podcastUUID - In the implementation block
@property (nonatomic,retain) NSNumber * podcastAdamID;                     //@synthesize podcastAdamID=_podcastAdamID - In the implementation block
@property (nonatomic,copy) NSString * currentPodcastFeedURL;               //@synthesize currentPodcastFeedURL=_currentPodcastFeedURL - In the implementation block
@property (nonatomic,copy) NSString * originalPodcastFeedURL;              //@synthesize originalPodcastFeedURL=_originalPodcastFeedURL - In the implementation block
+(id)identifierWithEpisode:(id)arg1 ;
+(id)identifierWithPlayerItem:(id)arg1 ;
-(id)initWithPlayerItem:(id)arg1 ;
-(NSString *)podcastUUID;
-(void)setPodcastUUID:(NSString *)arg1 ;
-(id)initWithEpisode:(id)arg1 ;
-(void)setEpisodeUUID:(NSString *)arg1 ;
-(void)setEpisodeGUID:(NSString *)arg1 ;
-(void)setEpisodeAdamID:(NSNumber *)arg1 ;
-(void)setEpisodeSerpentID:(NSNumber *)arg1 ;
-(void)_updateWithPodcast:(id)arg1 ;
-(void)setPodcastAdamID:(NSNumber *)arg1 ;
-(void)setCurrentPodcastFeedURL:(NSString *)arg1 ;
-(void)setOriginalPodcastFeedURL:(NSString *)arg1 ;
-(NSString *)currentPodcastFeedURL;
-(NSString *)originalPodcastFeedURL;
-(NSNumber *)podcastAdamID;
-(NSString *)episodeUUID;
-(NSString *)episodeGUID;
-(NSNumber *)episodeAdamID;
-(NSNumber *)episodeSerpentID;
-(BOOL)_hasFeedURL:(id)arg1 ;
@end

