/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:20 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKitCore/UIView.h>

@class NSMutableDictionary, NSArray, MTColorTheme;

@interface MTEpisodeStateView : UIView {

	NSMutableDictionary* _imageViewCache;
	NSArray* _imageViews;
	unsigned long long _icons;
	BOOL _needsIconUpdate;
	BOOL _needsSizeUpdate;
	BOOL _verticalLayout;
	BOOL _centeredLayout;
	MTColorTheme* _colorTheme;
	unsigned long long _playStatus;
	unsigned long long _assetStatus;

}

@property (nonatomic,retain) MTColorTheme * colorTheme;                                //@synthesize colorTheme=_colorTheme - In the implementation block
@property (assign,nonatomic) unsigned long long playStatus;                            //@synthesize playStatus=_playStatus - In the implementation block
@property (assign,nonatomic) unsigned long long assetStatus;                           //@synthesize assetStatus=_assetStatus - In the implementation block
@property (assign,setter=setExplicit:,nonatomic) BOOL isExplicit; 
@property (assign,getter=isSaved,nonatomic) BOOL saved; 
@property (assign,getter=isVideo,nonatomic) BOOL video; 
@property (assign,getter=isVerticalLayout,nonatomic) BOOL verticalLayout;              //@synthesize verticalLayout=_verticalLayout - In the implementation block
@property (assign,getter=isCenteredLayout,nonatomic) BOOL centeredLayout;              //@synthesize centeredLayout=_centeredLayout - In the implementation block
+(id)imageForIconKey:(id)arg1 theme:(id)arg2 ;
+(id)orderedIconKeys;
+(double)imagePadding;
+(id)explicitIcon;
+(id)videoIcon;
-(id)init;
-(BOOL)_error;
-(void)_setError:(BOOL)arg1 ;
-(BOOL)isVideo;
-(void)sizeToFit;
-(BOOL)_streaming;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(BOOL)_document;
-(void)setExplicit:(BOOL)arg1 ;
-(void)layoutSubviews;
-(BOOL)_airplaneMode;
-(BOOL)isSaved;
-(void)setColorTheme:(MTColorTheme *)arg1 ;
-(MTColorTheme *)colorTheme;
-(BOOL)isExplicit;
-(void)setVideo:(BOOL)arg1 ;
-(void)_updateImageViews;
-(id)_imageViews;
-(BOOL)_isRTL;
-(unsigned long long)assetStatus;
-(void)setSaved:(BOOL)arg1 ;
-(BOOL)isNotEmpty;
-(void)setVerticalLayout:(BOOL)arg1 ;
-(void)_setStreaming:(BOOL)arg1 ;
-(void)_setDocument:(BOOL)arg1 ;
-(void)_setAirplaneMode:(BOOL)arg1 ;
-(void)_setNeedsIconUpdate;
-(void)_setEnabled:(BOOL)arg1 forFlag:(unsigned long long)arg2 ;
-(id)_imageViewForKey:(id)arg1 ;
-(void)applyThemeToImageViewWithKey:(id)arg1 ;
-(void)_updateIconsIfNeeded;
-(BOOL)isVerticalLayout;
-(BOOL)isCenteredLayout;
-(void)updateSizeIfNeeded;
-(void)setCenteredLayout:(BOOL)arg1 ;
-(void)setAssetStatus:(unsigned long long)arg1 ;
-(void)setPlayStatus:(unsigned long long)arg1 ;
-(id)imagesForCurrentIconsExcludingPlayState;
-(unsigned long long)playStatus;
@end

