/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:21 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKitCore/UIView.h>
#import <Podcasts/MTReachabilityObserver.h>

@protocol MTEpisodeLockupDelegate;
@class NSMutableDictionary, MTEpisode, MTTVEpisodeActionController, MTColorTheme, MTTouchInsetsButton, UIImage, NSOperation, IMActionSheetAction, MTNowPlayingIndicatorView, UITextView, UILabel, MTEpisodeArtworkView, UIImageView, MTEpisodeStateView, UIButton, NSString;

@interface MTEpisodeLockup : UIView <MTReachabilityObserver> {

	BOOL _initialized;
	NSMutableDictionary* _sizeCache;
	CGSize _descriptionSize;
	BOOL _editing;
	BOOL _expanded;
	BOOL _currentPlayerItem;
	BOOL _shouldShowNowPlaying;
	BOOL _showsPubDate;
	BOOL _showsPlayState;
	BOOL _showsDescriptionButton;
	BOOL _showsFooterTextView;
	BOOL _showsExplicitIcon;
	BOOL _showsStreamingIcon;
	BOOL _showsDocumentIcon;
	BOOL _showsErrorIcon;
	BOOL _showsAirplaneModeIcon;
	BOOL _showsArtwork;
	BOOL _showsMoreButton;
	MTEpisode* _episode;
	id<MTEpisodeLockupDelegate> _delegate;
	MTTVEpisodeActionController* _actionController;
	MTColorTheme* _colorTheme;
	unsigned long long _style;
	MTTouchInsetsButton* _moreButton;
	MTTouchInsetsButton* _descriptionButton;
	UIImage* _titleImage;
	NSOperation* _imageLoadingOperation;
	IMActionSheetAction* _moreAction;
	MTNowPlayingIndicatorView* _barsView;
	UITextView* _titleTextView;
	UILabel* _metadataLabel;
	UITextView* _descriptionTextView;
	UITextView* _footerTextView;
	MTEpisodeArtworkView* _artworkView;
	UIImageView* _playStatusView;
	UIImageView* _explicitIconView;
	MTEpisodeStateView* _iconView;
	MTEpisodeStateView* _buttonView;
	unsigned long long _disabledReason;
	UIEdgeInsets __layoutMargins;

}

@property (assign,nonatomic) UIEdgeInsets _layoutMargins;                                    //@synthesize _layoutMargins=__layoutMargins - In the implementation block
@property (nonatomic,retain) MTTouchInsetsButton * moreButton;                               //@synthesize moreButton=_moreButton - In the implementation block
@property (nonatomic,retain) MTTouchInsetsButton * descriptionButton;                        //@synthesize descriptionButton=_descriptionButton - In the implementation block
@property (nonatomic,retain) UIImage * titleImage;                                           //@synthesize titleImage=_titleImage - In the implementation block
@property (nonatomic,retain) NSOperation * imageLoadingOperation;                            //@synthesize imageLoadingOperation=_imageLoadingOperation - In the implementation block
@property (assign,nonatomic) BOOL showsDescriptionButton;                                    //@synthesize showsDescriptionButton=_showsDescriptionButton - In the implementation block
@property (assign,nonatomic) BOOL showsFooterTextView;                                       //@synthesize showsFooterTextView=_showsFooterTextView - In the implementation block
@property (assign,nonatomic) BOOL showsExplicitIcon;                                         //@synthesize showsExplicitIcon=_showsExplicitIcon - In the implementation block
@property (assign,nonatomic) BOOL showsStreamingIcon;                                        //@synthesize showsStreamingIcon=_showsStreamingIcon - In the implementation block
@property (assign,nonatomic) BOOL showsDocumentIcon;                                         //@synthesize showsDocumentIcon=_showsDocumentIcon - In the implementation block
@property (assign,nonatomic) BOOL showsErrorIcon;                                            //@synthesize showsErrorIcon=_showsErrorIcon - In the implementation block
@property (assign,nonatomic) BOOL showsAirplaneModeIcon;                                     //@synthesize showsAirplaneModeIcon=_showsAirplaneModeIcon - In the implementation block
@property (nonatomic,readonly) UIButton * actionButton; 
@property (nonatomic,retain) IMActionSheetAction * moreAction;                               //@synthesize moreAction=_moreAction - In the implementation block
@property (nonatomic,retain) MTNowPlayingIndicatorView * barsView;                           //@synthesize barsView=_barsView - In the implementation block
@property (nonatomic,retain) UITextView * titleTextView;                                     //@synthesize titleTextView=_titleTextView - In the implementation block
@property (nonatomic,retain) UILabel * metadataLabel;                                        //@synthesize metadataLabel=_metadataLabel - In the implementation block
@property (nonatomic,retain) UITextView * descriptionTextView;                               //@synthesize descriptionTextView=_descriptionTextView - In the implementation block
@property (nonatomic,retain) UITextView * footerTextView;                                    //@synthesize footerTextView=_footerTextView - In the implementation block
@property (nonatomic,retain) MTEpisodeArtworkView * artworkView;                             //@synthesize artworkView=_artworkView - In the implementation block
@property (nonatomic,retain) UIImageView * playStatusView;                                   //@synthesize playStatusView=_playStatusView - In the implementation block
@property (nonatomic,retain) UIImageView * explicitIconView;                                 //@synthesize explicitIconView=_explicitIconView - In the implementation block
@property (nonatomic,retain) MTEpisodeStateView * iconView;                                  //@synthesize iconView=_iconView - In the implementation block
@property (nonatomic,retain) MTEpisodeStateView * buttonView;                                //@synthesize buttonView=_buttonView - In the implementation block
@property (assign,nonatomic) unsigned long long disabledReason;                              //@synthesize disabledReason=_disabledReason - In the implementation block
@property (assign,nonatomic) BOOL showsArtwork;                                              //@synthesize showsArtwork=_showsArtwork - In the implementation block
@property (assign,nonatomic) BOOL showsMoreButton;                                           //@synthesize showsMoreButton=_showsMoreButton - In the implementation block
@property (nonatomic,retain) MTEpisode * episode;                                            //@synthesize episode=_episode - In the implementation block
@property (assign,nonatomic,__weak) id<MTEpisodeLockupDelegate> delegate;                    //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) MTTVEpisodeActionController * actionController;                 //@synthesize actionController=_actionController - In the implementation block
@property (assign,getter=isEditing,nonatomic) BOOL editing;                                  //@synthesize editing=_editing - In the implementation block
@property (assign,getter=isExpanded,nonatomic) BOOL expanded;                                //@synthesize expanded=_expanded - In the implementation block
@property (assign,getter=isCurrentPlayerItem,nonatomic) BOOL currentPlayerItem;              //@synthesize currentPlayerItem=_currentPlayerItem - In the implementation block
@property (assign,nonatomic) BOOL shouldShowNowPlaying;                                      //@synthesize shouldShowNowPlaying=_shouldShowNowPlaying - In the implementation block
@property (nonatomic,retain) MTColorTheme * colorTheme;                                      //@synthesize colorTheme=_colorTheme - In the implementation block
@property (assign,nonatomic) unsigned long long style;                                       //@synthesize style=_style - In the implementation block
@property (assign,nonatomic) BOOL showsPubDate;                                              //@synthesize showsPubDate=_showsPubDate - In the implementation block
@property (assign,nonatomic) BOOL showsPlayState;                                            //@synthesize showsPlayState=_showsPlayState - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)titleFont;
+(id)titleTextStyle;
+(id)dependentPropertyKeys;
+(unsigned long long)styleForWidth:(double)arg1 showsArtwork:(BOOL)arg2 ;
+(CGSize)artworkSizeForStyle:(unsigned long long)arg1 ;
+(double)estimatedHeightForWidth:(double)arg1 style:(unsigned long long)arg2 ;
+(BOOL)useSelfSizingCells;
+(double)maximumContentWidthForStyle:(unsigned long long)arg1 ;
+(id)descriptionFont;
+(double)estimatedHeightForWidth:(double)arg1 showsArtwork:(BOOL)arg2 ;
+(id)mockEpisode;
+(BOOL)useLayoutForSkinnyPhones;
+(double)maximumContentWidthForStyle:(unsigned long long)arg1 showsPlayState:(BOOL)arg2 ;
+(BOOL)showsArtworkForStyle:(unsigned long long)arg1 ;
+(id)descriptionTextStyle;
+(unsigned long long)titleNumberOfLinesForStyle:(unsigned long long)arg1 ;
+(unsigned long long)descriptionNumberOfLinesForStyle:(unsigned long long)arg1 isTitleMultipleLines:(BOOL)arg2 ;
+(double)artworkHeightForStyle:(unsigned long long)arg1 sizeType:(unsigned long long)arg2 ;
+(id)defaultArtworkWithSize:(CGSize)arg1 ;
+(id)footerTextStyle;
+(id)metadataHeaderFont;
+(id)metadataFooterFont;
+(id)defaultArtworkForStyle:(unsigned long long)arg1 ;
+(double)leadingMarginForViewWidth:(double)arg1 ;
+(double)descriptionMaxHeightForCurrentOrientation;
+(CGRect)frameForContentViewSize:(CGSize)arg1 style:(unsigned long long)arg2 ;
-(void)dealloc;
-(id<MTEpisodeLockupDelegate>)delegate;
-(void)setDelegate:(id<MTEpisodeLockupDelegate>)arg1 ;
-(unsigned long long)style;
-(void)setStyle:(unsigned long long)arg1 ;
-(void)setFrame:(CGRect)arg1 ;
-(void)prepareForReuse;
-(BOOL)isEditing;
-(void)update;
-(void)setBounds:(CGRect)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setEditing:(BOOL)arg1 ;
-(MTEpisode *)episode;
-(MTEpisodeStateView *)buttonView;
-(void)setButtonView:(MTEpisodeStateView *)arg1 ;
-(UIImage *)titleImage;
-(void)setTitleImage:(UIImage *)arg1 ;
-(UIButton *)actionButton;
-(void)layoutSubviews;
-(void)setExpanded:(BOOL)arg1 ;
-(BOOL)isExpanded;
-(void)layoutMarginsDidChange;
-(void)contentSizeCategoryDidChange:(id)arg1 ;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)setColorTheme:(MTColorTheme *)arg1 ;
-(MTColorTheme *)colorTheme;
-(MTEpisodeStateView *)iconView;
-(void)setEpisode:(MTEpisode *)arg1 ;
-(void)setIconView:(MTEpisodeStateView *)arg1 ;
-(UIEdgeInsets)_layoutMargins;
-(void)setCurrentPlayerItem:(BOOL)arg1 ;
-(void)invalidateLayoutMargins;
-(BOOL)_isRTL;
-(MTTVEpisodeActionController *)actionController;
-(MTEpisodeArtworkView *)artworkView;
-(void)updateColors;
-(UITextView *)descriptionTextView;
-(void)setDescriptionTextView:(UITextView *)arg1 ;
-(void)setArtworkView:(MTEpisodeArtworkView *)arg1 ;
-(void)reachabilityChangedFrom:(BOOL)arg1 to:(BOOL)arg2 ;
-(MTTouchInsetsButton *)moreButton;
-(void)moreButtonTapped:(id)arg1 ;
-(void)setMoreButton:(MTTouchInsetsButton *)arg1 ;
-(id)_currentTitleColor;
-(void)configureSubviews;
-(void)setShowsArtwork:(BOOL)arg1 ;
-(BOOL)isCurrentPlayerItem;
-(MTNowPlayingIndicatorView *)barsView;
-(void)startObservingPlaybackState;
-(void)stopObservingPlaybackState;
-(void)setBarsView:(MTNowPlayingIndicatorView *)arg1 ;
-(BOOL)showsArtwork;
-(void)setShowsPlayState:(BOOL)arg1 ;
-(UILabel *)metadataLabel;
-(UIImageView *)explicitIconView;
-(UIImageView *)playStatusView;
-(BOOL)showsPlayState;
-(void)setMetadataLabel:(UILabel *)arg1 ;
-(void)setExplicitIconView:(UIImageView *)arg1 ;
-(void)set_layoutMargins:(UIEdgeInsets)arg1 ;
-(void)dismissActionSheetsAndPopovers;
-(void)updateActionSheetsAndPopovers;
-(void)fixEmptyTextContainers;
-(UIEdgeInsets)_layoutMarginsForViewWidth:(double)arg1 ;
-(IMActionSheetAction *)moreAction;
-(void)setActionController:(MTTVEpisodeActionController *)arg1 ;
-(void)updateMetadataText;
-(void)updateDescriptionText;
-(BOOL)shouldShowNowPlaying;
-(void)setShouldShowNowPlaying:(BOOL)arg1 ;
-(void)setShowsMoreButton:(BOOL)arg1 ;
-(void)setShowsPubDate:(BOOL)arg1 ;
-(BOOL)showsPubDate;
-(void)invalidateSizeMetrics;
-(void)airplaneModeChanged:(id)arg1 ;
-(UITextView *)titleTextView;
-(UITextView *)footerTextView;
-(void)descriptionButtonTapped:(id)arg1 ;
-(void)updateColorsForBarsView:(id)arg1 ;
-(MTTouchInsetsButton *)descriptionButton;
-(void)updatePlayStatusIcons;
-(BOOL)updateDisabledReason;
-(void)updateIcons;
-(BOOL)showsMoreButton;
-(unsigned long long)disabledReason;
-(void)updateMoreButtonVisibility;
-(void)updateIconView;
-(void)_setNumberOfLinesForDescription:(unsigned long long)arg1 ;
-(void)updateFooterTextViewVisbility;
-(BOOL)updateTitleFontIfNeeded;
-(void)setDisabledReason:(unsigned long long)arg1 ;
-(CGRect)artworkFrameForStyle:(unsigned long long)arg1 forViewWidth:(double)arg2 ;
-(double)titleOriginYForArtworkFrame:(CGRect)arg1 style:(unsigned long long)arg2 ;
-(CGRect)actionButtonFrameForViewWidth:(double)arg1 titleOriginY:(double)arg2 ;
-(CGRect)downloadButtonFrameForActionButtonFrame:(CGRect)arg1 titleOriginY:(double)arg2 ;
-(CGRect)buttonsFrameForActionButtonFrame:(CGRect)arg1 downloadButtonFrame:(CGRect)arg2 ;
-(double)titleOriginXForViewWidth:(double)arg1 artworkFrame:(CGRect)arg2 buttonFrame:(CGRect)arg3 style:(unsigned long long)arg4 ;
-(CGSize)titleSizeForViewWidth:(double)arg1 titleOrigin:(CGPoint)arg2 artworkFrame:(CGRect)arg3 buttonViewFrame:(CGRect)arg4 style:(unsigned long long)arg5 ;
-(CGRect)playStatusViewFrameForViewWidth:(double)arg1 titleFrame:(CGRect)arg2 artworkFrame:(CGRect)arg3 ;
-(CGRect)metadataFrameForViewWidth:(double)arg1 titleFrame:(CGRect)arg2 style:(unsigned long long)arg3 ;
-(CGRect)iconsViewFrameForViewWidth:(double)arg1 titleFrame:(CGRect)arg2 metadataFrame:(CGRect*)arg3 style:(unsigned long long)arg4 ;
-(CGPoint)descriptionOriginForViewWidth:(double)arg1 artworkFrame:(CGRect)arg2 buttonViewFrame:(CGRect)arg3 titleFrame:(CGRect)arg4 metadataFrame:(CGRect)arg5 iconViewFrame:(CGRect)arg6 style:(unsigned long long)arg7 ;
-(CGSize)exactDescriptionSizeForOrigin:(CGPoint)arg1 viewWidth:(double)arg2 titleFrame:(CGRect)arg3 actionButtonFrame:(CGRect)arg4 downloadButtonFrame:(CGRect)arg5 style:(unsigned long long)arg6 ;
-(CGRect)moreButtonFrameForDescriptionFrame:(CGRect)arg1 ;
-(CGRect)descriptionButtonFrameForDescriptionFrame:(CGRect)arg1 ;
-(BOOL)showsDescriptionButton;
-(BOOL)showsFooterTextView;
-(CGRect)footerFrameForDescriptionButtonFrame:(CGRect)arg1 descriptionFrame:(CGRect)arg2 ;
-(double)heightForWidth:(double)arg1 style:(unsigned long long)arg2 ;
-(id)titleExclusionPathsForButtonViewFrame:(CGRect)arg1 ;
-(id)_currentTitleFont;
-(double)descriptionWidthForViewWidth:(double)arg1 titleFrame:(CGRect)arg2 style:(unsigned long long)arg3 ;
-(BOOL)isLabelMultipleLinesWithFrame:(CGRect)arg1 font:(id)arg2 ;
-(id)descriptionExclusionPathsForOrigin:(CGPoint)arg1 descriptionWidth:(double)arg2 buttonsFrame:(CGRect)arg3 titleFrame:(CGRect)arg4 ;
-(void)setShowsDescriptionButton:(BOOL)arg1 ;
-(void)updateTitleIncludingIcons;
-(void)beginLoadingArtwork;
-(id)_currentDescriptionColor;
-(void)updateFooterText;
-(void)setShowsFooterTextView:(BOOL)arg1 ;
-(void)setShowsExplicitIcon:(BOOL)arg1 ;
-(BOOL)updateIsCurrentPlayerItemState;
-(CGRect)explicitIconFrameForViewWidth:(double)arg1 titleFrame:(CGRect)arg2 ;
-(id)titleExclusionPathsForExplicitIconFrame:(CGRect)arg1 viewWidth:(double)arg2 ;
-(void)playbackStateDidChange;
-(void)updateStateForBarsView:(id)arg1 ;
-(void)updateAssetStatusIcons;
-(id)_currentDescriptionFont;
-(void)setDescriptionButton:(MTTouchInsetsButton *)arg1 ;
-(NSOperation *)imageLoadingOperation;
-(void)setImageLoadingOperation:(NSOperation *)arg1 ;
-(BOOL)showsExplicitIcon;
-(BOOL)showsStreamingIcon;
-(void)setShowsStreamingIcon:(BOOL)arg1 ;
-(BOOL)showsDocumentIcon;
-(void)setShowsDocumentIcon:(BOOL)arg1 ;
-(BOOL)showsErrorIcon;
-(void)setShowsErrorIcon:(BOOL)arg1 ;
-(BOOL)showsAirplaneModeIcon;
-(void)setShowsAirplaneModeIcon:(BOOL)arg1 ;
-(void)setMoreAction:(IMActionSheetAction *)arg1 ;
-(void)setTitleTextView:(UITextView *)arg1 ;
-(void)setFooterTextView:(UITextView *)arg1 ;
-(void)setPlayStatusView:(UIImageView *)arg1 ;
@end

