/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:18 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/MTTableViewCell.h>
#import <Podcasts/MTCellProtocol.h>

@class UIView, MTArtworkView, MTLabelStackView, NSString;

@interface MTGenericCell : MTTableViewCell <MTCellProtocol> {

	BOOL _hidesSideViewWhenEditing;
	BOOL _sideViewHidden;
	BOOL _showsArtwork;
	UIView* _sideView;
	MTArtworkView* _artworkView;
	MTLabelStackView* _textStackView;

}

@property (nonatomic,retain) MTArtworkView * artworkView;                                                          //@synthesize artworkView=_artworkView - In the implementation block
@property (nonatomic,retain) MTLabelStackView * textStackView;                                                     //@synthesize textStackView=_textStackView - In the implementation block
@property (assign,setter=_setSideViewHidden:,getter=_isSideViewHidden,nonatomic) BOOL sideViewHidden;              //@synthesize sideViewHidden=_sideViewHidden - In the implementation block
@property (assign,nonatomic) BOOL showsArtwork;                                                                    //@synthesize showsArtwork=_showsArtwork - In the implementation block
@property (nonatomic,retain) NSString * title; 
@property (nonatomic,retain) NSString * subtitle; 
@property (nonatomic,retain) NSString * artworkKey; 
@property (nonatomic,retain) UIView * sideView;                                                                    //@synthesize sideView=_sideView - In the implementation block
@property (assign,nonatomic) BOOL hidesSideViewWhenEditing;                                                        //@synthesize hidesSideViewWhenEditing=_hidesSideViewWhenEditing - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(double)maxHeight;
+(double)heightForWidth:(double)arg1 ;
+(id)reuseIdentifier;
+(BOOL)showsArtwork;
+(CGSize)artworkSizeForViewWidth:(double)arg1 ;
+(Class)textStackViewClass;
-(void)setEnabled:(BOOL)arg1 ;
-(NSString *)title;
-(void)setTitle:(NSString *)arg1 ;
-(void)prepareForReuse;
-(void)setSubtitle:(NSString *)arg1 ;
-(NSString *)subtitle;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)layoutSubviews;
-(void)updateFonts;
-(MTArtworkView *)artworkView;
-(void)updateColors;
-(void)setArtworkView:(MTArtworkView *)arg1 ;
-(void)willTransitionToState:(unsigned long long)arg1 ;
-(void)configureSubviews;
-(void)setShowsArtwork:(BOOL)arg1 ;
-(NSString *)artworkKey;
-(void)setArtworkKey:(NSString *)arg1 ;
-(BOOL)showsArtwork;
-(MTLabelStackView *)textStackView;
-(BOOL)hidesSideViewWhenEditing;
-(void)_updateSideViewHiddenForCurrentState;
-(CGRect)artworkFrameForContentViewSize:(CGSize)arg1 ;
-(CGRect)sideViewFrameForContentViewSize:(CGSize)arg1 ;
-(BOOL)_isSideViewHidden;
-(UIView *)sideView;
-(CGRect)textStackFrameForContentViewSize:(CGSize)arg1 artworkFrame:(CGRect)arg2 sideViewFrame:(CGRect)arg3 ;
-(void)_updateSideViewHiddenForState:(unsigned long long)arg1 ;
-(double)textViewMinXForArtworkFrame:(CGRect)arg1 sideViewFrame:(CGRect)arg2 ;
-(double)textViewMaxXForArtworkFrame:(CGRect)arg1 sideViewFrame:(CGRect)arg2 ;
-(void)_setSideViewHidden:(BOOL)arg1 ;
-(void)updateWithObject:(id)arg1 ;
-(void)setHidesSideViewWhenEditing:(BOOL)arg1 ;
-(void)setSideView:(UIView *)arg1 ;
-(void)setTextStackView:(MTLabelStackView *)arg1 ;
@end

