/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:21 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIViewController.h>

@class MTPlaylist, UIImageView;

@interface MTTVStationPlaceholderViewController : UIViewController {

	MTPlaylist* _station;
	UIImageView* _imageView;

}

@property (nonatomic,retain) UIImageView * imageView;              //@synthesize imageView=_imageView - In the implementation block
@property (nonatomic,retain) MTPlaylist * station;                 //@synthesize station=_station - In the implementation block
-(void)_update;
-(MTPlaylist *)station;
-(void)loadView;
-(void)setStation:(MTPlaylist *)arg1 ;
-(UIImageView *)imageView;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidLayoutSubviews;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)setImageView:(UIImageView *)arg1 ;
-(void)_updateColors;
-(id)initWithStation:(id)arg1 ;
-(id)_fetchArtwork;
-(BOOL)_isDarkBackground;
@end

