/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:22 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKitCore/UIView.h>

@class UIColor, UIImageView, TVMTMusicBarsView, UIImage;

@interface MTTVEpisodePlayStatusView : UIView {

	BOOL _currentPlayerItem;
	BOOL _barsFillBounds;
	UIColor* _barsTintColor;
	UIImageView* _dotView;
	TVMTMusicBarsView* _barsView;

}

@property (nonatomic,retain) UIImageView * dotView;                                          //@synthesize dotView=_dotView - In the implementation block
@property (nonatomic,retain) TVMTMusicBarsView * barsView;                                   //@synthesize barsView=_barsView - In the implementation block
@property (assign,nonatomic) UIImage * image; 
@property (assign,getter=isCurrentPlayerItem,nonatomic) BOOL currentPlayerItem;              //@synthesize currentPlayerItem=_currentPlayerItem - In the implementation block
@property (nonatomic,retain) UIColor * barsTintColor;                                        //@synthesize barsTintColor=_barsTintColor - In the implementation block
@property (assign,nonatomic) unsigned long long barsStyle; 
@property (assign,nonatomic) BOOL barsFillBounds;                                            //@synthesize barsFillBounds=_barsFillBounds - In the implementation block
-(id)init;
-(void)dealloc;
-(void)_unregisterForNotifications;
-(UIImage *)image;
-(void)setImage:(UIImage *)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)layoutSubviews;
-(void)_registerForNotifications;
-(void)didMoveToWindow;
-(void)setCurrentPlayerItem:(BOOL)arg1 ;
-(void)setDotView:(UIImageView *)arg1 ;
-(UIImageView *)dotView;
-(BOOL)isCurrentPlayerItem;
-(TVMTMusicBarsView *)barsView;
-(void)updatePlaybackState;
-(void)setBarsView:(TVMTMusicBarsView *)arg1 ;
-(void)setBarsStyle:(unsigned long long)arg1 ;
-(BOOL)barsFillBounds;
-(void)setBarsTintColor:(UIColor *)arg1 ;
-(void)setBarsFillBounds:(BOOL)arg1 ;
-(unsigned long long)barsStyle;
-(UIColor *)barsTintColor;
@end

