/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:21 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIViewController.h>

@class MTPodcast, UIImageView, TVMTExpandingTextView;

@interface MTTVPodcastInfoViewController : UIViewController {

	MTPodcast* _podcast;
	UIImageView* _artworkView;
	TVMTExpandingTextView* _descriptionView;

}

@property (nonatomic,retain) UIImageView * artworkView;                            //@synthesize artworkView=_artworkView - In the implementation block
@property (nonatomic,retain) TVMTExpandingTextView * descriptionView;              //@synthesize descriptionView=_descriptionView - In the implementation block
@property (nonatomic,retain) MTPodcast * podcast;                                  //@synthesize podcast=_podcast - In the implementation block
-(void)_update;
-(void)loadView;
-(MTPodcast *)podcast;
-(void)viewDidLayoutSubviews;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)setPodcast:(MTPodcast *)arg1 ;
-(void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2 ;
-(void)_updateColors;
-(UIImageView *)artworkView;
-(TVMTExpandingTextView *)descriptionView;
-(void)setDescriptionView:(TVMTExpandingTextView *)arg1 ;
-(void)setArtworkView:(UIImageView *)arg1 ;
-(id)_fetchArtwork;
-(id)initWithPodcast:(id)arg1 ;
-(id)_fetchDescription;
-(void)updateDescriptionTextColor;
@end

