/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:51 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/securityd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <securityd/CKKSSQLDatabaseObject.h>

@class NSString, NSData, NSDate, CKKSRateLimiter, CKServerChangeToken;

@interface CKKSZoneStateEntry : CKKSSQLDatabaseObject {

	BOOL _ckzonecreated;
	BOOL _ckzonesubscribed;
	NSString* _ckzone;
	NSData* _encodedChangeToken;
	NSDate* _lastFetchTime;
	unsigned long long _lastFixup;
	CKKSRateLimiter* _rateLimiter;

}

@property (retain) NSString * ckzone;                                                                           //@synthesize ckzone=_ckzone - In the implementation block
@property (assign) BOOL ckzonecreated;                                                                          //@synthesize ckzonecreated=_ckzonecreated - In the implementation block
@property (assign) BOOL ckzonesubscribed;                                                                       //@synthesize ckzonesubscribed=_ckzonesubscribed - In the implementation block
@property (setter=setChangeToken:,getter=getChangeToken,retain) CKServerChangeToken * changeToken; 
@property (retain) NSData * encodedChangeToken;                                                                 //@synthesize encodedChangeToken=_encodedChangeToken - In the implementation block
@property (retain) NSDate * lastFetchTime;                                                                      //@synthesize lastFetchTime=_lastFetchTime - In the implementation block
@property (assign) unsigned long long lastFixup;                                                                //@synthesize lastFixup=_lastFixup - In the implementation block
@property (retain) CKKSRateLimiter * rateLimiter;                                                               //@synthesize rateLimiter=_rateLimiter - In the implementation block
@property (retain) NSData * encodedRateLimiter; 
+(id)sqlTable;
+(id)fromDatabaseRow:(id)arg1 ;
+(id)sqlColumns;
+(id)state:(id)arg1 ;
+(id)fromDatabase:(id)arg1 error:(id*)arg2 ;
+(id)tryFromDatabase:(id)arg1 error:(id*)arg2 ;
-(id)sqlValues;
-(id)whereClauseToFindSelf;
-(id)initWithCKZone:(id)arg1 zoneCreated:(BOOL)arg2 zoneSubscribed:(BOOL)arg3 changeToken:(id)arg4 lastFetch:(id)arg5 lastFixup:(unsigned long long)arg6 encodedRateLimiter:(id)arg7 ;
-(id)getChangeToken;
-(NSData *)encodedRateLimiter;
-(void)setEncodedRateLimiter:(NSData *)arg1 ;
-(NSString *)ckzone;
-(void)setCkzone:(NSString *)arg1 ;
-(BOOL)ckzonecreated;
-(void)setCkzonecreated:(BOOL)arg1 ;
-(BOOL)ckzonesubscribed;
-(void)setCkzonesubscribed:(BOOL)arg1 ;
-(NSData *)encodedChangeToken;
-(void)setEncodedChangeToken:(NSData *)arg1 ;
-(NSDate *)lastFetchTime;
-(void)setLastFetchTime:(NSDate *)arg1 ;
-(unsigned long long)lastFixup;
-(void)setLastFixup:(unsigned long long)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(CKKSRateLimiter *)rateLimiter;
-(void)setRateLimiter:(CKKSRateLimiter *)arg1 ;
-(void)setChangeToken:(CKServerChangeToken *)arg1 ;
@end

