/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:51 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/securityd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CKKSSelfPeer;
@class NSSet;

@interface CKKSSelves : NSObject {

	id<CKKSSelfPeer> _currentSelf;
	NSSet* _allSelves;

}

@property (retain) id<CKKSSelfPeer> currentSelf;              //@synthesize currentSelf=_currentSelf - In the implementation block
@property (retain) NSSet * allSelves;                         //@synthesize allSelves=_allSelves - In the implementation block
-(id)description;
-(id)initWithCurrent:(id)arg1 allSelves:(id)arg2 ;
-(id<CKKSSelfPeer>)currentSelf;
-(void)setCurrentSelf:(id<CKKSSelfPeer>)arg1 ;
-(NSSet *)allSelves;
-(void)setAllSelves:(NSSet *)arg1 ;
@end

