/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:50 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/securityd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <securityd/securityd-Structs.h>
#import <securityd/NSCopying.h>

@class NSDictionary;

@interface CKKSSQLDatabaseObject : NSObject <NSCopying> {

	NSDictionary* _originalSelfWhereClause;

}

@property (copy) NSDictionary * originalSelfWhereClause;              //@synthesize originalSelfWhereClause=_originalSelfWhereClause - In the implementation block
+(BOOL)deleteFromTable:(id)arg1 where:(id)arg2 connection:(OpaqueSecDbConnectionRef)arg3 error:(id*)arg4 ;
+(id)sqlTable;
+(BOOL)saveToDatabaseTable:(id)arg1 row:(id)arg2 connection:(OpaqueSecDbConnectionRef)arg3 error:(id*)arg4 ;
+(id)makeWhereClause:(id)arg1 ;
+(id)groupByClause:(id)arg1 ;
+(id)orderByClause:(id)arg1 ;
+(BOOL)queryDatabaseTable:(id)arg1 where:(id)arg2 columns:(id)arg3 groupBy:(id)arg4 orderBy:(id)arg5 limit:(long long)arg6 processRow:(/*^block*/id)arg7 error:(id*)arg8 ;
+(BOOL)queryMaxValueForField:(id)arg1 inTable:(id)arg2 where:(id)arg3 columns:(id)arg4 processRow:(/*^block*/id)arg5 ;
+(id)fromDatabaseWhere:(id)arg1 error:(id*)arg2 ;
+(id)tryFromDatabaseWhere:(id)arg1 error:(id*)arg2 ;
+(id)allWhere:(id)arg1 error:(id*)arg2 ;
+(id)fetch:(unsigned long long)arg1 error:(id*)arg2 ;
+(id)fetch:(unsigned long long)arg1 where:(id)arg2 error:(id*)arg3 ;
+(id)fetch:(unsigned long long)arg1 where:(id)arg2 orderBy:(id)arg3 error:(id*)arg4 ;
+(id)fromDatabaseRow:(id)arg1 ;
+(id)sqlColumns;
+(id)allUUIDs:(id)arg1 error:(id*)arg2 ;
+(id)all:(id)arg1 error:(id*)arg2 ;
+(BOOL)deleteAll:(id)arg1 error:(id*)arg2 ;
+(id)all:(id*)arg1 ;
+(id)quotedString:(id)arg1 ;
+(BOOL)deleteAll:(id*)arg1 ;
-(BOOL)saveToDatabase:(id*)arg1 ;
-(BOOL)saveToDatabaseWithConnection:(OpaqueSecDbConnectionRef)arg1 error:(id*)arg2 ;
-(BOOL)deleteFromDatabase:(id*)arg1 ;
-(id)memoizeOriginalSelfWhereClause;
-(id)sqlValues;
-(id)whereClauseToFindSelf;
-(NSDictionary *)originalSelfWhereClause;
-(void)setOriginalSelfWhereClause:(NSDictionary *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

