/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:53 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/securityd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface KeychainItem : NSObject {

	NSString* _accessGroup;

}

@property (retain) NSString * accessGroup;              //@synthesize accessGroup=_accessGroup - In the implementation block
-(NSString *)accessGroup;
-(void)setAccessGroup:(NSString *)arg1 ;
-(id)initWithAccessGroup:(id)arg1 ;
@end

