/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:52 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/securityd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <securityd/securityd-Structs.h>
#import <securityd/CKKSResultOperation.h>
#import <securityd/OctagonStateTransitionOperationProtocol.h>

@interface OctagonStateTransitionOperation : CKKSResultOperation <OctagonStateTransitionOperationProtocol> {

	NSString* _nextState;
	NSString* _intendedState;

}

@property (retain) NSString*<OctagonStateString> nextState;                    //@synthesize nextState=_nextState - In the implementation block
@property (readonly) NSString*<OctagonStateString> intendedState;              //@synthesize intendedState=_intendedState - In the implementation block
+(id)named:(id)arg1 entering:(NSString*)arg2 ;
+(id)named:(id)arg1 intending:(NSString*)arg2 errorState:(NSString*)arg3 timeout:(unsigned long long)arg4 withBlockTakingSelf:(/*^block*/id)arg5 ;
-(NSString*<OctagonStateString>)intendedState;
-(id)initIntending:(NSString*)arg1 errorState:(NSString*)arg2 ;
-(id)description;
-(NSString*<OctagonStateString>)nextState;
-(void)setNextState:(NSString*<OctagonStateString>)arg1 ;
@end

