/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:53 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/securityd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface OTDeviceInformation : NSObject {

	NSString* _containerName;
	NSString* _contextID;
	unsigned long long _epoch;
	NSString* _machineID;
	NSString* _modelID;
	NSString* _deviceName;
	NSString* _serialNumber;
	NSString* _osVersion;

}

@property (retain) NSString * containerName;              //@synthesize containerName=_containerName - In the implementation block
@property (retain) NSString * contextID;                  //@synthesize contextID=_contextID - In the implementation block
@property (assign) unsigned long long epoch;              //@synthesize epoch=_epoch - In the implementation block
@property (retain) NSString * machineID;                  //@synthesize machineID=_machineID - In the implementation block
@property (retain) NSString * modelID;                    //@synthesize modelID=_modelID - In the implementation block
@property (retain) NSString * deviceName;                 //@synthesize deviceName=_deviceName - In the implementation block
@property (retain) NSString * serialNumber;               //@synthesize serialNumber=_serialNumber - In the implementation block
@property (retain) NSString * osVersion;                  //@synthesize osVersion=_osVersion - In the implementation block
-(id)initForContainerName:(id)arg1 contextID:(id)arg2 epoch:(unsigned long long)arg3 machineID:(id)arg4 modelID:(id)arg5 deviceName:(id)arg6 serialNumber:(id)arg7 osVersion:(id)arg8 ;
-(NSString *)containerName;
-(void)setContainerName:(NSString *)arg1 ;
-(NSString *)contextID;
-(void)setContextID:(NSString *)arg1 ;
-(unsigned long long)epoch;
-(void)setEpoch:(unsigned long long)arg1 ;
-(NSString *)deviceName;
-(void)setDeviceName:(NSString *)arg1 ;
-(NSString *)serialNumber;
-(NSString *)modelID;
-(NSString *)osVersion;
-(void)setOsVersion:(NSString *)arg1 ;
-(NSString *)machineID;
-(void)setMachineID:(NSString *)arg1 ;
-(void)setModelID:(NSString *)arg1 ;
-(void)setSerialNumber:(NSString *)arg1 ;
@end

