/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:50 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/securityd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <securityd/securityd-Structs.h>
#import <securityd/SecAKSRefKey.h>
@class NSData;


@protocol SecAKSRefKey <NSObject>
@property (readonly) NSData * refKeyBlob; 
@required
-(NSData *)refKeyBlob;
-(id)initWithKeybag:(int)arg1 keyclass:(int)arg2;
-(id)initWithBlob:(id)arg1 keybag:(int)arg2;
-(id)wrappedDataForKey:(id)arg1;
-(id)keyWithWrappedData:(id)arg1;

@end


@class NSData, NSString;

@interface SecAKSRefKey : NSObject <SecAKSRefKey> {

	aks_ref_key_sRef _refKey;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (readonly) NSData * refKeyBlob; 
-(NSData *)refKeyBlob;
-(id)initWithKeybag:(int)arg1 keyclass:(int)arg2 ;
-(id)initWithBlob:(id)arg1 keybag:(int)arg2 ;
-(id)wrappedDataForKey:(id)arg1 ;
-(id)keyWithWrappedData:(id)arg1 ;
-(void)dealloc;
@end

