/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 3:11:50 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /usr/libexec/securityd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class SecCDKeychainItemType, SecCDKeychainAccessControlEntity, NSUUID, NSDictionary, NSSet, NSData, NSArray;

@interface SecCDKeychainItemMetadata : NSObject {

	SecCDKeychainItemType* _itemType;
	SecCDKeychainAccessControlEntity* _owner;
	NSUUID* _persistentID;
	NSDictionary* _attributes;
	NSSet* _lookupAttributes;
	NSData* _managedDataBlob;
	int _keyclass;

}

@property (copy,readonly) NSSet * lookupAttributesSet;                      //@synthesize lookupAttributes=_lookupAttributes - In the implementation block
@property (copy,readonly) NSData * managedDataBlob;                         //@synthesize managedDataBlob=_managedDataBlob - In the implementation block
@property (readonly) SecCDKeychainItemType * itemType;                      //@synthesize itemType=_itemType - In the implementation block
@property (readonly) SecCDKeychainAccessControlEntity * owner;              //@synthesize owner=_owner - In the implementation block
@property (readonly) NSUUID * persistentID;                                 //@synthesize persistentID=_persistentID - In the implementation block
@property (copy,readonly) NSDictionary * attributes;                        //@synthesize attributes=_attributes - In the implementation block
@property (copy,readonly) NSArray * lookupAttributes; 
@property (readonly) int keyclass;                                          //@synthesize keyclass=_keyclass - In the implementation block
-(id)initWithItemType:(id)arg1 persistentID:(id)arg2 attributes:(id)arg3 lookupAttributes:(id)arg4 owner:(id)arg5 keyclass:(int)arg6 ;
-(id)initWithManagedItem:(id)arg1 keychain:(id)arg2 error:(id*)arg3 ;
-(void)fetchFullItemWithKeychain:(id)arg1 withConnection:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(NSArray *)lookupAttributes;
-(NSSet *)lookupAttributesSet;
-(NSData *)managedDataBlob;
-(BOOL)isEqual:(id)arg1 ;
-(id)description;
-(NSDictionary *)attributes;
-(id)primaryKeys;
-(NSUUID *)persistentID;
-(SecCDKeychainItemType *)itemType;
-(SecCDKeychainAccessControlEntity *)owner;
-(int)keyclass;
@end

