/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 2:00:52 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVPhotos.app/TVPhotos
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TVPhotos/TVPhotos-Structs.h>
#import <UIKitCore/UICollectionReusableView.h>

@class NSString, UILabel;

@interface TVPPhotoLibraryCollectionsHeaderView : UICollectionReusableView {

	BOOL _titleCenterAligned;
	BOOL _animateTitleForFocus;
	NSString* _collectionTitle;
	UILabel* _collectionTitleLabel;

}

@property (nonatomic,retain) UILabel * collectionTitleLabel;                                   //@synthesize collectionTitleLabel=_collectionTitleLabel - In the implementation block
@property (nonatomic,copy) NSString * collectionTitle;                                         //@synthesize collectionTitle=_collectionTitle - In the implementation block
@property (assign,getter=isTitleCenterAligned,nonatomic) BOOL titleCenterAligned;              //@synthesize titleCenterAligned=_titleCenterAligned - In the implementation block
@property (assign,nonatomic) BOOL animateTitleForFocus;                                        //@synthesize animateTitleForFocus=_animateTitleForFocus - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(NSString *)collectionTitle;
-(void)setCollectionTitle:(NSString *)arg1 ;
-(CGSize)_getAttributedStringSizeForText:(id)arg1 font:(id)arg2 ;
-(BOOL)animateTitleForFocus;
-(BOOL)isTitleCenterAligned;
-(void)setTitleCenterAligned:(BOOL)arg1 ;
-(void)setAnimateTitleForFocus:(BOOL)arg1 ;
-(UILabel *)collectionTitleLabel;
-(void)setCollectionTitleLabel:(UILabel *)arg1 ;
@end

