/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:17 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface MTImageDownloadClientRequest : NSObject {

	NSString* _uniqueId;
	NSString* _url;
	NSString* _key;
	/*^block*/id _completion;
	NSString* _uuid;

}

@property (nonatomic,readonly) NSString * uniqueId;              //@synthesize uniqueId=_uniqueId - In the implementation block
@property (nonatomic,readonly) NSString * url;                   //@synthesize url=_url - In the implementation block
@property (nonatomic,readonly) NSString * key;                   //@synthesize key=_key - In the implementation block
@property (nonatomic,readonly) id completion;                    //@synthesize completion=_completion - In the implementation block
@property (nonatomic,readonly) NSString * uuid;                  //@synthesize uuid=_uuid - In the implementation block
+(id)requestForUrl:(id)arg1 key:(id)arg2 podcastUuid:(id)arg3 completion:(/*^block*/id)arg4 ;
-(id)description;
-(NSString *)key;
-(id)completion;
-(NSString *)url;
-(NSString *)uuid;
-(NSString *)uniqueId;
-(id)initWithUrl:(id)arg1 key:(id)arg2 podcastUuid:(id)arg3 completion:(/*^block*/id)arg4 ;
@end

