/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:21 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PodcastsTVTopShelfExtension/MTSingleton.h>
#import <Podcasts/MTMediaLibraryTransactionManagerProtocol.h>

@protocol OS_dispatch_queue;
@class NSObject;

@interface MTMediaLibraryTransactionManager : MTSingleton <MTMediaLibraryTransactionManagerProtocol> {

	NSObject*<OS_dispatch_queue> _serialQueue;
	long long _counterForGeneratingLibraryChangeNotifications;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> serialQueue;                              //@synthesize serialQueue=_serialQueue - In the implementation block
@property (assign,nonatomic) long long counterForGeneratingLibraryChangeNotifications;              //@synthesize counterForGeneratingLibraryChangeNotifications=_counterForGeneratingLibraryChangeNotifications - In the implementation block
-(id)init;
-(NSObject*<OS_dispatch_queue>)serialQueue;
-(void)setSerialQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)requestMediaLibraryWriteTransaction:(/*^block*/id)arg1 ;
-(void)setCounterForGeneratingLibraryChangeNotifications:(long long)arg1 ;
-(void)requestMediaLibraryWriteTransaction:(/*^block*/id)arg1 completion:(/*^block*/id)arg2 ;
-(long long)counterForGeneratingLibraryChangeNotifications;
-(void)_endGeneratingLibraryChangeNotifications;
-(void)_beginGeneratingLibraryChangeNotifications;
-(void)beginGeneratingLibraryChangeNotifications:(/*^block*/id)arg1 ;
-(void)endGeneratingLibraryChangeNotifications:(/*^block*/id)arg1 ;
-(void)requestMediaLibraryReadTransaction:(/*^block*/id)arg1 ;
@end

