/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:20 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTMediaContentSource.h>

@interface MTMediaContentSourceiOSMusicLibrary : MTMediaContentSource {

	BOOL _iTunesMatchEnabled;

}

@property (nonatomic,readonly) BOOL iTunesMatchEnabled;              //@synthesize iTunesMatchEnabled=_iTunesMatchEnabled - In the implementation block
+(id)sharedInstance;
-(void)determineiTunesMatchEnabledWithCompletion:(/*^block*/id)arg1 ;
-(BOOL)iTunesMatchEnabled;
@end

