/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:19 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class AVPlayerItemAccessLogEvent, MTEpisodeMetricDataSource;

@interface MTPlayMetricsEvent : NSObject {

	BOOL _recorded;
	AVPlayerItemAccessLogEvent* _accessLogEvent;
	MTEpisodeMetricDataSource* _dataSource;

}

@property (nonatomic,retain) AVPlayerItemAccessLogEvent * accessLogEvent;              //@synthesize accessLogEvent=_accessLogEvent - In the implementation block
@property (nonatomic,retain) MTEpisodeMetricDataSource * dataSource;                   //@synthesize dataSource=_dataSource - In the implementation block
@property (assign,getter=isRecorded,nonatomic) BOOL recorded;                          //@synthesize recorded=_recorded - In the implementation block
+(id)eventWithAccessLog:(id)arg1 dataSource:(id)arg2 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)_data;
-(MTEpisodeMetricDataSource *)dataSource;
-(void)setDataSource:(MTEpisodeMetricDataSource *)arg1 ;
-(void)record;
-(BOOL)isRecorded;
-(id)initWithAccessLogEvent:(id)arg1 dataSource:(id)arg2 ;
-(void)setAccessLogEvent:(AVPlayerItemAccessLogEvent *)arg1 ;
-(void)setRecorded:(BOOL)arg1 ;
-(AVPlayerItemAccessLogEvent *)accessLogEvent;
@end

