/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:22 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface MTPrivacyUtil : NSObject
+(BOOL)cloudSyncIsDirty;
+(BOOL)allowReporting;
+(id)cloudSyncVersion;
+(void)resetToInitialState;
+(BOOL)shouldShowTermsScreen;
+(void)markAsAgreedToLatestTerms;
+(id)deviceAgreedTermsVersion;
+(id)accountAgreedTermsVersion;
+(void)setAccountAgreedTermsVersion:(id)arg1 ;
+(void)setCloudSyncVersion:(id)arg1 ;
+(void)setCloudSyncIsDirty:(BOOL)arg1 ;
+(void)setDeviceAgreedTermsVersion:(id)arg1 ;
@end

