/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:50:21 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKitCore/UIView.h>

@protocol MTTVPodcastHeaderViewDelegate;
@class UILabel, MTTVPodcastDetailsSectionControl, MTPodcast;

@interface MTTVPodcastHeaderView : UIView {

	UILabel* _titleLabel;
	MTTVPodcastDetailsSectionControl* _sectionControl;
	MTPodcast* _podcast;
	id<MTTVPodcastHeaderViewDelegate> _delegate;

}

@property (nonatomic,retain) MTPodcast * podcast;                                            //@synthesize podcast=_podcast - In the implementation block
@property (assign,nonatomic) unsigned long long selectedTab; 
@property (assign,nonatomic,__weak) id<MTTVPodcastHeaderViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id)init;
-(id<MTTVPodcastHeaderViewDelegate>)delegate;
-(void)setDelegate:(id<MTTVPodcastHeaderViewDelegate>)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(MTPodcast *)podcast;
-(void)layoutSubviews;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)setPodcast:(MTPodcast *)arg1 ;
-(BOOL)canBecomeFocused;
-(id)preferredFocusedView;
-(unsigned long long)selectedTab;
-(void)setSelectedTab:(unsigned long long)arg1 ;
-(void)configureSubviews;
-(void)updateTextColors;
-(id)initWithPodcast:(id)arg1 delegate:(id)arg2 ;
-(void)sectionControlDidChange:(id)arg1 ;
@end

