/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:07:55 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVAirPlay.app/TVAirPlay
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol APRKStreamRenderingManagerDelegate <NSObject>
@required
-(void)didStartStreamingWithRenderer:(id)arg1;
-(void)didStopStreamingWithRenderer:(id)arg1;
-(void)shouldShowGlobalPasscodeWithString:(id)arg1 withClientName:(id)arg2;
-(void)shouldHideGlobalPasscode;

@end

