/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 1:07:55 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVAirPlay.app/TVAirPlay
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TVAirPlay/TVAirPlay-Structs.h>
#import <UIKitCore/UIView.h>

@class CALayer;

@interface TVAirPlayAPRKMirroringView : UIView {

	CALayer* _mirroringLayer;
	CALayer* _HUDLayer;

}

@property (nonatomic,retain) CALayer * mirroringLayer;              //@synthesize mirroringLayer=_mirroringLayer - In the implementation block
@property (nonatomic,retain) CALayer * HUDLayer;                    //@synthesize HUDLayer=_HUDLayer - In the implementation block
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(BOOL)canBecomeFocused;
-(CALayer *)mirroringLayer;
-(CALayer *)HUDLayer;
-(id)initWithMirroringLayer:(id)arg1 HUDLayer:(id)arg2 ;
-(void)setMirroringLayer:(CALayer *)arg1 ;
-(void)setHUDLayer:(CALayer *)arg1 ;
@end

