/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 12:49:52 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVHomeSharing.app/TVHomeSharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TVHomeSharing/TVHJSObject.h>
#import <TVHomeSharing/TVHJSMediaCategoryTypesFetchControllerResult.h>
@class NSString, TVHJSMediaQueryResult;


@protocol TVHJSMediaCategoryTypesFetchControllerResult <JSExport>
@property (nonatomic,copy,readonly) NSString * queryReason; 
@property (nonatomic,readonly) TVHJSMediaQueryResult * mediaCategoryTypesResult; 
@required
-(NSString *)queryReason;
-(TVHJSMediaQueryResult *)mediaCategoryTypesResult;

@end


@class NSString, TVHJSMediaQueryResult;

@interface TVHJSMediaCategoryTypesFetchControllerResult : TVHJSObject <TVHJSMediaCategoryTypesFetchControllerResult> {

	NSString* _queryReason;
	TVHJSMediaQueryResult* _mediaCategoryTypesResult;

}

@property (nonatomic,copy) NSString * queryReason;                                          //@synthesize queryReason=_queryReason - In the implementation block
@property (nonatomic,retain) TVHJSMediaQueryResult * mediaCategoryTypesResult;              //@synthesize mediaCategoryTypesResult=_mediaCategoryTypesResult - In the implementation block
-(id)initWithAppContext:(id)arg1 ;
-(NSString *)queryReason;
-(void)setQueryReason:(NSString *)arg1 ;
-(TVHJSMediaQueryResult *)mediaCategoryTypesResult;
-(void)setMediaCategoryTypesResult:(TVHJSMediaQueryResult *)arg1 ;
-(id)initWithMediaCategoryTypesFetchControllerResult:(id)arg1 appContext:(id)arg2 ;
@end

