/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 12:49:52 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVHomeSharing.app/TVHomeSharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TVHomeSharingKit/TVHKMediaEntityServerOperation.h>

@class IKAppContext;

@interface TVHMediaEntityServerOperation : TVHKMediaEntityServerOperation {

	IKAppContext* _appContext;

}

@property (assign,nonatomic,__weak) IKAppContext * appContext;              //@synthesize appContext=_appContext - In the implementation block
-(void)setAppContext:(IKAppContext *)arg1 ;
-(IKAppContext *)appContext;
-(id)initWithMediaEntityServer:(id)arg1 ;
-(id)initWithMediaEntityServer:(id)arg1 appContext:(id)arg2 ;
@end

