/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 12:49:52 PM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /Applications/TVHomeSharing.app/TVHomeSharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TVHomeSharing/TVHomeSharing-Structs.h>
#import <TVHomeSharing/TVPPlaybackViewControllerDelegate.h>

@class TVPPlaybackViewController, NSString;

@interface TVHNowPlayingManager : NSObject <TVPPlaybackViewControllerDelegate> {

	TVPPlaybackViewController* _nowPlayingViewController;

}

@property (nonatomic,retain) TVPPlaybackViewController * nowPlayingViewController;              //@synthesize nowPlayingViewController=_nowPlayingViewController - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedInstance;
+(id)_contextMenuDataWithMenuItems:(id)arg1 title:(id)arg2 artistName:(id)arg3 ;
+(id)_mediaItemForPlayerMediaItem:(id)arg1 ;
-(id)init;
-(void)dealloc;
-(void)contextMenuForMediaItem:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(TVPPlaybackViewController *)nowPlayingViewController;
-(void)setNowPlayingViewController:(TVPPlaybackViewController *)arg1 ;
-(void)_handleNowPlayingViewWillAppearNotification:(id)arg1 ;
-(void)_handleNowPlayingViewDidDisappearNotification:(id)arg1 ;
-(id)_displayAlbumArtistMenuWithPlayerMediaItem:(id)arg1 ;
-(id)_displayAlbumMenuWithPlayerMediaItem:(id)arg1 ;
-(void)_displayCollectionForMediaItem:(id)arg1 collectionType:(unsigned long long)arg2 ;
-(id)_displayCollectionURLForMediaItem:(id)arg1 collectionType:(unsigned long long)arg2 ;
-(void)showNowPlayingViewControllerIfNeeded;
@end

